.github/workflows/add-to-project.yml
.github/workflows/docs-gen-and-push.yaml
.github/workflows/e2e-ci-ppc64le.yml

updating workflows to point at edge-mc repo instead of kcp

---

.github/workflows/OWNERS

updating owners file for approval of PRs

---

README.md

📖 Minor stuff in README.md

---

README.md

Signed-off-by: Paolo Dettori <dettori@us.ibm.com>
Fixes #17

🐛 bug fix:  fix broken doc link in README

---

OWNERS

Signed-off-by: Ezra Silvera <ezra@il.ibm.com>
Fixes #

🐛 🐛 Add initial owners

---

.ci-operator.yaml

🌱 adding ci-operator.yml file for the purpose of enabling PROW

---

hack/tools.go
hack/verify-contextual-logging.sh

added tools.go and verify-contextual-logging.sh

---

.github/workflows/e2e-ci-ppc64le.yml
Dockerfile
hack/verify-go-versions.sh

added verify-go-versions.sh and commented out local e2e test for PRs

---

Makefile

removed make test target for now

---

pkg/apis/OWNERS

🐛 added /pkg/apis/OWNERS

---

README.md

Update root README.md to add building icon
Fixes #42

:book: Update root README.md to add building icon

---

README.md

Signed-off-by: Paolo Dettori <dettori@us.ibm.com>
change KCP to lowercase in README
Fixes #45

🐛: change KCP to lowercase in README

---

main.go

We don't have an edge placement controller yet.

🌱 Correct controller name

---

Makefile

attempting to fix codegen by pulling updates from from KCP makefile
Fixes #

:bug: updating makefile to match KCP

---

pkg/reconciler/scheduling/placement/controller.go

Switched to lowerCamelCase as stipulated in
https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/migration-to-structured-logging.md#name-arguments
Fixes #

:bug: Fix case in message keys

---

hack/verify-contextual-logging.sh

This PR undoes #69, which I did not intend for merging.
Fixes #

🌱 Revert PR 69

---

Makefile
hack/update-codegen-clients.sh

update for update-codegen-clients.sh - replaced references to kcp with edge-mc, and also commented out some sections not currently in use.
Fixes #

:bug: update for update-codegen-clients.sh

---

go.mod

This PR merges the top two requirements blocks in go.mod, because there is no reason to keep them distinct.
Fixes #

🌱 Merge two requirements sections in go.mod

---

cmd/placement/README.md

📖 Improve README.md for the separated TMC placement controller

---

Makefile
hack/update-codegen-crds.sh

added API_GEN to the pre-reqs for the make crds section header to res…
Fixes #140

:bug: updated api-gen call to include repo_root

---

cmd/mailbox-controller/main.go

This PR re-organizes the imports of the mailbox controller to keep `make impors` happy.
Fixes #

🌱 Make mailbox controller source consistent with `make imports`

---

config/crds/edge.kcp.io_singleplacementslices.yaml
config/exports/apiexport-edge.kcp.io.yaml
config/exports/apiresourceschema-singleplacementslices.edge.kcp.io.yaml
pkg/apis/edge/v1alpha1/single-placement.go

🐛 Fix incorrect plural forms for SinglePlacementSlice

---

docs/poc2023q1/edge-scheduler.md

This PR adds missing parts to the documentation of edge-scheduler, as specified in #195 (thanks to @MikeSpreitzer).
Fixes #195

📖 Update the doc for edge-scheduler

---

docs/content/en/docs/Contribution guidelines/LICENSE.md

Improve pagination in documentation
Fixes #

📖 Remove CR

---

docs/content/en/docs/Contribution guidelines/LICENSE.md

Removing line carriage
Fixes #

📖 Update LICENSE.md

---

docs/poc2023q1/outline.md

This PR updates the 2023q1 PoC outline to address issues of workload conflicts.
Fixes #

:book: Address workload conflicts in 2023q1 PoC

---

README.md

:book Update wording say to specify

---

docs/content/en/docs/Contribution guidelines/LICENSE.md

📖 : Update LICENSE.md

---

docs/poc2023q1/edge-scheduler.md

📖 Update docs for edge scheduler regarding kcp version

---

docs/poc2023q1/example1.md

This PR adds a clarification to the PoC example walk-through.
Fixes #
/cc @ezrasilvera

📖 Add clarifications to PoC example scenario

---

cmd/mailbox-controller/controller.go
cmd/mailbox-controller/main.go
docs/poc2023q1/mailbox-controller.md

This PR does the following things.
- Separate out an identifiable controller, with constructor taking any suitable pre-informers and clients.
- Rationalize some names.
- Also fix some oversights in the doc.
The main motivation is to make a clear boundary so that a behavioral unit test can be written.
Fixes #

🌱 Factor mailbox controller

---

docs/content/en/docs/Coding Milestones/PoC2023q1/coding-milestone-invite-q1.md

This PR makes two updates to the coding invitation:
1. Remove the obsolete mention of finishing the mailbox controller;
2. Add mention of associated objects.
Fixes #

📖 Update coding invite

---

pkg/placement/reducer_test.go
pkg/placement/test_uider.go
pkg/scheduler/reconcile_on_edgeplacement.go
pkg/scheduler/reconcile_on_location.go
pkg/scheduler/reconcile_on_synctarget.go

This PR yet again does an overlooked `make imports`.
@clubanderson : maybe CI should check for this?
Fixes #

🌱 make imports

---

pkg/apis/edge/v1alpha1/register.go

This fixes an oversight from earlier.
This completes the earlier PR that adds the customization API.
Fixes #

🐛 Register the Customizer API

---

go.mod

Looks like `k8s.io/apiextensions-apiserver` is now a direct dependency.

🌱 go mod tidy

---

CONTRIBUTING.md

Docs: Update CONTRIBUTING.md regarding golang pre-req version

---

cmd/placement-translator/main.go
pkg/placement/cluster-name-and-path.go
pkg/placement/declarations.go
pkg/placement/main.go
pkg/placement/map-types.go
pkg/placement/reducer_test.go
pkg/placement/relay-map.go
pkg/placement/set-binder-test.go
pkg/placement/simple-reducer.go
pkg/placement/single-placement-set.go
pkg/placement/test-apimap-provider.go
pkg/placement/test_uider.go
pkg/placement/test_uider_test.go

This PR adds a little more commentary and type definitions showing what I expect to be the internal structure of a SetBinder.  I introduced some more generic abstractions that seemed relevant, and revised some existing ones for more consistency.
Fixes #

✨ Refinements wrt SetBinder, main

---

cmd/cluster-watchall/main.go
cmd/placement-translator/main.go
docs/content/en/docs/Coding Milestones/PoC2023q1/placement-translator.md
pkg/placement/main.go
pkg/placement/what-resolver.go

This PR is a work-in-progress and shows the begging of the work on implementing the placement translator.
This is built on #229 and I will rebase after #229 merges.
Fixes #

✨ Start placement translator

---

docs/content/en/docs/Coding Milestones/PoC2023q1/example1.md

This PR fixes bugs discovered while testing the nascent placement translator (#245).
Fixes #

🐛 Fix bugs in example scenario

---

CODE_OF_CONDUCT.md

📖 Create CODE_OF_CONDUCT.md

---

docs/content/en/docs/Coding Milestones/PoC2023q1/edge-scheduler.md

This PR updates the doc for the scheduler to keep up with recent progress on code.
Closes #268.

📖 Update doc for edge scheduler

---

pkg/mailboxwatch/impl.go
pkg/mailboxwatch/impl_test.go
pkg/mailboxwatch/interface.go
pkg/mailboxwatch/listwatch.go

This PR provides the first draft of the implementation of informers for workload objects in mailbox workspaces.
Fixes #

✨ First draft of implementation of mailbox informers

---

docs/content/en/docs/Coding Milestones/PoC2023q1/mailbox-controller.md

This PR improves the documentation for trying out the mailbox controller.

:book: improve docs for mailbox controller

---

docs/content/en/docs/Coding Milestones/PoC2023q1/example1.md
docs/content/en/docs/Coding Milestones/PoC2023q1/placement-translator.md

This PR makes some improvements and fixes some typos in the current 2023q1 PoC docs for example1 and placement translator.

:book: improvements to example1 and placement-translator docs

---

docs/content/en/docs/Coding Milestones/PoC2023q1/example1.md

This PR fixes some typos in our docs.

 🐛 Typo fix to example1

---

pkg/syncer/controller/controller.go
pkg/syncer/controller/controller_test.go
pkg/syncer/syncer.go
pkg/syncer/syncers/client.go
pkg/syncer/syncers/common.go
pkg/syncer/syncers/downsyncer.go
pkg/syncer/syncers/upsyncer.go

This PR fixes up import lists again.
Fixes #

🌱 make imports again

---

pkg/mailboxwatch/impl_test.go

This PR fixes a confusion of two identifiers in the unit test for mailboxwatch.
Fixes #

🐛 Fix object name vs cluster confusion in mailboxwatch unit test

---

docs/content/en/docs/Coding Milestones/PoC2023q1/edge-syncer.md

Update edge-syncer.md to add the description about which EdgeSyncConfig is watched by EdgeSyncer. 
https://github.com/kcp-dev/edge-mc/pull/284#issuecomment-1499794730

📖 update edge-syncer.md

---

cmd/placement-translator/main.go
docs/content/en/docs/Coding Milestones/PoC2023q1/placement-translator.md
hack/logcheck.out
pkg/placement/apiwatch-map-provider.go
pkg/placement/binding-organizer.go
pkg/placement/declarations.go
pkg/placement/dummies.go
pkg/placement/join-dynamic-12vwith13.go
pkg/placement/join-static.go
pkg/placement/main.go
pkg/placement/map-factored-aggregate.go
pkg/placement/map-factored-aggregate_test.go
pkg/placement/map-factored.go
pkg/placement/map-types.go
pkg/placement/set-binder-assembly.go
pkg/placement/set-indexed.go
pkg/placement/set-types.go
pkg/placement/slices.go
pkg/placement/test-apimap-provider.go
pkg/placement/workload-projector.go

The PR continues development of the placement translator.
It has gotten as far as maintaining the syncer config objects (new style).  It seems to create configs OK, but there is some bug in reacting to deletion of an EdgePlacement.
Fixes #
/cc @yana1205 
@yuji-watanabe-jp

✨ Placement translator development

---

pkg/mailboxwatch/impl_test.go

This PR attempts to fix problem in pkg/mailboxwatch/impl_test.go.
But no, the tracker still has no watchers when the workspace is added.
Even so, this is progress: it invokes the inforner factory's Start method.
Fixes #

🐛 Attempt to fix problem in pkg/mailboxwatch/impl_test.go

---

cmd/mailbox-controller/main.go
cmd/scheduler/options/options.go
pkg/client-options/options.go

This PR gives better names to ClientOpts' methods. Thanks to @MikeSpreitzer 's suggestions.

🌱 Better names for ClientOpts methods

---

cmd/placement-translator/main.go
docs/content/en/docs/Coding Milestones/PoC2023q1/example1.md
hack/logcheck.out
pkg/placement/binding-organizer.go
pkg/placement/declarations.go
pkg/placement/external-name.go
pkg/placement/hash-domain.go
pkg/placement/main.go
pkg/placement/map-relation.go
pkg/placement/map-set-differencer.go
pkg/placement/map-types.go
pkg/placement/relation-types.go
pkg/placement/rotations_test.go
pkg/placement/set-binder-assembly.go
pkg/placement/set-binder-test.go
pkg/placement/set-hash.go
pkg/placement/set-indexed.go
pkg/placement/set-project.go
pkg/placement/slices.go
pkg/placement/tuples.go
pkg/placement/what-resolver.go
pkg/placement/workload-projector.go

It is mostly working now.
Fixes #
/cc @yana1205 
/cc @waltforme

✨ Yet more placement translator development

---

docs/content/en/docs/Coding Milestones/PoC2023q1/outline.md

This PR updates the PoC outline to recognize that certain individual objects are part of the nature of some other object or system and should be excepted from downsync.
Fixes #

📖 Document special handling of system infrastructure objects

---

docs/content/en/docs/Coding Milestones/PoC2023q1/example1.md

This PR fixes one typo.
Fixes #
/cc @waltforme

📖 Fix another typo: wit vs with

---

cmd/ls-syncer-config/README.md
cmd/ls-syncer-config/main.go

This PR adds a demonstration of what does and does not work regarding client access to resources not built into kcp.
Fixes #
/cc @dumb0002 
/cc @yana1205

✨ Add cmd/ls-syncer-config

---

docs/content/en/docs/Coding Milestones/PoC2023q1/example1.md

This PR updates example1.md to include concrete details of using the edge syncer.
Fixes #
/cc @yana1205 
/cc @dumb0002 
/cc @ezrasilvera 
@francostellari 
@KPRoche

📖 Update example1.md to reflect current state

---

cmd/ls-syncer-config/main.go
pkg/syncer/controller/controllerbase.go
pkg/syncer/controller/syncerconfigcontroller.go
pkg/syncer/controller/syncerconfigcontroller_test.go
pkg/syncer/controller/syncerconfigmanager.go
test/e2e/edgesyncer/common_test.go

This PR tidies up imports yet again.  It is the result of running `make imports`.  CI should be checking for lack of this.
Fixes #
/cc @yana1205 
/cc @waltforme

✨ make imports yet again

---

docs/content/en/docs/Coding Milestones/PoC2023q1/placement-translator.md
pkg/placement/set-types.go
pkg/placement/slices.go
pkg/placement/workload-projector.go

This PR changes the placement translator to remedy the oversights noted in issue #320.
It was not reacting to workload objects in the mailbox workspace regardless of whether they are desired, so not all undesired ones were not being deleted.
It was not reconsidering all the source objects when the projection criteria change, so consequent deltas were not happening.
Fixes #320 
/cc @yana1205 

🐛 Make placement translator react more fully.

---

Makefile
docs/content/en/docs/Coding Milestones/PoC2023q1/edge-syncer.md

- Add tasks to build edge-syncer image to Makefile
- Add the description about how to build edge-syncer image
Fixes https://github.com/kcp-dev/edge-mc/pull/329#issuecomment-1519208167

📖 Update edge-syncer doc to include how to build edge-syncer image

---

docs/content/en/docs/Coding Milestones/PoC2023q1/example1.md
docs/content/en/docs/Coding Milestones/PoC2023q1/scripts.md
scripts/ensure-wmw.sh

This PR adds a script that automates the steps in creating a workload management workspace.
Fixes #
/cc @dumb0002

✨ Create scripts/ensure-wmw.sh

---

Makefile
hack/make-release-platform-archive.sh

This PR adds a script for building the archive for users to use for a given platform.
Fixes #

✨ Start drafting release building

---

scripts/mailbox-prep.sh

Update the syncer image to match the release v0.1.0
Fixes #

:seedling: Update syncer image tag to v0.1.0

---

docs/content/en/docs/Coding Milestones/PoC2023q1/placement-translator.md

This PR corrects the displayed SyncerConfig object contents in the placement translator doc, removing the obsolete mentions of customizers.
Fixes #
/cc @yana1205

🐛 Update displays of SyncerConfig objects

---

examples/common-placement.yaml
examples/common-workload.yaml
examples/florin-config.yaml
examples/guilder-config.yaml
examples/special-placement.yaml
examples/special-workload.yaml
hack/make-release-platform-archive.sh

This PR introduces the examples/ directory to hold files used in the examples.
This PR also adds examples/ and config/ to the directories that go into each release archive.
Fixes #
/cc @dumb0002 

✨ Introduce examples/, add it and config/ to tarchive

---

scripts/kubectl-kubestellar-prep_for_syncer

Point to the new quay.io registetry
Fixes #

:sparkles: Update the syncer image registry in kubectl-kubestellar-prep_script

---

scripts/kubestellar

This PR updates  KubeStellar script to use the renamed kubestellar-scheduler
Fixes #

✨ Updating KubeStellar script to use the renamed kubestellar-scheduler

---

bootstrap/bootstrap-kubestellar.sh
bootstrap/install-kcp-with-plugins.sh
bootstrap/install-kubestellar.sh

1. Moved from hack --> bootstrap
2. Removed `--create-folder`, now default to create
3. Changed `--folder` --> `--ensure-folder`
4. Change `kcp-edge.sh` --> `kubestellar`
Fixes #

:bug: Update install/bootstrap scripts

---

docs/content/en/docs/Coding Milestones/PoC2023q1/commands.md

This PR extends the document on user commands to include the others (besides the kubectl plugins).  That is, `kubestellar` and the bootstrap scripts.
Fixes #
/cc @dumb0002

✨ Revise the user commands doc to include the rest

---

scripts/kubestellar
scripts/remove-kubestellar

This PR fixes issues with kubestellar and remove-kubestellar scripts
Fixes #

🐛 Fixing issues with kubestellar and remove-kubestellar scripts

---

QUICKSTART.md

This PR fixing typos and issues from the Quickstart example
Fixes #

🐛 Fixing and typos issues with Quickstart

---

QUICKSTART.md

added instructions to prevent error with kind cluster pre-existence, curl not working, and guilder prep not running due to wrong workspace location.
Fixes #

❇️ Update QUICKSTART.md

---

bootstrap/bootstrap-kubestellar.sh

added a 'KubeStellar bootstrap started...'
Fixes #

✨ Update bootstrap-kubestellar.sh

---

QUICKSTART.md

This PR extends the quickstart to mention that removing the example includes removing the generated syncer YAML files.
Fixes #
/cc @dumb0002 

🐛 Include removal of syncer YAML files in example cleanup

---

QUICKSTART.md

Fixing typos in the Quickstart.
Fixes #

 📖  Fixing a typo in QUICKSTART.md

---

bootstrap/bootstrap-kubestellar.sh
bootstrap/install-kcp-with-plugins.sh
bootstrap/install-kubestellar.sh
docs/content/en/docs/Coding Milestones/PoC2023q1/commands.md

This PR adds a debugging option to startup scripts.
Fixes #
/cc @dumb0002 

✨ Add the `-X` option to setup scripts

---

docs/content/en/docs/Coding Milestones/PoC2023q1/commands.md

This PR fixes up the introduction and some heading levels in commands.md
Fixes #
/cc @dumb0002 

🐛 Fix some issues in commands.md

---

bootstrap/bootstrap-kubestellar.sh

This PR fixes a goofup in the bootstrap command line parsing.
Fixes #
/cc @dumb0002 
@clubanderson

🐛 Fix goofup in bootstrap command line parsing

---

bootstrap/bootstrap-kubestellar.sh
bootstrap/install-kcp-with-plugins.sh
bootstrap/install-kubestellar.sh

This PR does two things: it makes the echo of the current working directory show the literal directory, and it removes some redundant exit commands.
Fixes #

✨ Improve PWD echo, remove redundant exits in bootstrap

---

QUICKSTART.md

added estimate time and updated title for the png.
Fixes #

✨ Update QUICKSTART.md

---

README.md

🐛 Fix nits in README.md

---

CONTRIBUTING.md

This PR revises and extends the comments in CONTRIBUTING.md about testing, to better serve contributors and explicitly discuss how to cope with the implications of our curl-to-bash.
Fixes #
/cc @dumb0002 
/cc @waltforme

✨ Extend testing remarks in CONTRIBUTING.md

---

QUICKSTART.md

This PR updates the QUICKSTART.md to include a pointer to example1 and have a more complete introductory sentence.
Fixes #
/cc @dumb0002

✨ Make QUICKSTART include reference to example1

---

Makefile

This PR fixes an oversight in the Makefile, where it omitted the image tag from the line that says what it is going to do.
Fixes #

:bug:Fix omission in Makefile

---

cmd/kubestellar-version/main.go
docs/content/en/docs/Coding Milestones/PoC2023q1/commands.md

This PR introduces an executable that reports on properties captured at build time.
This may help with the container image part of #395
/cc @dumb0002

✨ Introduce kubestellar-version

---

docs/content/Coding Milestones/PoC2023q1/outline.md

This PR fixes the outline.md doc to use the relevant kcp release in its reference to the Location and SyncTarget APIs.
Fixes #
/cc @dumb0002

🐛 Pin outline.md reference to kcp APIs to v0.11.0

---

docs/content/Coding Milestones/PoC2023q1/commands.md

This PR updates the documentation of the user-facing commands.  The main point of this PR is to add an explanation for each command line flags, and do it in the style common for documenting Linux commands.  This includes documenting the default value for the syncer image (which I hope to change in the next release --- which is why explicit documentation and versioning of the documentation matters).
This PR also adds some **NOTE**s about limitations.
This PR also corrects the case in "KubeStellar" in the commands.md file.
Fixes #
/cc @yana1205 
/cc @dumb0002

✨ Update commands doc, incl spec default syncer image

---

bootstrap/bootstrap-kubestellar.sh

1. do not use external scrips anymore
2. introduces additional checks on kcp (including version) and kubestellar
3. more messages even without -V
4. suggest solutions on errors
#400 ? could be better if #395 is solved i.e. `kubestellar version`
#406 
#413
Fixes #

:sparkles: More reliable bootstrap

---

Dockerfile
hack/boilerplate/boilerplate.Dockerfile.txt

Update KCP to KubeStellar
Fixes #

✨ Update boilerplate.Dockerfile.txt

---

Makefile
hack/boilerplate/boilerplate.Makefile.txt

update kcp with KubeStellar
Fixes #

✨ Update boilerplate.Makefile.txt

---

CONTRIBUTING.md

updating contributing.md to point at the QS in the main branch of the docs
Fixes #

✨ Update CONTRIBUTING.md pointer to QuickStart

---

bootstrap/bootstrap-kubestellar.sh
bootstrap/install-kcp-with-plugins.sh
bootstrap/install-kubestellar.sh
docs/scripts/deploy-docs.sh
docs/scripts/serve-docs.sh
hack/boilerplate/boilerplate.sh.txt
hack/go-install.sh
hack/make-release-container.sh
hack/make-release-full.sh
hack/make-release-platform-archive.sh
hack/update-codegen-clients.sh
hack/update-codegen-crds.sh
hack/validate-k8s.sh
hack/verify-codegen-clients.sh
hack/verify-contextual-logging.sh
hack/verify-go-versions.sh
hack/verify-imports.sh

update kcp with kubestellar
Fixes #

✨ Update boilerplate.sh.txt

---

docs/home.html

✨ Create home.html

---

hack/boilerplate/boilerplate.py.txt

update kcp with KubeStellar
Fixes #

✨ Update boilerplate.py.txt

---

hack/boilerplate/boilerplate.generatego.txt

update kcp with KubeStellar
Fixes #

✨ Update boilerplate.generatego.txt

---

scripts/kubectl-kubestellar-ensure-location
scripts/kubectl-kubestellar-ensure-wmw
scripts/kubectl-kubestellar-prep_for_cluster
scripts/kubectl-kubestellar-prep_for_syncer
scripts/kubectl-kubestellar-remove-location
scripts/kubectl-kubestellar-remove-wmw
scripts/kubestellar
scripts/remove-kubestellar

✨ updating the remaining files that need the new boilerplate

---

docs/content/index.md

Updated text and link for our new slack channel.
Fixes #

✨ Update index.md with new slack link

---

Makefile

✨ Update Makefile - replace reference to kcp-edge

---

cmd/placement-translator/main.go
docs/content/Coding Milestones/PoC2023q1/example1.md
docs/content/Coding Milestones/PoC2023q1/placement-translator.md
pkg/placement/main.go
pkg/placement/workload-projector.go

This PR updates the workload projector to apply customization.
It works on projection, but does not yet attempt to react to change in Customizer or Location.
Fixes #
/cc @waltforme

🌱 Start adding customization to workload projector

---

docs/content/Coding Milestones/PoC2023q1/example1.md
docs/content/Getting-Started/quickstart.md
examples/guilder-config.yaml

based on feedback from partner - OpenZiti
changes are needed in docs as well (QS, etc)
Fixes #

✨ Update guilder-config.yaml to use not-so-common port

---

docs/content/Coding Milestones/PoC2023q1/commands.md

:sparkles: Update commands.md to pull in updates in pr420

---

CONTRIBUTING.md

This PR fixes the following:
-  KubeStellar slack channel 
-  Broken link for example1
Fixes #

📖  Fixes for CONTRIBUTING.md

---

docs/content/Coding Milestones/PoC2023q1/example1.md
examples/guilder-config.yaml
examples/special-workload.yaml

and update all other references to port 8082 in doc
Fixes #

:sparkles: Update guilder-config.yaml - second host port to 8097

---

docs/content/Getting-Started/quickstart.md

:sparkles: Update quickstart.md - add jq req

---

docs/content/Getting-Started/quickstart.md

:sparkles: Update quickstart.md - open reqs in new browser tab

---

.github/workflow-settings.json

:sparkles: Update workflow-settings.json

---

docs/content/Getting-Started/quickstart.md

This PR updates the creation of the Florin and Guilder cluster for inline(text)
Fixes #

📖 Updating QuickStart: command to create kind clusters

---

docs/content/Getting-Started/quickstart.md

:sparkles: Update quickstart.md toc 

---

docs/content/Coding Milestones/PoC2023q1/edge-syncer.md
pkg/syncer/README.md

Same PR as https://github.com/kcp-dev/edge-mc/pull/479 for release-0.2 branch
Fixes #

:bug: Correct broken links in docs related with syncer for release-0.2 branch

---

docs/content/Getting-Started/quickstart.md

:sparkles: Update quickstart.md with port 8094 for florin

---

docs/content/Community/partners/argocd.md

This PR tweaks the freshly copied Argo CD integration doc to make it to be more in context.

:sparkles: Tweak the migrated Argo CD integration doc

---

docs/content/Getting-Started/quickstart.md

Fixes #534 to move video to top of the page and make clear that error is expected to happen and try again.

:sparkles: Update quickstart.md

---

SECURITY.md
SECURITY_CONTACTS

required for CNCF sandbox and for IBM Dev Advocates office
Fixes #

:sparkles: Create SECURITY_CONTACTS and SECURITY.md

---

ONBOARDING.md

required for IBM Dev Advocate satisfaction of terms
Fixes #

:sparkles: Create ONBOARDING.md

---

bootstrap/bootstrap-kubestellar.sh

:book: Fix bootstrap-kubestellar.sh typos

---

docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler.md

This PR updates the scheduler doc to fit into the newly created CI feature of doc testing.

🌱 Update scheduler doc

---

.github/spellcheck/.wordlist.txt
docs/content/Coding Milestones/PoC2023q1/edge-syncer.md
pkg/syncer/README.md
pkg/syncer/scripts/edge-syncer-bootstrap.template.yaml

Same changes as https://github.com/kcp-dev/edge-mc/pull/550 for release-0.2 branch
Fixes #

:book: Fix documentation about syncer-gen plugin (for release-0.2)

---

docs/content/Community/partners/argocd.md

This PR documents Argo CD's resource exclusion for kcp's ClusterWorkspace.
/cc @fileppb

📖 Document Argo CD's resource exclusion for kcp's ClusterWorkspace

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler-subs/kubestellar-scheduler-0-pull-kcp-and-kubestellar-source-and-start-kcp.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer.md
docs/content/Coding Milestones/PoC2023q1/mailbox-controller.md

Did a high level edit of the documents (grammar, formatting, etc).

:book: first edit of the docs

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-0-deploy-florin.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-0-deploy-guilder.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-1-syncer-gen-plugin.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer.md

fixed the link to specify kcp release 0.11.0 and changed references from edge-syncer to KubeStellar-Syncer

📖 specified kcp release link & updated syncer refs

---

cmd/json-path-replace/main.go

This PR mainly tries to make the output of the json-path-replace command a little cleaner. It also suggests a name change to a variable.

✨ Append newlines to the outputs for json-path-replace

---

docs/content/Community/partners/argocd.md
docs/content/Community/partners/kyverno.md
docs/content/Community/partners/turbonomic.md
docs/content/Getting-Started/infomercial.md
docs/content/Getting-Started/quickstart-subs/quickstart-0-demo.md

fixed spinner onload so that it occurs in the same space as the frame, reduced spinner size, added spinner to infomercial

:sparkles: adding spinner onload

---

pkg/apis/logicalcluster/v1alpha1/logical-cluster.go
pkg/client/clientset/versioned/cluster/typed/logicalcluster/v1alpha1/fake/logicalcluster.go
pkg/client/clientset/versioned/cluster/typed/logicalcluster/v1alpha1/fake/logicalcluster_client.go
pkg/client/clientset/versioned/cluster/typed/logicalcluster/v1alpha1/logicalcluster.go
pkg/client/clientset/versioned/typed/logicalcluster/v1alpha1/fake/fake_logicalcluster.go
pkg/client/clientset/versioned/typed/logicalcluster/v1alpha1/fake/fake_logicalcluster_client.go
pkg/client/clientset/versioned/typed/logicalcluster/v1alpha1/logicalcluster.go
pkg/client/clientset/versioned/typed/logicalcluster/v1alpha1/logicalcluster_client.go
pkg/client/informers/externalversions/logicalcluster/v1alpha1/interface.go
pkg/client/informers/externalversions/logicalcluster/v1alpha1/logicalcluster.go
pkg/client/listers/logicalcluster/v1alpha1/logicalcluster.go
pkg/client/listers/logicalcluster/v1alpha1/logicalcluster_expansion.go

:sparkles:  change logical cluster to namespaced

---

cluster-provider-client/cluster/logicalcllusterinfo.go
cluster-provider-client/kind/kind.go
cluster-provider-client/provider.go
cmd/logical-cluster-manager/main.go
pkg/apis/logicalcluster/v1alpha1/cluster-provider-desc.go
pkg/apis/logicalcluster/v1alpha1/logical-cluster.go
pkg/logical-cluster-manager/cluster-manager-controller.go

:bug:  fix boilertap

---

pkg/logical-cluster-manager/cluster-manager-controller.go

Add support to namespace at the logical cluster resource.
Fixes #

:bug: logical cluster is now at a namespace resolution

---

docs/content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md

📖 Fix scheduler name in console output

---

docs/content/Community/partners/argocd.md

This PR adds a linkedin [post](https://www.linkedin.com/embed/feed/update/urn:li:ugcPost:7074718212461899776) from 'learnk8s' to our documentation. This post refers our post in one of its weekly event.

🌱 Add reference from 'learnk8s' to 'ArgoCD and KubeStellar in the news'

---

pkg/clustermanager/controller.go
pkg/clustermanager/reconcile_clusterprovider.go
pkg/clustermanager/reconcile_logicalcluster.go

The boilerplate in pkg/clustermanager has a minor booboo.
Fixes #

:bug: fix boilderplate

---

README.md

add Aashni to README contributors

:seedling: Update README.md

---

hack/logcheck.out

:bug: hack/logcheck.out

---

cmd/logical-cluster-manager/main.go
config/crds/logicalcluster.kubestellar.io_logicalclusters.yaml
config/exports/apiexport-logicalcluster.kubestellar.io.yaml
config/exports/apiresourceschema-clusterproviderdescs.logicalcluster.kubestellar.io.yaml
config/exports/apiresourceschema-logicalclusters.logicalcluster.kubestellar.io.yaml
pkg/apis/logicalcluster/v1alpha1/logical-cluster.go

Dummy PR to test our new branch, and verify it passes all PR tests

:sparkles: test the new branch PRs

---

config/crds/logicalcluster.kubestellar.io_clusterproviderdescs.yaml
config/exports/apiexport-logicalcluster.kubestellar.io.yaml
config/exports/apiresourceschema-clusterproviderdescs.logicalcluster.kubestellar.io.yaml
pkg/apis/logicalcluster/v1alpha1/cluster-provider-desc.go

Cluster provider status phase can be Initializing or Ready
Fixes #

:sparkles:Add provider status phase.

---

docs/mkdocs.yml

move getting started tab to second place

:book: move getting started

---

docs/content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-d-create-and-deploy-apache-into-clusters.md

This PR updates the quickstart to track #612 , in which the name of the APIBinding for TMC's k8s basics changed.
Fixes #

🐛 Update quickstart to track ensure-wmw

---

pkg/clustermanager/discovery.go

:bug: fix discovery

---

clusterprovider/kind/kind.go
pkg/clustermanager/discovery.go
pkg/clustermanager/providerclient/client_interface.go
pkg/clustermanager/reconcile_logicalcluster.go

Changing the provider interface. 
Fixes #

:bug:  refactor lc provider

---

scripts/kubectl-kubestellar-prep_for_syncer

:sparkles: update to 0.3.0 for syncer image

---

cmd/logical-cluster-manager/main.go
pkg/clustermanager/controller.go
pkg/clustermanager/reconcile_clusterprovider.go

Add reconciliation logic for provider objects.
Fixes #

:sparkles:Add provider reconcile.

---

pkg/clustermanager/discovery.go

1. On StopDiscovery delete cached provider. StopDiscovery is called when provider object is deleted.
2. If ResultChan read fail, don't try to close the channel. It will panic: close of closed channel
3. LogicalCluster is found when Get does not return error.
Fixes #

:bug:Fix discovery.

---

pkg/clustermanager/discovery.go

:sparkles: reduce complexity

---

docs/content/Getting-Started/user-guide.md

making the glossary/primer headers in the user guide. Now, anyone can add terms or update the primer 
#632

:book: creating the glossary & primer page

---

docs/README.md

:sparkles: repair reference to repo_default_file_path var main

---

docs/README.md
docs/content/Contribution guidelines/operations/release-management.md

:sparkles: repair references to repo_default_file_path r-0.2

---

docs/README.md

:sparkles: repair references to repo_default_file_path r-0.3

---

clusterprovider/kind/kind.go
cmd/logical-cluster-manager/main.go
config/samples/clusterproviderdesc.yaml
config/samples/logicalcluster_dev.yaml
pkg/clustermanager/discovery.go
pkg/clustermanager/reconcile_clusterprovider.go
pkg/clustermanager/reconcile_logicalcluster.go

:bug:Fixes in discovery and reconcilers.

---

pkg/clustermanager/controller.go
pkg/clustermanager/provider.go

:sparkles: add prefix filtering

---

pkg/clustermanager/controller.go
pkg/clustermanager/provider.go
pkg/clustermanager/reconcile_logicalcluster.go

Add finalizers for logical cluster object deletion.
Fixes #

:sparkles: add finalizer

---

pkg/clustermanager/provider.go
pkg/clustermanager/reconcile_logicalcluster.go

:bug: fixes

---

.github/workflows/goreleaser.yml

Add linux/s390
https://github.com/kubestellar/kubestellar/issues/732

:sparkles: Support Syncer image for linux/s390

---

pkg/clustermanager/reconcile_clusterprovider.go

:bug:Log provider namespace.

---

cmd/mc-client-test/demo-magic.sh
cmd/mc-client-test/lcdemo.sh

:bug: fix boilertap

---

cmd/mc-client-test/clientdemo.sh
cmd/mc-client-test/main.go
pkg/mcclient/controller.go

Cluster aware client demo script and main.
Fixes #

:sparkles:Client demo

---

cmd/mc-client-test/clientdemo.sh
cmd/mc-client-test/lcdemo.sh
cmd/mc-client-test/main.go

:bug: fix demo

---

cmd/mc-client-test/lcdemo.sh

:bug: demo

---

.github/workflows/docs-ecutable-placement.yml
docs/content/Coding Milestones/PoC2023q1/where-resolver.md

This PR nearly finishes the renaming of the "scheduler" to the "where resolver", updating some GitHub Actions (workflow) related things.
If I understand correctly, the remaining task is #753, which I suspect we have to hold off for a while.
Fixes #

✨ GitHub Actions related cleanup after scheduler renaming

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md

moved kubestellar clone reference to get Kubestellar section
#692

:book: moving get kubestellar release-0.2

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md

Moved kubestellar clone reference to Get Kubestellar section, release 0.3
#692

:book: move kubestellar clone, release 0.3

---

docs/content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md
docs/content/Getting-Started/quickstart.md
docs/content/common-subs/required-packages.md

Updated Fedora family linux commands in docs/content/common-subs/required_packages.md include file
Also added a first "general" tab in that include file listing the packages without specific environments
Updated docs/content/Getting-Started/quickstart.md to include required packages in install flow
Moved anchor/heading # 1 out of included file and into docs/content/Getting-Started/quickstart.md
700, 602
Fixes #

:bug: :book: Update prereqs Fedora commands and quickstart.md

---

cmd/mc-client-test/clientdemo.sh
cmd/mc-client-test/lcdemo.sh
cmd/mc-client-test/main.go

Logical clusters

---

docs/mkdocs.yml

fixed spelling of "invitation" in Coding Milestones side menu

:book: "invitation" spelling in coding milestones

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md

:book: "built" misspelling

---

docs/content/common-subs/pre-req.md

:sparkles: add logic to check for go version 1.19

---

pkg/placement/workload-projector.go

This PR does some cleanup in the workload projector source.
Fixes #

✨ Fix up some naming and comments in workload projector

---

docs/content/readme.md

adding aashni and kevin to readme

📖  add aashni + kevin to contributers

---

.goreleaser.yaml

Fixes https://github.com/kubestellar/kubestellar/issues/794

:bug: add verion prefix v to syncer image

---

docs/content/Coding Milestones/PoC2023q1/where-resolver.md

This PR addresses [this comment](https://github.com/kubestellar/kubestellar/issues/711#issuecomment-1613943430) regarding the anthn & anthz of the where-resolver.
/cc @MikeSpreitzer 
#711

📖 Document the authn/z of the where-resolver

---

.github/spellcheck/.wordlist.txt
docs/content/Coding Milestones/PoC2023q1/commands.md
docs/content/Coding Milestones/PoC2023q1/environments/cloud-env.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1b.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-0-deploy-florin.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-0-deploy-guilder.md
docs/content/Coding Milestones/PoC2023q1/outline.md
docs/content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-c-onboarding-clusters.md

replace references of pcluster with workload execution cluster, added words to spellcheck dictionary
#810

🐛 add to dictionary and replace pcluster

---

cmd/logical-cluster-manager/main.go
pkg/clustermanager/controller.go
pkg/clustermanager/provider.go
pkg/clustermanager/reconcile_clusterprovider.go
pkg/clustermanager/reconcile_logicalcluster.go

Handle some of the comments from PR #783 post merge.
Fixes #

:bug: Handle some of the comments from phase1 of logical cluster into main

---

docs/content/Getting-Started/user-guide.md

Add a quick glossary to the user guide. Some definitions are missing, and some need more elaboration (because I think others can provide a much better definition than I can).
#632

📖 : make base glossary

---

README.md
docs/content/Coding Milestones/PoC2023q4/outline.md
docs/content/readme.md
docs/mkdocs.yml

This PR updates the documentation, renaming q3 to q4 in the file names and content.
Fixes #

📖 Rename q3 to q4 in file names and content

---

docker/Dockerfile
docker/Makefile
docker/README.md
docker/entry.sh

Provide:
- `Dockerfile` to create a **KubeStellar** container image
- `Makefile` to automate the processes of creating the image, running the container, cleaning up
- `README.md` detailing the steps and options
I'm currently hosting the following images... that will hopefully move to the KubeStellar registry:
- quay.io/stellari/kubestellar:v0.3.0
- quay.io/stellari/kubestellar:v0.3.1 (==latest)
https://kubernetes.slack.com/archives/C058SUSL5AA/p1688543882794829
https://kubernetes.slack.com/archives/C058SUSL5AA/p1688657230224689
Fixes #

✨ Docker container for KubeStellar

---

docs/content/Getting-Started/user-guide.md

This PR updates the glossary.  This PR adopts the new terminology, and describes the terminology shift in a backward-looking way rather than a forward-looking way.  This PR also adds "space", "downsynced object", and "upsynced object", fills in some blanks, and hopefully improves some of the definitions.
Fixes #

📖 Update glossary

---

docs/content/Coding Milestones/PoC2023q1/commands.md

This PR updates the documentation of the `kubectl kubestellar ensure location` command to track the changes made in #814.
Fixes #
/cc @fileppb

✨ Update doc of kubectl kubestellar ensure location

---

scripts/kubectl-kubestellar-ensure-location
scripts/kubectl-kubestellar-prep_for_syncer
scripts/kubectl-kubestellar-remove-location

This PR is a follow-on to #814, adding the overlooked uses of `kubectl_flags` in kubectl plugins.
Fixes #

🐛 Add missing uses of kubectl_flags

---

cmd/emc-customize/main.go
cmd/mailbox-controller/main.go
cmd/mailbox-controller/options/options.go
hack/logcheck.out
pkg/customize/customize.go
pkg/placement/workload-projector.go
scripts/kubectl-kubestellar-ensure-location
scripts/kubectl-kubestellar-remove-location

cleanup diagnostics and comments and a couple of commands such as binds that were considered by the reviewer to be undesireable although they did no harm.
Resolves #848
Fixes #

✨ feature finish adoption of definition of SyncTarget and Location

---

docs/content/common-subs/required-packages.md

:book: Update quickstart's Ubuntu required-packages.md

---

cmd/syncer/options/options.go
hack/logcheck.out
pkg/apis/edge/v1alpha1/customize.go
pkg/placement/main.go
test/e2e/framework/kubestellar_syncer.go

Remove some additional kcp references, as per Mike's comment:
https://github.com/kubestellar/kubestellar/issues/848#issuecomment-1666147382
#848
Fixes #848

 ✨ feature  - Remove some additional kcp references

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1b.md

🐛 Update example1-stage-1b.md to remove root:espw:edge.kcp.io

---

config/crds/space.kubestellar.io_spaces.yaml
config/exports/apiexport-space.kubestellar.io.yaml
config/exports/apiresourceschema-spaces.space.kubestellar.io.yaml
pkg/apis/space/v1alpha1/space.go

This will allow to use empty status when Space object is created programmatically.
Fixes #

:bug:Allow empty Space status phase

---

pkg/mcclient/mcclient.go

If client controller didn't get an event or didn't add Space to cache for any reason, try to get the space object from API server.
Fixes #

:bug:Get space from server if not in cache

---

bootstrap/bootstrap-kubestellar.sh
docs/content/Coding Milestones/PoC2023q1/commands.md
docs/content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md
docs/content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-b-create-imw-and-wmw.md
docs/content/common-subs/teardown-the-environment.md

This PR updates the bootstrap script so that it has the option to deploy to a Kubernetes cluster rather than as bare processes, and updates the quickstart so that it describes how to use both techniques.
Fixes #
/cc @ronenkat 
/cc @dumb0002 

✨ Make bootstrap able to deploy to kubernetes cluster

---

bootstrap/bootstrap-kubestellar.sh

This PR updates the bootstrap script to give more information when it disapproves of the found kcp version.
Fixes #

✨ Add more info to kcp version mismatch error message

---

docs/content/Contribution guidelines/CONTRIBUTING.md
docs/content/common-subs/required-packages.md

This PR factors the pre-reqs in the quickstart into three groups:
(1) Those needed for KubeStellar, period.
(2) The additional things needed to run the example in the quickstart.
(3) The additional things needed by contributors (which this PR moves to the CONTRIBUTING document).
Fixes #
/cc @dumb0002 
/cc @ronenkat 

📖 Factor pre-reqs in quickstart

---

scripts/kubestellar

✨ update logging to append instead of replace

---

space-provider/kcp/kcp.go

:bug:Check cluster has owner in KCP provider

---

pkg/syncer/syncers/common.go

Same PR as https://github.com/kubestellar/kubestellar/pull/940 against for release-0.4 branch 
Fixes #938

🐛(release-0.4) Fix Syncer not to update status field

---

pkg/syncer/syncers/downsyncer.go

This PR updates the syncer to make it choose how to update the status of an upstream object based on the API group.  This is better than the previous code but not fully correct; the correct code would somehow depend on whether the resource actually has a status subresource.
Partially addresses #945

🐛 release-0.4: Choose update status method according to API group

---

Makefile

This PR updates the Makefile targets for building the syncer image to add image labels recording the git commit used in the build.
Fixes #

✨ Make syncer image build record git commit

---

cmd/placement-translator/main.go
docs/content/Coding Milestones/PoC2023q1/placement-translator.md

This PR removes unneeded stuff from the placement translator.
Fixes #930

✨ Remove junk from placement-translator

---

docs/content/Coding Milestones/PoC2023q1/commands.md
scripts/kubectl-kubestellar-ensure-location
scripts/kubectl-kubestellar-ensure-wmw
scripts/kubectl-kubestellar-prep_for_cluster
scripts/kubectl-kubestellar-prep_for_syncer
scripts/kubectl-kubestellar-remove-location
scripts/kubectl-kubestellar-remove-wmw

This PR adds the `-X` option for debuggability to some scripts that were missing it.
This PR also adds documentation of the `-s` option that was snuck into some scripts recently.
Fixes #956

✨ Add -X to some scripts

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md

This PR improves the material in example1 about getting kcp.
This addresses the first two points in #974.
This PR does not address the need to recognize that not all users are deployers.

📖 Improve pointers to getting kcp in example1

---

pkg/placement/doc.go
pkg/placement/set-types.go

This PR adds some comments in pkg/placement, mainly adding an outline the newly created doc.go file.
Fixes #

📖 Add some internal documentation pkg/placement/doc.go

---

docs/content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md
docs/content/Getting-Started/quickstart.md

Mention its installation more clearly.  Document the required version.
This PR documents the required version of kcp and includes mention of kcp in section headings about install.  This is good because @eaepstein has demonstrated that users are lost without it.
Fixes #

📖 Make quickstart clearer about kcp

---

pkg/mailboxwatch/impl_test.go

This PR makes a fix to the unit test of the mailboxwatch patckage.  The fix updates the checking of the Workspace informer behavior to cope with the fact that the fake clientset constructed by NewSimpleClientset has a dumb implementation of WATCH: it does not deliver the pre-existing objects.
This test still fails.  A full fix would require making a fake clientset whose LIST and WATCH behavior have full fidelity to ResourceVersion semantics.  The use of those semantics is an important part of what we want to test.
Fixes #

🐛 Cope with simplicity of SimpleClientset

---

config/samples/edgeplacement_all2all.yaml
config/samples/edgeplacement_dev.yaml

This PR finishes updating examples to match the EdgePlacement interface change in #884.
Fixes #

✨ Update where-resolver doc for EdgePlacement schema change

---

pkg/placement/apiwatch-map-provider.go
pkg/placement/binding-organizer.go
pkg/placement/declarations.go
pkg/placement/doc.go
pkg/placement/external-name.go
pkg/placement/hash-domain.go
pkg/placement/map-factored.go
pkg/placement/rotations_test.go
pkg/placement/set-binder-assembly.go
pkg/placement/set-binder-test.go
pkg/placement/slices.go
pkg/placement/what-resolver.go
pkg/placement/what-resolver_test.go
pkg/placement/where-resolver.go
pkg/placement/where-resolver_test.go
pkg/placement/workload-projector.go

This PR does some regularization and other cleanup following the recent regularization of the downsync API.
Fixes #

🌱 Begin cleanup after EdgePlacement downsync unification

---

pkg/apis/edge/v1alpha1/report-single.go

This PR proposes an API by which (1) users explicitly request return of reported state when the number of executing copies is 1 (i.e., #772) and (2) the implementation reports the number of executing copies.
This PR is for review of the proposed API.  It would be confusing to merge the API extension without the accompanying implementation.
Fixes #

✨ Draft API for requesting return of singleton reported state

---

docs/content/Coding Milestones/PoC2023q1/commands.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md

This PR fixes a few small documentation issues.  It fixes one issue, #1027.  This PR fixes an inaccuracy that I noticed and adds answers and emphasis to respond to some of @eaepstein's comments.
Fixes #1027

📖 Brush up docs a little

---

docs/content/common-subs/required-packages.md

Instructions for installing Helm are added to the required packages documentation.
This addresses [#1017](https://github.com/kubestellar/kubestellar/issues/1017)

:book: Add Helm to required packages

---

docs/content/Coding Milestones/PoC2023q1/commands.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md

This PR makes a few doc updates and expansions to the `release-0.7` branch.  This is like #1029 but for this release branch.
Fixes #

📖 A few doc updates & expansions

---

docs/content/Coding Milestones/PoC2023q1/commands.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md

This PR updates the extended example and documentation to say more about the hosting cluster.
Fixes #

📖 Add remarks about hosting cluster and Ingress

---

core-helm-chart/README.md

Update Helm chart README.md to point to the correct instructions for creating the Kind cluster
Fixes #

🐛 Update Helm chart README.md to point to the correct instructions

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md

This PR replaces the fixed time waiting periods after starting KCP, `mailbox-controller`, `where-resolver`, and `placement-translator`. This reduces waiting time on fast machines, and prevents errors on slow machines.
Fixes #

:book: Add dynamic waiting to example1

---

space-framework/.gitignore
space-framework/Makefile
space-framework/core.Dockerfile
space-framework/entry.sh

We don't want to use .git in the docker image build instead we export the needed variables when we call make and then 
when building in the image we use the imported file
Fixes #

:sparkles: Build the space-framework image

---

config/crds/edge.kubestellar.io_edgeplacements.yaml
config/exports/apiexport-edge.kubestellar.io.yaml
config/exports/apiresourceschema-edgeplacements.edge.kubestellar.io.yaml
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md
outer-scripts/kubectl-kubestellar-deploy
pkg/apis/edge/v2alpha1/edge-placement.go
pkg/apis/edge/v2alpha1/zz_generated.deepcopy.go
pkg/placement/what-resolver.go

This PR expands the "what predicate" to allow testing a namespace's name rather than its labels.
Fixes #1084

✨ Expand API to allow namespace selection by name

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md

This PR makes many long overdue updates to the text in example1, to track code developments and bash command changes made over the last several months.
Fixes #1061
Fixes #1127 
This PR includes replacing the use of "si" with "yes", because many readers did not recognize the intended meaning of that "si" (this was a contributing factor to #1065).

🐛 Fix outdated text in example1

---

outer-scripts/kubectl-kubestellar-deploy

This PR updates the image reference in `kubectl-kubestellar-deploy` to a build of `main` as it is right now.  There have been some changes since the last tag update.
Fixes #

🌱 Update core image ref to build of main

---

bootstrap/bootstrap-kubestellar.sh

This PR revises #1144 to create the chosen namespace if it does not already exist.
Fixes #1141

✨ Generalize bootstrap wrt namespace in hosting cluster

---

docs/content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md

This PR fixes the display of the initial load of spaces.  This is the release-0.8 version of #1143 
Fixes #

🐛 Show all spaces

---

core-helm-chart/Chart.yaml

Update Chart.yaml appVersion
Fixes #

📖Update Chart.yaml appVersion

---

cmd/cluster-watchall/main.go
pkg/apiwatch/resources.go
pkg/placement/apiwatch-map-provider.go
pkg/placement/what-resolver.go

This PR is a bit of code cleanup, replacing the "ur" chosen in a moment of desperate lack of imagination with "ks" for "KubeStellar".
Fixes #

🌱 Rename urmeta to ksmeta

---

README.md

Added @namasl and @fab7 to contributors of README.
Fixes #

:book: Added contributors to README

---

README.md
docs/content/readme.md

Make sure all contributors are updated in both `README.md` and `docs/content/readme.md`
Fixes #

:book: More contributor updates

---

Formula/README.md
Formula/kcp_cli.rb
Formula/kubestellar_cli.rb

✨ Brew installer for kubestellar user commands and kubectl plugins

---

cmd/inform-syncer-configs/README.md
cmd/inform-syncer-configs/main.go

This PR updates the inform-syncer-configs demo/utility to track the removal of hierarchy in workspace usage (#1015). This demo/utility was usable, you just had to mentally adjust the instructions and naming.
Fixes #

🌱 Update inform-syncer-configs due to workspace flattening

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md

This PR extends example1 with a CustomResoureDefinition object and an object whose kind is defined by that CRD.
Fixes #

✨ Add a CustomResourceDefinition to example1

---

docs/content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-c-onboarding-clusters.md
docs/content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-d-create-and-deploy-apache-into-clusters.md

This PR updates the existing quickstart to use simpler selection criteria available now. This PR also replaces some Spanish with English and adds a note about the upsync section of the exhibited EdgePlacement object.
Fixes #

📖 Simplify some selection criteria in quickstart

---

docs/content/Getting-Started/user-quickstart-kind.md
docs/content/Getting-Started/user-quickstart-openshift.md
docs/content/common-subs/kubestellar-apply-apache-openshift.md
docs/content/common-subs/kubestellar-test-apache-kind.md
docs/content/common-subs/kubestellar-test-apache-openshift.md

✨ openshift user-quickstart is missing service, route, and a correct curl to reach the route needed to test the example

---

core-helm-chart/README.md

The command loops forever for me, without specifying the `kubestellar` namespace.

🐛 Update the ready check for core helm chart

---

space-framework/pkg/space-manager/provider.go
space-framework/space-provider/kind/kind.go
space-framework/space-provider/kubeflex/kubeflex.go

:bug:  return error when fail to create a provider

---

Makefile

🌱 remove vendor from Makefile (not used anywhere)

---

space-framework/go.mod
space-framework/go.sum
space-framework/space-provider/kubeflex/kubeflex.go

:sparkles:  remove the dependency on kubeflex import

---

core-container/entry.sh

Fix a regression in checking kcp readiness
Fixes #

🐛 Fix regression in checking kcp readiness

---

.github/workflows/docs-ecutable-user-quickstart-test.yml

This PR changes the docs-ecutable workflow for the user-quickstart-test to be a regular part of testing a PR.
Fixes #

✨ Run user-quickstart-test as regular CI

---

docs/mkdocs.yml

This PR adds the letter "g" where it is missing.
Fixes #

📖 Fix typo in doc menu

---

docs/content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-c-onboarding-clusters.md

📖 fix typos in docs

---

space-framework/pkg/msclientlib/client.go

This PR fixes a bug of missing clientset for secret objects in cluster aware client.
Fixes #

:bug: Fix cluster aware client crash

---

space-framework/pkg/space-manager/provider.go
space-framework/pkg/space-manager/reconcile_spaceprovider.go

:bug: Fix some SM bugs

---

docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer.md
docs/content/Contribution guidelines/operations/release-management.md

This PR updates the documentation on building the syncer image, to clearly state the issues around identifying the git commit involved.
Fixes #

📖 Update doc on building the syncer image

---

docs/content/Coding Milestones/PoC2023q1/outline.md

This PR describes the kcp variant that @pdettori built and why.
Fixes #

📖 Document the kcp hack that Paolo did

---

config/kube/exports/cluster-scoped/apiexport-core.k8s.io.yaml
config/kube/exports/cluster-scoped/apiexport-networking.k8s.io.yaml
config/kube/exports/cluster-scoped/apiexport-storage.k8s.io.yaml
overlap-scripts/kubectl-kubestellar-ensure-wmw

This PR renames some APIExport objects, to avoid name collisions.
Fixes #1261

🐛 Rename APIExports to avoid collisions

---

docs/content/Coding Milestones/PoC2023q1/outline.md

This PR updates the list of patched kcp release archives in the design outline.
Fixes #

📖 Noted two more patched kcp archives

---

space-framework/space-provider/kubeflex/kubeflex.go

:bug: Avoid panic due to closing a closed channel

---

cmd/mailbox-controller/controller.go
overlap-scripts/kubectl-kubestellar-ensure-mbw

This PR finishes item 3 in Section "Use kube-bind" of #1208.
/cc @ezrasilvera
/cc @andreyod

✨ Invocation of kube-bind script from the mailbox-controller

---

pkg/cliplugins/kubestellar/syncer-gen/edgesync.go

This PR is an alternative to #1275 and makes syncer-gen follow the pattern shown in https://eng.d2iq.com/blog/service-account-tokens-in-kubernetes-v1.24/#how-does-this-affect-you if a token Secret for the syncer's ServiceAccount does not show up within a limited amount of time. This also adds a second wait for a token to appear in the Secret. This behavior should work for kcp v0.11.0, Kubernetes 1.23 and later, and OpenShift (which is unlikely to be relevant as a space provider).
This is part of the campaign in #1274 
Fixes #

🌱 Syncer gen patience2

---

README.md
pkg/placement/apiwatch-map-provider.go
pkg/placement/declarations.go
pkg/placement/hash-domain.go

📖 added common badges used in most familiar go projects to README.

---

space-framework/pkg/space-manager/provider.go
space-framework/space-provider/kubeflex/kubeflex.go

:bug: error in secrets

---

docs/content/Coding Milestones/PoC2023q1/outline.md

This PR ammends the doc on the IDs in SinglePlacement, according to latest agreement.
Fixes #

📖 Update doc on IDs in SinglePlacement

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1b.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-0-deploy-florin.md
docs/content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-c-onboarding-clusters.md
docs/content/common-subs/teardown-the-environment.md

minor doc change  to match changes done in commit #1169
Fixes #

📖 minor update in docs

---

README.md

Added @nirrozenbaum and @vMaroon to contributors.
Fixes #

🌱 added contributors to README

---

pkg/syncer/README.md

📖 change p-cluster to workload execution cluster in syncer readme

---

cmd/mailbox-controller/controller.go

:sparkles: Use original SyncTarget name in mailbox space annotation

---

cmd/mailbox-controller/controller.go
scripts/inner/kubestellar
scripts/inner/kubestellar-kube-bind
scripts/overlap/kubectl-kubestellar-ensure-wmw

This PR makes the first batch of improvements in response to comments to PR #1265.

🌱 First batch of improvements to `kube-bind`

---

cmd/mailbox-controller/controller.go
cmd/placement-translator/main.go
pkg/placement/what-resolver.go

:sparkles: Fixes upon review comments

---

core.Dockerfile
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1b.md
scripts/inner/kubestellar
scripts/outer/kubectl-kubestellar-prep_for_cluster
scripts/outer/kubectl-kubestellar-prep_for_syncer

🌱 Changes in response to review comments

---

hack/verify-go-versions.sh

this change is checking go version is at least 1.19 instead of strictly eqaulity.
Fixes #

✨ updated verify go version script

---

scripts/outer/kubectl-kubestellar-prep_for_syncer

🌱 Minor fixes in response to review comments to 1265

---

core.Dockerfile
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
scripts/inner/kubestellar
scripts/inner/kubestellar-kube-bind

✨ More changes in response to review comments to 1265

---

docs/content/Contribution guidelines/operations/code-management.md

be more explicit about the branching and squashing instructions, add the info re the Compare and pull request github page
Add instructions to the Code Management section of the Contributing Guidelines - Operations documentation
#1187
Fixes #

✨ Code Management Documentation

---

cmd/mailbox-controller/controller.go
scripts/inner/kubestellar
scripts/inner/kubestellar-kube-bind
scripts/overlap/kubectl-kubestellar-ensure-wmw

 ✨ Make kubestellar-kube-bind idempotent

---

.gitignore
hack/count-commit.sh
hack/count-directory.sh
hack/count-tree.sh
hack/make-count-summary-table.sh
hack/make-count-summary-tables.sh

This PR introduces a utility that counts uses of "kcp", broken down by directory and file type. It is intended to compile a record over time that can be examine for evolution.
Fixes #

✨ Introduce word counting utility

---

cmd/mailbox-controller/controller.go
scripts/inner/kubestellar
scripts/inner/kubestellar-kube-bind
scripts/overlap/kubectl-kubestellar-ensure-wmw

:bug:  use spaces with kube-bind

---

space-framework/docs/using-sf-for-ks.md

📖 fixed typos in SF docs

---

scripts/inner/kubestellar-kube-bind

:sparkles:  fix mb

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md
docs/content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md
docs/content/Getting-Started/user-quickstart-test.md

The quickstart.test was somehow missing a SM_CONTEXT define.
Fixes #

✨ fix a quickstart.test failure

---

scripts/inner/kubestellar-kube-bind

Minor fix of the in-cluster param in the kube bind script.
Fixes #

✨ fix in_cluster param in kube-bind script

---

cmd/kubestellar-where-resolver/cmd/where-resolver-cmd.go

:bug: Fix log featureGate

---

scripts/outer/kubectl-kubestellar-prep_for_syncer

:bug: fix syncer space id

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md

:bug:  fix typo

---

config/kube/crds/cluster-scoped/apiregistration.k8s.io_apiservices.yaml
config/kube/crds/cluster-scoped/flowcontrol.apiserver.k8s.io_flowschemas.yaml
config/kube/crds/cluster-scoped/flowcontrol.apiserver.k8s.io_prioritylevelconfigurations.yaml
config/kube/crds/cluster-scoped/networking.k8s.io_ingressclasses.yaml
config/kube/crds/cluster-scoped/node.k8s.io_runtimeclasses.yaml
config/kube/crds/cluster-scoped/scheduling.k8s.io_priorityclasses.yaml
config/kube/crds/cluster-scoped/storage.k8s.io_csidrivers.yaml
config/kube/crds/cluster-scoped/storage.k8s.io_csinodes.yaml
config/kube/crds/cluster-scoped/storage.k8s.io_storageclasses.yaml
config/kube/crds/cluster-scoped/storage.k8s.io_volumeattachments.yaml
config/kube/crds/namespaced/apps_deployments.yaml
config/kube/crds/namespaced/core.k8s.io_pods.yaml
config/kube/crds/namespaced/core.k8s.io_services.yaml
config/kube/crds/namespaced/discovery.k8s.io_endpointslices.yaml
config/kube/crds/namespaced/networking.k8s.io_ingresses.yaml
config/kube/crds/namespaced/networking.k8s.io_networkpolicies.yaml
config/kube/crds/namespaced/storage.k8s.io_csistoragecapacities.yaml
docs/content/Coding Milestones/PoC2023q1/commands.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md
scripts/overlap/kubectl-kubestellar-ensure-wmw

✨ Use crds when ensuring wmw

---

scripts/outer/kubectl-kubestellar-prep_for_syncer
scripts/overlap/kubectl-kubestellar-get-config-for-space

:bug:  Fix syncer

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md

:bug: Fix typo in md file

---

cmd/placement-translator/main.go
pkg/mailboxwatch/impl.go
pkg/mailboxwatch/impl_test.go
pkg/placement/apiwatch-map-provider.go
pkg/placement/binding-organizer.go
pkg/placement/declarations.go
pkg/placement/external-name.go
pkg/placement/hash-domain.go
pkg/placement/main.go
pkg/placement/rotations_test.go
pkg/placement/set-binder-assembly.go
pkg/placement/set-binder-test.go
pkg/placement/test-apimap-provider.go
pkg/placement/what-resolver.go
pkg/placement/what-resolver_test.go
pkg/placement/where-resolver.go
pkg/placement/where-resolver_test.go
pkg/placement/workload-projector.go

:sparkles: Use space framework in placement-translator

---

pkg/placement/apiwatch-map-provider.go
pkg/placement/what-resolver.go

:sparkles: Start informer factories

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md
docs/content/Coding Milestones/PoC2023q1/example1.md

:bug: Fix sc1

---

scripts/inner/kubestellar

✨ Use exact match when looking for dex process

---

pkg/where-resolver/reconcile_on_edgeplacement.go
pkg/where-resolver/reconcile_on_location.go
scripts/outer/kubectl-kubestellar-prep_for_syncer

✨ Improvments in response to comments to 1363

---

core-container/entry.sh
scripts/inner/kubestellar

remove the --allcluster-context from placement-translator.
Fixes #

✨ remove the --allcluster-context from placement-translator

---

docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-0-deploy-florin.md
docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-0-deploy-guilder.md

:bug:  fix the syncer test

---

cmd/kubestellar-where-resolver/cmd/where-resolver-cmd.go
cmd/kubestellar-where-resolver/options/options.go
cmd/mailbox-controller/controller.go
cmd/mailbox-controller/main.go
cmd/placement-translator/main.go

:sparkles: Name changes

---

cmd/mailbox-controller/controller.go
cmd/mailbox-controller/main.go

:sparkles: Minor changes upon review comments

---

core-container/entry.sh
docs/content/common-subs/kubestellar-apply-apache-kind.md
scripts/outer/kubectl-kubestellar-prep_for_syncer

✨ Set the SM_CONTEXT for all controllers when running from an image

---

docs/content/Coding Milestones/PoC2023q1/commands.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-provider.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md
docs/content/Getting-Started/user-quickstart-test.md
scripts/inner/kubestellar
scripts/inner/kubestellar-kube-bind
scripts/outer/kubectl-kubestellar-ensure-location
scripts/outer/kubectl-kubestellar-prep_for_syncer
scripts/overlap/kubectl-kubestellar-create-space
scripts/overlap/kubectl-kubestellar-ensure-wmw
scripts/overlap/kubectl-kubestellar-get-config-for-space

Post the recent rebase of the space-mgt branch I am resubmitted a few PRs that were lost during the rebase.
Fixes #

✨ update commands.md and use default provider name

---

pkg/apiwatch/definition-tracking.go
pkg/apiwatch/resources.go

This PR is one more turn on the crank of adapting to JSON-based loggers.
Fixes #

✨ Add more adaptation for JSON logging

---

hack/count-commit.sh

This PR trims one more bit of junk before counting.
Fixes #

🐛 Do not count docs/scripts/generated_script.sh

---

core-container/entry.sh
space-framework/entry.sh

This PR replaces scripting that ensures the existence and content of a Secret object by deleting it and then creating it with using `kubectl apply`. This is good because concurrent processes can exist and get trouble from the deletion.
Fixes #1429

🐛 Replace secret delete;create with apply

---

cmd/mailbox-controller/controller.go

This PR undoes a bad suggestion from me, to restore the property that only one goroutine works on a given object at a time.
Fixes #

🐛 Remove concurrency bug in mailbox controller

---

docs/content/Coding Milestones/PoC2023q1/commands.md

This PR updates `commands.md` to track recent changes. There are several updates.
- more accurately reflect how commands are sensitive to non-standard environment variables and kube config more broadly;
- indicate which commands are not converted to using the space framework yet;
- change some "workspace" terminology to "space" terminology (this PR only does a little of what is needed about that).
Fixes #

📖 Update commands.md

---

scripts/inner/kubestellar-kube-bind

:bug:  Use the IN_CLUSTER env variable instead of hardcoded --in-cluster

---

pkg/apis/edge/v2alpha1/edge-placementdecision.go
pkg/transport/generic_transport_controller.go

🌱 minor changes in transport controller

---

scripts/inner/kubestellar-kube-bind

This PR tries to make the parsing of kubectl-bind's result a little safer.

✨ Defensive parsing of kubectl-bind result

---

docs/content/Getting-Started/user-quickstart-kind.md
docs/content/Getting-Started/user-quickstart-openshift.md
docs/content/Getting-Started/user-quickstart-test.md
docs/content/common-subs/kubestellar-prep-syncer.md
docs/content/common-subs/kubestellar-show-available-spaces.md

The kind and openshift ones still need more work.
This PR removes some outdated material from user-quickstart-test (addressing https://github.com/kubestellar/kubestellar/pull/1444#pullrequestreview-1779303828) and makes some progress on updating the other two user quickstarts (which still need more work).
Fixes #

🌱 Some more updates to the user quickstarts

---

space-framework/test/example/clone_and_build_space_manager.sh
space-framework/test/example/create_kind_cluster.sh
space-framework/test/example/example.md
space-framework/test/example/get_kubeconfig_for_space
space-framework/test/example/install_and_run_kcp.sh
space-framework/test/example/install_and_run_kubeflex.sh
space-framework/test/example/kcp-provider.yaml
space-framework/test/example/kcp-space.yaml
space-framework/test/example/kf-provider.yaml
space-framework/test/example/kf-space.yaml
space-framework/test/example/kind-provider.yaml
space-framework/test/example/kind-space.yaml
space-framework/test/example/run_space_manager.sh

Create a usage example of the space framework.
Fixes #

✨ create a space manager example

---

space-framework/test/example/clone_and_build_space_manager.sh
space-framework/test/example/example.md

:seedling: improve SM examples

---

space-framework/test/example/create_kind_cluster.sh
space-framework/test/example/example.md

:bug: Fix space framework example

---

space-framework/pkg/space-manager/provider.go
space-framework/pkg/space-manager/reconcile_space.go

:bug: Fix space finalizer deletion

---

space-framework/test/example/example.md

:sparkles: Add teardown section in SM example

---

space-framework/test/example/example.md

✨ sm example

---

docs/content/common-subs/delete-contexts-for-kind-and-openshift-clusters.md

Quick start guide says "and" where it should say "any".
Fixes #1455

:book: fix: trivial typo

---

CONTRIBUTING.md

Original article has been taken down, point to a reproduction.
Fixes #1460

:book: fix: broken link

---

space-framework/test/example/clone_and_build_space_manager.sh

Commands following this script in the quick start guide require you to be in the kubestellar directory
Fixes #

🐛 Update clone_and_build_space_manager.sh

---

docs/content/common-subs/remove-all.md

1. Kill the space-manager and example-backend processes.
2. Delete the sm-mgt Kind cluster.
3. Remove files and directories created by docs-executable in Kubestellar root directory.
Fixes #

:bug: Update remove-all.md

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-pre-provider.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1b.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md

Update some of the outputs and logs in example1 subs.
Fixes #

:sparkles: Cosmetic changes in the example1 subs

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-provider-kcp.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-provider-kubeflex.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md
scripts/inner/kubestellar

Fix the hard coded ensure-wmw --kube-needed parameter.
Fixes #

✨ update with-kube

---

hack/update-codegen-crds.sh

:sparkles: Remove unused code from update-codegen-crds.sh

---

go.mod
go.sum
pkg/transport/generic_transport_controller.go
pkg/transport/transport.go

added code to transport controller
Fixes #

✨ updated transport controller code

---

pkg/transport/generic_transport_controller.go
pkg/transport/transport.go

removed the requirement to get wrapped object GVR from transport interface
Fixes #

🌱 calculate wrapped object GVR from the wrapped object.

---

pkg/transport/generic_transport_controller.go
pkg/transport/transport.go

🌱 Transport wrappedobj informer

---

cmd/transport/base-controller.go
cmd/transport/options/options.go
pkg/transport/generic_transport_controller.go

🌱 Transport cmd

---

docs/content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md

Update quickstart text from kcp to space framework.
Fixes #

✨ update quickstart text

---

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-provider.md
docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md

Small update in the example1 text.
Fixes #

:book: Text changes in the example1 subs

---

README.md

Add [grahamwhiteuk](https://github.com/grahamwhiteuk) to contributors in README as suggested by @clubanderson (note: I've not opened a related issue in the tracker for this PR)
It also looks like my vscode settings of removing whitespace at the end of lines has adjusted a few additional things here but I think that's OK.
Note also: I've linked to my list of PRs in the README which is hinted at by the `title` element within the anchor reference that says "Contributed PRs".  This is different to all the other contributors in the README that have their assigned issues linked.  I have no assigned issues since I'm not currently a member of the project.  I wonder if the README would be better updated such that everyone else is shown with their contributions rather than their assigned issues???

✨  add contributor to README

---

README.md

Small updates to README.md.
Fixes #

✨ Update README.md

---

docs/content/Getting-Started/user-quickstart-kind.md
docs/content/common-subs/brew-install.md
docs/content/common-subs/brew-remove.md
docs/content/common-subs/kubestellar-prep-syncer.md

update the quickstart-kind to support spaces.
Fixes #

✨ update user-quickstart-kind

---

Makefile
hack/logcheck.out
hack/verify-contextual-logging.sh
scripts/add-helm-code.sh

fix makefile for missing lint command

🐛 fix makefile for missing lint command

---

.gitignore
Makefile
config/manager/kustomization.yaml
core-helm-chart/templates/operator.yaml

add commands to build and publish image and chart to makefile
Fixes #1555

✨ add commands to build and publish image and chart to makefile

---

scripts/add-helm-code.sh

This PR updates the commentary at the start of scripts/add-helm-code.sh to clarify what it does.
Fixes #

🌱 Clarify helm tweak

---

docs/content/v0.20/README.md

This PR updates the Placement objects exhibited in the doc to track #1525 .
Remember that users do not see the new schema until other things have changed (image, Helm chart, KubeFlex hook).
This PR also fixes the test for Helm labels.
Fixes #

🐛 Update examples to track Placement schema change

---

.github/workflows/pr-test.yml

 :sparkles: pr flow

---

.github/workflows/pr-test.yml

:sparkles:  initial flow

---

test/integration/multi-cluster-deployment/cleanup.sh
test/integration/multi-cluster-deployment/run-test.sh
test/integration/multi-cluster-deployment/setup-kubestellar.sh
test/integration/multi-cluster-deployment/workload-deployment.sh
test/pre-reqs.md

This is an end to end integration test for ks-0.20.
It takes advantage of the new make ko-build and make install-local-chart that Paolo PRed on Sunday. 
Fixes #

✨ end to end test for ks-0.20

---

test/integration/multi-cluster-deployment/README.md
test/integration/multi-cluster-deployment/setup-kubestellar.sh
test/pre-reqs.md

Update pre-req and create a README for the integration test.
Fixes #

✨ update pre-req and create README for PR test

---

test/integration/multi-cluster-deployment/setup-kubestellar.sh

Pipe flex output to /dev/null so we don't overwhelm the CICD test output with meaningless messages.
Fixes #

✨ pipe kflex output to /dev/null

---

test/integration/multi-cluster-deployment/README.md

fix a couple of issues with README.md of pr test.
Fixes #

✨ fix a couple of issues in the README.md for pr test

---

pkg/ocm/ocm.go
pkg/placement/controller.go
pkg/placement/manifest.go
scripts/add-helm-code.sh

🐛 Some fixes to function names and typos

---

docs/README.md

This PR adds more explanatory material to docs/README.md. It also adds subsection headers for the different cases of codeblocks, making the structure more visually obvious.
Fixes #

📖 Add more explanation in docs/README.md

---

README.md
docs/content/v0.20/README.md
test/integration/multi-cluster-deployment/README.md

This PR updates some doc to make its status explicit.
Fixes #

📖 Make status of documents explicit.

---

.github/workflows/pr-test-singleton-status.yml
README.md
test/e2e/singleton-status/README.md
test/e2e/singleton-status/cleanup.sh
test/e2e/singleton-status/run-test.sh
test/e2e/singleton-status/setup-kubestellar.sh
test/e2e/singleton-status/workload-deployment.sh

This PR adds a test of the return of status in the 1:1 distribution case.
Fixes #

🌱 Add singleton test

---

pkg/placement/controller.go
pkg/status/controller.go
pkg/util/keys.go

This PR simplifies the controllers by removing some string encoding and decoding.
Fixes #

🌱 Remove some string encoding and parsing

---

Makefile
README.md
config/manager/kustomization.yaml
config/postcreate-hooks/kubestellar.yaml
config/postcreate-hooks/ocm.yaml
core-helm-chart/templates/operator.yaml
docs/content/v0.20/README.md
docs/content/v0.20/thirdparties.md
test/pre-reqs.md

Update the base README for all scenarios to work with latest builds from Jan 17, 2024
This is still an interim README until the docs work is completed.

📖 update v0.20/README.md for all scenarios to work with latest builds

---

.github/workflows/add-to-project.yml

Change the project pointer to point to our new project
Fixes #

:bug: Update add-to-project.yml

---

.github/workflows/pull_request.yml

Update the workflow to add PRs to our new project
Fixes #

:bug: Update the workflow to add PRs to our new project

---

docs/content/v0.20/README.md

Some minor adjustments to the interim README file. The instructions have been fully tested for the v0.20.0-alpha.1  snapshot.

📖  minor adjustments for interim README file

---

.github/workflows/pr-test-multicluster.yml
.github/workflows/pr-test-singleton-status.yml

This PR does a bit of regularization of the GitHub workflows that test PRs, mainly establishing a regular pattern for their names.
Fixes #

🌱 Regularize the GH workflows for testing PRs

---

docs/content/v0.20/examples.md

📖 Add CLI alternative to syncing Argo CD App

---

config/postcreate-hooks/kubestellar.yaml
hack/build-helm-image.sh

- provide script for building the Helm container image
- created multi arch image `3.14.0`
- updated the reference in the yaml
Fixes #

✨ Provide build script for Helm image

---

docs/content/v0.20/packaging.md

Update the tag version of `clusteradm` and `helm` images.
Fixes #

📖 Update the reference to image tags in packaging.md

---

README.md

:bug: Update the KubeStellar README badges

---

pkg/placement/controller.go
pkg/placement/crd.go
pkg/status/controller.go

This PR fixes a bug as #1553, and another similar bug.
Fixes #1553

🐛 Get back missing group or missing resource

---

docs/content/v0.20/examples.md
test/e2e/common/setup-kubestellar.sh

Explain what's expected in step 6 of the common kubestellar setup.
This handles issue #1545 .
Fixes #1545

✨ explain step 6 in the common setup

---

docs/content/v0.20/pre-reqs.md

Fix typo in the pre-req doc.
Fixes #
#1626

🐛 fix typo in pre-req doc

---

.github/workflows/pr-test-multicluster.yml
.github/workflows/pr-test-singleton-status.yml
docs/content/v0.20/pre-reqs.md

update pre-reqs for KubeFlex to v0.4.1
Fixes #1638

📖 update pre-reqs for KubeFlex to v0.4.1

---

api/edge/v1alpha1/types.go
api/edge/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/edge.kubestellar.io_placements.yaml
pkg/crd/files/edge.kubestellar.io_placements.yaml

🌱 Don't expose spec.numberOfClusters of placements

---

example/kind-nginx-ingress-with-SSL-passthrough.yaml

This PR restores a broadly useful example, which is still used by CI for testing release-0.14.
This is part of #1585 and is blocking CI success on #1660
Fixes #

🐛 Restore example ingress-with-SSL-passthrough

---

docs/content/v0.20/example-wecs.md

Add a note explaining the CSR pending condition.
Fixes #
https://github.com/kubestellar/kubestellar/issues/1634

:book: Documentation improvement for CSR condition

---

.github/workflows/pr-test-multicluster.yml
.github/workflows/pr-test-singleton-status.yml
docs/content/v0.20/pre-reqs.md
test/e2e/common/setup-kubestellar.sh

Disable chatty output in CICD.
Fixes #1646

✨ use kubeflex chatty flag

---

docs/content/v0.20/examples.md

📖 Remove spaces

---

docs/content/v0.20/contributor.md
docs/content/v0.20/examples.md
docs/content/v0.20/pre-reqs.md
hack/check_pre_req.sh

Provide a utility script to check several pre-requisites. 
This may be useful in support of other scripts and for user debugging.
Command line:
```shell
$ ./check_pre_req.sh --help
Usage: ./check_pre_req.sh [-A|--assert] [-L|--list] [-V|--verbose] [-X] [program1] [program2] ...
```
Listing all programs that can be checked:
```shell
$ ./check_pre_req.sh --list
argo brew docker go helm jq kind ko make ocm yq
```
Check several Go related dependencies:
```shell
$ ./check_pre_req.sh go ko
Checking KubeStellar pre-requisites:
✅ Go
✅ KO
```
Check verbosely, showing resolution suggestions:
```shell
$ ./check_pre_req.sh -V argo
Checking KubeStellar pre-requisites:
❌ ArgoCD CLI
install: https://argo-cd.readthedocs.io/en/stable/cli_installation/
```
Fixes #

✨ Add script to check pre-requisites

---

.github/workflows/docs-ecutable-mailbox.yml
.github/workflows/docs-ecutable-placement.yml
.github/workflows/docs-ecutable-qs.yml
.github/workflows/docs-ecutable-syncer.yml
.github/workflows/docs-ecutable-user-quickstart-kind.yml
.github/workflows/docs-ecutable-where-resolver.yml

This PR narrows the applicability of the remaining docs-ecutable workflows to legacy releases, in the workflow definitions in the `main` branch.
This is part of addressing #1585 
Fixes #

🌱 Restore other docs-ecutable workflows for legacy releases, for main

---

pkg/crd/crds.go

fixed the following comment from code review on issue #1676:
https://github.com/kubestellar/kubestellar/pull/1676#discussion_r1473120706
This is failing too aggressively. The problem in err might not be relevant to the particular gvk of interest here. See #1466 
Fixes #

🐛 fixed comment from code review

---

.github/workflows/docs-ecutable-mailbox.yml
.github/workflows/docs-ecutable-placement.yml
.github/workflows/docs-ecutable-qs.yml
.github/workflows/docs-ecutable-syncer.yml
.github/workflows/docs-ecutable-user-quickstart-kind.yml
.github/workflows/docs-ecutable-where-resolver.yml

This PR narrows what the remaining docs-ecutable workflows say they apply to, restricting them to legacy releases.
This addresses part of #1585 
Fixes #

🌱 Restore other docs-ecutable workflows for legacy releases, for release-0.14

---

Makefile

✨ Let `make ko-build-local` produce platform-specific container image

---

docs/content/v0.20/examples.md

This PR temporarily gets back to the 'edge.kubestellar.io' API group for Placements in the user-facing examples. So that the instructions and the container images in that doc are consistent.
We will update the examples again when we have the new images published.

🌱 Temporarily get back the 'edge.kubestellar.io' group for user examples

---

hack/inspect-image.py

This PR enhances the `hack/inspect-image.py` script, so that when it gets an authorization failure of the form commonly gotten from ghcr.io, it will try the suggested request to get a bearer token.
Fixes #

✨ Add some bearer token automation to inspect-image.py

---

.github/workflows/pr-test-multicluster.yml
.github/workflows/pr-test-singleton-status.yml

This PR revises the state dump at the end of the test workflows, to more clearly separate the different parts.
This is in place of https://github.com/vMaroon/kubestellar/pull/9
Fixes #

✨ Improve post-test state dump

---

.github/workflows/pr-test-multicluster.yml
.github/workflows/pr-test-singleton-status.yml

This PR extends the state dumping at the end of the e2e tests to include the Deployment objects on the WEC(s).
Fixes #

✨ Add final state dump of Deployment objs in WEC(s)

---

docs/content/v0.20/packaging.md

This PR tries to fill out the description of the OCM status addon, and discovers that there is not much ready to say about the OCM transport plugin.
Fixes #

📖 Extend packaging.md

---

docs/content/v0.20/examples.md
test/e2e/common/setup-kubestellar.sh

update ocm-status-addon chart reference to public ks repo
Fixes #1726

🐛 update ocm-status-addon chart reference to public ks repo

---

pkg/binding/controller.go

set c.allowedGroupsSet in NewController()
Fixes #1742

🐛 set c.allowedGroupsSet in NewController()

---

docs/content/v0.20/examples.md
test/e2e/common/setup-kubestellar.sh

Fixing references to use v0.2.0-alpha.1
Fixes #

🐛 fix references to status addon chart

---

hack/build-clusteradm-image.sh
hack/build-helm-image.sh

- `chmod +x`
- fix env path
Fixes #

🐛 Fix env path and add +x 

---

docs/content/v0.20/packaging.md

This PR updates packaging.md to describe how the clusteradm container image is built.
Fixes #

📖 Describe clusteradm in packaging.md

---

cmd/transport/options/options.go
options/client-options.go

fix point (1) in issue #1750 
Fixes #

🌱 move client options from cmd to options dir

---

docs/content/v0.20/release-notes.md

:sparkles:  Initial Release limitations doc

---

api/control/v1alpha1/types.go
config/crd/bases/control.kubestellar.io_bindings.yaml
pkg/crd/files/control.kubestellar.io_bindings.yaml

This PR addresses [this comment](https://github.com/kubestellar/kubestellar/pull/1761#discussion_r1489733533) to #1761.

📖 Tweak go doc comments for the binding API

---

docs/content/v0.20/examples.md
test/e2e/common/setup-kubestellar.sh

Update refs to latest status add-on.
Fixes #

✨ update references to status addon

---

docs/content/v0.20/packaging.md

This PR fills in some more information in packaging.md.
Fixes #

📖 Further updates to packaging.md

---

pkg/binding/controller.go

This PR adds a bit more logging in the binding controller.
Fixes #

🌱 Add more debug logging in binding controller

---

pkg/binding/controller.go
pkg/binding/controller_test.go

This PR attempts to add a unit test for the binding controller.
This PR takes the approach of using fake clientsets.
Fixes #

✨ Start unit test of binding controller, using fake clientsets

---

pkg/binding/bindingpolicy.go

This PR adds more error wrapping in the binding controller.
Fixes #

✨ Add some more error wrapping

---

docs/content/v0.20/packaging.md

This PR updates packaging.md to be accurate about the current status of the ocm-transport-plugin and its dependency cycle with ks/ks.
Fixes #

📖 Note dependency cycle between ks/ks and ks/OTP

---

config/postcreate-hooks/kubestellar.yaml

This PR tweaks the kubestellar-controller-manager PostCreateHook for the upcoming 0.20.0-rc2 release.
Fixes #

🌱 Tweak KCM PCH for release 0.20.0-rc2

---

docs/content/v0.20/example-wecs.md
docs/content/v0.20/examples.md
docs/content/v0.20/thirdparties.md

- Updates references to release 
- minor updates to example using the  --resource filter with "host" type CP

📖 update examples.md for v0.20.0-rc2

---

docs/content/v0.20/README.md
docs/content/v0.20/examples.md
docs/content/v0.20/user-guide.md

This PR introduces a non-legacy user guide. Much more needs to be done, but this adds a few bits of information that we urgently want to get out.
Fixes #

📖 Start v020 user guide

---

docs/content/v0.20/README.md
docs/content/v0.20/release.md

This PR is intended to design and document the release process for this repo. This PR is currently incomplete.
Fixes #1732
This interacts with the website design, whose updating is (sort of?) in #1535 .

📖 Start drafting release process

---

docs/content/v0.20/release-notes.md

This PR slightly updates release-notes.md, to make it not look useless for the 0.20.0 release.
Fixes #

📖 Slightly freshen release-notes.md

---

docs/content/v0.20/README.md

This PR does the last of the self-reference edits in preparation for release 0.20.0. This changes the place in the README that wishes it could reference "the latest stable release".
Fixes #

📖 Update ersatz latest reference for coming 0.20.0

---

pkg/transport/generic_transport_controller.go

This PR factors the generic transport controller to allow the caller to take responsibility for determining the wrapper GVR. This enables unit testing with fakes that do not sufficiently support discovery.
This PR also fixes a bug regarding worker ID.
Fixes #

🌱 Factor discovery out of the generic transport controller

---

docs/content/v0.20/examples.md
test/e2e/common/setup-kubestellar.sh

Update refs to the latest status add-on version.
Fixes #

:sparkles: Update references to status addon v0.2.0-rc3

---

.github/workflows/pr-test-multicluster.yml
.github/workflows/pr-test-singleton-status.yml
test/e2e/common/cleanup.sh
test/e2e/common/setup-kubestellar.sh

🌱 run transport controller in e2e tests

---

pkg/transport/generic_tranpsort_controller_test.go

This PR adds a unit test of the generic transport controller.
Fixes #

✨ Add unit test of generic transport controller

---

docs/content/v0.20/examples.md

📖 updated how to run transport controller in example.md

---

docs/content/v0.20/examples.md

fix of minor comments that were left from #1808 
Fixes #

📖 fixed minor issues in example.md

---

docs/content/v0.20/README.md
docs/content/v0.20/contributor.md
docs/content/v0.20/packaging.md
docs/content/v0.20/release.md
test/e2e/README.md

This PR does some catch-up on the existing document set.
Fixes #

📖 Some overdue documentation updates

---

.github/workflows/pr-test-integration.yml
.gitignore
.prow.yaml
docs/content/v0.20/contributor.md
hack/run-integration-tests.sh
test/integration/controller-manager/matching_test.go

This PR adds a Prow job that runs the integration test.
This is built on #1769 , and will be rebased if that merges first.
Fixes #

✨ Run the integration test in CI

---

.github/workflows/pr-test-object-fields-filtering.yml
test/e2e/object-fields-filtering/README.md
test/e2e/object-fields-filtering/run-test.sh
test/e2e/object-fields-filtering/use-kubestellar.sh

This PR adds e2e test that includes distribution of service. 
this PR aims to validate the work that have been done in #1812 
Fixes #

🌱 added e2e to test service distribution

---

pkg/ocm/ocm.go

remove unused code from pkg/ocm.
after the transition to pluggable transport, the removed code is not used anymore. 
Fixes #

🌱 remove unused functions from pkg/ocm

---

hack/run-integration-tests.sh
pkg/binding/binding.go
pkg/binding/bindingpolicy-resolution.go
pkg/binding/bindingpolicy.go
pkg/binding/controller.go
pkg/binding/selectors.go
test/integration/controller-manager/matching_test.go

This PR fixes the construction of the DownsyncObjectReferences in the binding controller.
Fixes #1788

🐛 Fix downsync

---

docs/content/direct/architecture.md
docs/mkdocs.yml

Step by step pulling the docs into the site
Fixes #

:sparkles: Add arch doc into doc site

---

.github/workflows/pr-test-multicluster.yml
.github/workflows/pr-test-object-fields-filtering.yml
.github/workflows/pr-test-singleton-status.yml

:sparkles:  Don't run tests when docs are changed

---

docs/content/direct/architecture.md
docs/mkdocs.yml
docs/requirements.txt

:sparkles: try using caption plugin

---

.github/workflows/pr-test-integration.yml
.github/workflows/pr-test-multicluster.yml
.github/workflows/pr-test-object-fields-filtering.yml
.github/workflows/pr-test-singleton-status.yml

:sparkles:  fix actions

---

docs/content/direct/architecture.md

:sparkles: fix image captions

---

docs/content/direct/architecture.md

:sparkles: Make images work both on web site and on MD files

---

pkg/binding/controller.go
pkg/ocm/ocm.go
pkg/util/unstructured.go

This PR removes unused code. most of the unused code became redundant after the transition to pluggable transport.
there is more cleanup to do as we make progress.
Fixes #

🌱 removed unused code

---

pkg/binding/controller.go

This PR contains changes to address some of the open comments to #1828.

🌱 Some follow-up changes after PR1828

---

scripts/add-helm-code.sh
test/e2e/common/setup-kubestellar.sh
test/e2e/multi-cluster-deployment/run-test.sh

Doing it again since I botched the rebase
Fixes #
#1883

🐛 Add pre req check in some e2e scripts

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md
docs/content/direct/release-notes.md

prep for release. 
in `examples.md` there are many places to update the same version. this is tedious and error prone.
I've added a step to define the required versions and then use these versions in all other steps.
Fixes #

📖  prep for release 0.21.0-rc1

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md
docs/content/direct/release-notes.md

0.21.0 rc1 had a typo in examples.md file in deploy transport script url (missed `v`).
this PR fixed this issue and bump to rc2.
Fixes #

📖 prep of 0.21.0 rc2

---

.github/workflows/pr-test-object-cleaning.yml
.gitignore
test/e2e/README.md
test/e2e/object-cleaning/README.md
test/e2e/object-cleaning/run-test.sh
test/e2e/object-cleaning/use-kubestellar.sh

This PR does the renaming in response to [this comment](https://github.com/kubestellar/kubestellar/pull/1891#discussion_r1522545642).

📖 Rename 'object fields filtering' to 'object cleaning' in tests

---

docs/content/direct/README.md
docs/content/direct/examples.md
docs/content/direct/release-notes.md

This PR fixes various problems I found reviewing 0.21.0-rc2 and trying to run through examples.md.  I did not get past the setup.
Fixes #

📖 Fix doc bugs just found

---

docs/content/direct/examples.md
docs/content/direct/packaging.md
test/e2e/common/setup-kubestellar.sh

This PR updates the kubestellar repo to depend on rc6 of the ocm-status-addon repo.
Fixes #

🌱 Update ocm-status-addon dependency from rc3 to rc6

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md

This PR updates the self-references for the upcoming RC3.
Fixes #

🌱 Update self-references for release 0.21.0-rc3

---

docs/content/direct/examples.md

This PR updates examples.md to fix problems I noticed while testing scenarios 1, 2, and 5.
Fixes #

📖 Fix problems in examples.md

---

README.md

This PR fixes a broken pointer to the website, removes a useless pointer to the website, and consolidates pointers to documentation.
Fixes #1908

📖 Update doc pointers in README

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md

This PR updates the self-references to anticipate release 0.21.0.
Fixes #

✨ Update self-references for release 0.21.0

---

docs/content/readme.md

:bug: fix links to images

---

docs/mkdocs.yml

This PR reorganizes the website navigation tree so that it has one branch for contributors.
Fixes #1923 
Fixes #1924 
Fixes #1926

📖 Reorg to one branch for contributors

---

docs/mkdocs.yml
docs/requirements.txt

:bug:  Add support for mermaid diagrams

---

scripts/deploy-transport-controller.sh
test/e2e/common/setup-kubestellar.sh

🌱 bump OTP version

---

README.md

This PR updates the comment in the root README about where to find documentation.
Fixes #

📖 Fix root README

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md
docs/content/direct/release-notes.md

 :sparkles: New release - 0.21.1

---

.github/workflows/pr-test-e2e.yml
test/e2e/ginkgo/multiple_cluster_deployment_test.go
test/util/util.go

The PR makes various improvements and fixes in resilience testing.
This is intended to causes of flakiness that I know about now. The flakiness is part of #1951 .

🐛 Fixup resiliency testing

---

docs/content/direct/hosting-cluster.md
docs/content/direct/ks-on-k3d.md
docs/content/direct/ks-on-kind.md
docs/content/direct/ks-on-ocp.md
docs/mkdocs.yml

:sparkles: Add and rearrange some sections in kubestellar.io

---

Makefile

Fix regression introduced by #1920  by removing the CRDs from the Helm chart
Fixes #1965

🐛 remove CRDs from Helm chart

---

docs/content/direct/architecture.md

Update architecture doc to be aligned with the changes in https://github.com/kubestellar/kubestellar/pull/1900
Fixes https://github.com/kubestellar/kubestellar/issues/1688

:book: Update architecture doc

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md
docs/content/direct/release-notes.md

This PR updates the self-references and release notes in preparation for release 0.21.2-rc1.
Fixes #

✨ Self reference and related prep for release 0.21.2-rc1

---

hack/Dockerfile.kubectl
hack/build-kubectl-image.sh

Script to build kubectl image
Fixes #

✨ Script to build kubectl image

---

docs/content/direct/packaging.md

This PR makes some overdue updates to packaging.md, listing newer published artifacts.
Fixes #

📖 Add recent stuff to packaging.md

---

docs/content/direct/release.md

This PR updates the release process doc, mainly covering changes we have made since this doc was last updated. This primarily concerns getting the website back in business and the policy for release branches.
Fixes #

📖 Catch-up for the relase process doc

---

docs/content/direct/ks-on-k3d.md
docs/mkdocs.yml

:book: Move k3d doc to the correct place

---

GOVERNANCE.md
docs/content/docs-readme.md
docs/mkdocs.yml

Discovered intended way to publish docs/README.md.
This PR replaces one relative link to non-doc contents and recognizes the intended way to publish docs/README.md.
Fixes #

🐛 Fix more broken links

---

.github/workflows/test-latest-release.yml

Remove v tag trigger from test-latest-release action.
Fixes #1981

✨ fix issue 1981 by removing tag trigger

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md
docs/content/direct/release-notes.md

This PR updates the self references and description, in preparation for making release candidate 2 for 0.21.2.
Fixes #

✨ Update self-references in prep for release 0.21.2-rc2

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md

:sparkles:  Prep release 0.21.2

---

scripts/update-release.sh

:sparkles:  A simple helper script to update the version number

---

docs/content/direct/architecture.md

Looks like mkdocs need some more formatting to handle list items and sub items.
Before:
After:
Before:
After:
Before:
After:
Fixes #

📖 Updates for mkdocs to better render the architecture webpage

---

pkg/transport/filtering/job.go

This PR makes the cleaning of Job objects more extensive. As reported in #1936 , in my testing it got the Job objects to the WEC but also received error messages in the ManifestWorkStatus.
This is intended to address #1936 but is not entirely satisfactory (yet).

🐛 More better Job cleaning

---

docs/content/direct/best-practices.md
docs/mkdocs.yml

:book: Starting best practices

---

docs/content/direct/release.md

This PR updates the release process document to:
- Move the step-by-step instructions up to be the first thing in the document; and
- Add some mentions of the dependency cycle between ks/ks and ks/OTP.
Fixes #

📖 Re-org and extend release process doc

---

docs/content/direct/examples.md
docs/content/direct/thirdparties.md

This PR extends examples.md with instructions on how to teardown each scenario without un-deploying KubeStellar.
Fixes #

📖 Add teardown instructions to examples.md

---

docs/content/direct/examples.md

This PR fixes a typo that was introduced in #2014 .
Fixes #

📖 Fix typo

---

docs/content/direct/architecture.md

Fixed some bullet formatting in the architecture document to resolve inconsitency between the intent (from the markdown) vs the rendered docuemntation.
None

:book: Minor formatting tweaks to architecture docs

---

pkg/binding/controller.go
pkg/transport/generic_transport_controller.go
test/e2e/ginkgo/multiple_cluster_deployment_test.go

✨ Fix a panic in the transport handleWrappedObject()
Fix a panic in the transport handleWrappedObject().
Fixes #1850

✨ Fix a panic in the transport handleWrappedObject

---

test/e2e/common/cleanup.sh
test/e2e/common/setup-kubestellar-ocp.sh
test/e2e/multi-cluster-deployment/README.md
test/e2e/multi-cluster-deployment/run-test.sh
test/e2e/multi-cluster-deployment/use-kubestellar.sh

This PR adds an easy release testing for KS on OCP for deployment in multiple clusters
https://github.com/kubestellar/kubestellar/issues/2037
Fixes #

✨   KS release test OCP: deployment in multiple clusters

---

docs/content/direct/release-testing.md
docs/content/direct/release.md

Describe the testing need to be done for each release
Fixes #2022

:book: Document the testing process for a Release

---

.github/workflows/greetings.yml

This PR narrows the conditions under which the greetings workflow runs. We do not need it to run on every push and comment to a PR or issue.
Fixes #

🌱 More selective triggering of .github/workflows/greetings.yml

---

docs/content/direct/README.md
docs/mkdocs.yml

This PR (a) fixes the link to `user-guide.md` in `docs/mkdocs.yml` (which makes the navigation in the website) and (b) adds a link to `user-guide.md` in `docs/content/direct/README.md`.
Fixes #

📖 Fix links to user-guide.md

---

docs/content/direct/architecture.md

This PR updates the architecture document, mainly regarding the OCM Status Add-On Agent. This PR also makes some references to OCM object types into hyperlinks to their souce (which is helpful for developers). This PR also changes several references to Go datatypes to use code-quoting instead of emphasis.
Fixes #2078

📖 Mostly update the architecture doc of status add-on agent

---

api/control/v1alpha1/register.go
pkg/crd/crds.go
pkg/transport/cmd/generic-main.go
pkg/transport/custom_transform_collection.go
pkg/transport/generic_transport_controller.go
pkg/transport/generic_transport_controller_test.go

This PR adds the behavior intended for CustomTransform objects.
This PR fixes an oversight in #2045, which neglected to update the API object type registration func to include the new object types.
This finishes the implementation part of #1976 . The documentation and some testing remain.

✨ Implement custom transforms

---

docs/README.md
docs/content/direct/user-guide.md

This PR fixes the way Jinja examples are quoted.
Fixes #

📖 Fix quoting of jinja syntax

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md
docs/content/direct/release-notes.md

This PR makes the self-reference updates for release 0.22.0-rc1.
Fixes #

✨ Update self-references for release 0.22.0-rc1

---

docs/content/direct/release-notes.md

This PR expands the release note for 0.22.0, noting more features and bug fixes.
Fixes #

📖 Expand release note for 0.22.0

---

docs/content/direct/deploy-on-k3d.md
docs/content/direct/examples.md
docs/content/direct/release.md
test/e2e/common/setup-kubestellar.sh
test/e2e/multi-cluster-deployment/README.md

This PR updates the references to ks/OSA to use the latest version, and updates the release procedure document to mention this.
This PR also updates the `deploy-on-k3d.md` document to something that works for me, where "works" means that it runs successfully and can be followed by use of examples.md. This involved retreating from some changes that anticipated some sensible renaming of things in other files (such as examples.md). I think that the ambition is laudible but belongs in a separate PR.
Fixes #2087

🐛 Document and update dependency of ks/ks on ks/OSA

---

docs/content/direct/packaging.md

This PR replaces the tables in `packaging.md` with statements of the rules that the tables reflected.
Fixes #

📖 Replace the image/chart listings in packaging.md with rules

---

docs/content/direct/examples.md
scripts/deploy-transport-controller.sh
test/e2e/common/setup-kubestellar.sh

The PR updates KubeStellar to depend on release 0.1.6 of ks/ocm-transport-plugin.
Fixes #

✨ Track release 0.1.6 of ks/OTP

---

test/e2e/common/cleanup.sh
test/e2e/common/setup-kubestellar-ocp.sh
test/e2e/multi-cluster-deployment/README.md
test/e2e/multi-cluster-deployment/run-test.sh

This PR fixes bugs on the e2e script to install KS on ocp for release-0.22.0-rc2.
It was successfully tested on the e2e test scripts and ginkgo tests
Fixes #

🐛 bug fix: Updating install for kcp on ocp for release-0.22.0-rc2

---

docs/content/direct/contributor.md

Signed-off-by: Pratik-Mahalle <mahallepratik683@gmail.com>
Fixes #

📖 docs : Updating the contributor.md file by removing the height!

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md
docs/content/direct/release-notes.md
docs/content/direct/release.md
test/e2e/multi-cluster-deployment/README.md

This PR updates the self-references in preparation for the upcoming release (0.22.0-rc3).
This PR also adds some overlooked content in the release notes.
Fixes #

✨ Prep for 0220rc3

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md
scripts/deploy-transport-controller.sh
test/e2e/common/setup-kubestellar.sh
test/e2e/multi-cluster-deployment/README.md

This PR tracks the creation of the 0.1.7 release of ks/OTP and updates the self-references for the 0.22.0 release of ks/ks.
Fixes #

✨ Track OTP 0.1.7 and prep ks 0.22.0

---

home.html

I hope that this PR will fix #2121 .
Will fix #2121 if we are lucky.

📖 Make home.html redirect to latest instead of stable

---

docs/README.md

This PR updates docs/README.md to clarify the fact that we have two websites and how the redirects work.
Fixes #

📖 Clarify remarks about GoDaddy and redirects

---

docs/README.md

This PR adds @clubanderson's email to `docs/README.md`.
Fixes #

📖 Add Andy's email to docs/README.md

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/README.md
docs/content/direct/examples.md
docs/content/direct/release-notes.md
test/e2e/multi-cluster-deployment/README.md

This PR updates the self-references in preparation for release 0.23.0-alpha.1.
This PR also contributes to the campaign of washing the word "stable" out of our mouths.
Fixes #

✨ Update self-references for ks/ks release 0.23.0-alpha.1

---

test/e2e/common/setup-kubestellar.sh

This PR fixes quoting bugs in `test/e2e/common/setup-kubestellar.sh` introduced in #2137 .
Fixes #2147

🐛 Fixed quoting snafu

---

config/postcreate-hooks/kubestellar.yaml
docs/content/direct/examples.md

This PR updates the self-references for upcoming release 0.23.0-alpha.2.
Fixes #

✨ Update self-references for 0.23.0-alpha.2

---

test/e2e/README.md
test/e2e/bash/README.md
test/e2e/ginkgo/README.md

This PR updates the `test/e2e/README.md` to be a decent introduction to the whole topic of E2E testing, and trims the READMEs in the scenario subdirectories to focus on describing their scenario.
Fixes #

📖 Brush up E2E READMEs

---

.github/workflows/goreleaser.yml
.gitignore
core-chart/.helmignore
core-chart/Chart.yaml
core-chart/LICENSE
core-chart/templates/NOTES.txt
core-chart/templates/cps/its.yaml
core-chart/templates/cps/wds.yaml
core-chart/templates/kubeflex-clusterrolebinding.yaml
core-chart/templates/kubeflex-namespaces.yaml
core-chart/templates/postcreatehooks/its.yaml
core-chart/templates/postcreatehooks/wds.yaml
core-chart/templates/pre-delete-hook.yaml
core-chart/values.yaml
docs/content/direct/common-setup-core-chart.md
docs/content/direct/common-setup-step-by-step.md
docs/content/direct/core-chart.md
docs/content/direct/examples.md
docs/content/direct/microshift.md
scripts/create-k3s-cluster-with-SSL-passthrough.sh
scripts/create-kind-cluster-with-SSL-passthrough.sh

This PR proposes a first version of the KubeStellar Core chart that allows one to:
1. install KubeFlex and its requirements
2. install PCHs for ITSes and WDSes
3. install a  user defined list of ITSes and WDSes
This PR attempts to provide an update to the goreleaser to automatically generate the chart upon a new release.
Please see this initial documentation: https://github.com/francostellari/kubestellar/blob/hub-chart/docs/content/direct/hub-chart.md
Not included in this PR:
1. update of the example.md to reflect the availability of this chart (I think this should be done after the first version of the chart is actually released, without advertising, and tested... a chart must be released to be actually used)
2. the new documentation is not connected to the overall documentation
Fixes #

✨ KubeStellar Core chart

---

docs/content/direct/common-setup-core-chart.md
docs/content/direct/core-chart.md

Update docs to remove unnecessary `sudo su` for kinf/k3s installation scripts
Fixes #

📖 Update docs to remove unnecessary `sudo su`

---

config/postcreate-hooks/kubestellar.yaml
core-chart/values.yaml
docs/content/direct/README.md
docs/content/direct/common-setup-core-chart.md
docs/content/direct/common-setup-step-by-step.md
docs/content/direct/core-chart.md
docs/content/direct/microshift.md
docs/content/direct/release.md

This PR updates the self-references for the 0.23.0-alpha.3 prerelease.
Fixes #

✨ Update self references and release doc for 0.23.0-alpha.3

---

docs/content/direct/core-chart.md
docs/content/direct/release.md

This PR catches more self-references in core-chart.md.
Fixes #

✨ More self-references in core-chart.md

---

core-chart/templates/NOTES.txt
docs/content/direct/core-chart.md

Improve code to retrieve the CP kubeconfigs
Fixes #

📖 Improve code to retrieve the CP kubeconfigs

---

config/postcreate-hooks/kubestellar.yaml
core-chart/values.yaml
docs/content/direct/README.md
docs/content/direct/common-setup-core-chart.md
docs/content/direct/common-setup-step-by-step.md
docs/content/direct/core-chart.md
docs/content/direct/microshift.md
docs/content/direct/release-notes.md

This PR updates the self-references in preparation for release 0.23.0-alpha.4.
Fixes #

✨ Update self-references for 0.23.0-alpha.4 release

---

docs/content/direct/deploy-on-k3d.md

This PR updates the reported experience with K3D, to use the latest KubeStellar release. This is good because the existing report uses too old a release to have all the 0.22.0 features.
Fixes #2130

📖 Fix install report for K3d

---

docs/content/direct/deploy-on-k3d.md

This PR fixes the report of deploying on K3D, in the `main` branch. This is the same change as #2189, but applied to the `main` branch.
Fixes #2130

📖 Update deploy-on-k3d.md

---

config/postcreate-hooks/kubestellar.yaml
core-chart/values.yaml
docs/content/direct/README.md
docs/content/direct/common-setup-core-chart.md
docs/content/direct/common-setup-step-by-step.md
docs/content/direct/core-chart.md
docs/content/direct/microshift.md
docs/content/direct/release-notes.md

This PR is the prep for making 0.23.0-rc1.
Fixes #

✨ Update self-references for release 0.23.0-rc1

---

.github/workflows/test-latest-release.yml

This PR fixes the GitHub Actions workflow that tests the latest release, to track changes made in #2167 .
Fixes #

🐛 Track change in E2E testing organization

---

docs/content/direct/architecture.md
docs/content/direct/packaging.md

This PR primarily updates the packaging document to account for developments over the past few months.
Preview available at https://mikespreitzer.github.io/kcp-edge-mc/doc-update-610/direct/packaging/ .
This PR also makes some updates to the architecture document, for clarity and precision.
Fixes #

📖 Update packaging doc

---

docs/content/direct/examples.md

✨  Update examples.md to include the term "helm" in the description of the link to helm chart install instructions.

---

.github/ISSUE_TEMPLATE/bug_report.yaml

Remove the old instructions for specific KS info collection, these instructions are not suitable for the new KS. For now, the general template asking for bug description, logs, and expected behavior is good enough.
Fixes #

:bug: Update the "new bug" template

---

docs/content/direct/pre-reqs.md

This PR makes some small improvements to the wording in the pre-reqs document.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-update-621b/direct/pre-reqs/
Fixes #

📖 Tweak wording in pre-reqs.md

---

.github/ISSUE_TEMPLATE/bug_report.yaml

This PR extends the bug report form with prompts for information that we often need to ask for.
Fixes #

🌱 Extend prompting in bug report form

---

docs/content/direct/hosting-cluster.md

This PR adds a note about the version of k3d that was tested.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-k3d-version/direct/hosting-cluster/#create-a-k3d-cluster
Fixes #

📖 Restore doc of the tested version of k3d

---

.github/spellcheck/.wordlist.txt
CODE_OF_CONDUCT.md
docs/content/direct/architecture.md
docs/content/direct/core-chart.md
docs/content/direct/release-notes.md
docs/content/direct/release.md
test/e2e/README.md
test/e2e/ginkgo/README.md
test/performance/README.md

This PR fixes more spelling problems in the website.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-spellfix-2/readme/
Fixes #

📖 Another batch of speling fickses

---

test/e2e/ginkgo/multiple_cluster_deployment_test.go

This PR extends the ginkgo E2E test with a scenario that flaps the workload object label matched by the BindingPolicy, checking that the object is removed from and then restored to the WECs.
Fixes #

🌱 Add E2E test scenarios manipulating object label

---

test/e2e/ginkgo/multiple_cluster_deployment_test.go
test/util/util.go

E2e tests for combined status functionality.
Fixes #

:sparkles: Combined status tests

---

test/e2e/ginkgo/multiple_cluster_deployment_test.go

This PR makes the individual specs in the ginkgo end-to-end functional test file take a `ctx context.Context`, because they need one and it is better to take the one from Ginkgo than create a `context.Background`.
Fixes #

✨ Make ginkgo subject nodes interruptable

---

docs/content/direct/pre-reqs.md

🐛 Update pre-reqs.md to fix spellings

---

docs/content/direct/example-scenarios.md

This PR updates the example scenarios document with links to setup instructions.
Preview in https://mikespreitzer.github.io/kcp-edge-mc/doc-0231-more-links/direct/example-scenarios/
Fixes #

📖 [release-0.23.1] Add pointers into example-scenarios.md

---

docs/content/direct/best-practices.md
docs/content/direct/example-scenarios.md
docs/content/direct/get-started.md
docs/content/direct/setup-limitations.md
docs/content/direct/setup-overview.md
docs/content/direct/usage-limitations.md
docs/content/direct/user-guide-intro.md
docs/content/direct/wec-registration.md
docs/content/direct/wec.md
docs/mkdocs.yml

This PR adds some intermediate levels of structure into the user guide, to make it easier to follow.
This PR also fixes a few minor botches noticed along the way.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-ug-deeper/direct/user-guide-intro/
Fixes #

📖 Add intermediate levels of organization into the user guide

---

docs/content/direct/get-started.md

:bug: Update get-started.md so that "cluster" is changed to "clusters" to reflect multiplicity

---

docs/content/direct/pre-reqs.md

🐛  Update pre-reqs.md so that "fist" is spelled as "first"

---

docs/content/direct/core-chart.md

🐛  Update core-chart.md so that "|| true" is deleted to avoid redundancy

---

docs/content/direct/pre-reqs.md

:book: 📖 docs Update pre-reqs.md grammatical changes: "An" to "a"

---

docs/content/direct/combined-status.md

This PR updates the user documentation about the combined status feature, in a couple of ways. One is to track developments that have happen since this doc was written. Another is to hopefully make it more precise and clear.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-update-713/direct/combined-status/
Fixes #

📖 Clarify status combining feature

---

docs/content/direct/pre-reqs.md

:book: 📖 docs Update pre-reqs.md; fixed capitalization of Kubestellar

---

docs/content/direct/pre-reqs.md

Fix for issue #2290
Fixes #2290

🐛  Update pre-reqs.md to add links

---

docs/mkdocs.yml

🐛 Update mkdocs.yml so that Releaes Testing is corrected to Release Testing

---

api/control/v1alpha1/types.go
config/crd/bases/control.kubestellar.io_bindingpolicies.yaml
config/crd/bases/control.kubestellar.io_combinedstatuses.yaml
config/crd/bases/control.kubestellar.io_statuscollectors.yaml
pkg/crd/files/crds.yaml
pkg/status/cel-evaluator.go
pkg/status/controller.go
pkg/status/statuscollector.go
test/util/util.go

This PR implements [StatusCollector validation](https://github.com/kubestellar/kubestellar/pull/2174#discussion_r1630076164) as outlined in #2141 
It also involves minor code refactoring.
- #2141

:sparkles: StatusCollector validation & error propagation to CR

---

docs/content/direct/pr-signing.md

Includes basic instructions on setting up GPG/SSH keys and submitting/signing PRs on the kubestellar github
Fixes #

✨ Create pr-signing.md, a guide for signing PRs

---

docs/mkdocs.yml

✨ Update mkdocs.yml to add pr-signing doc to sidebar dropdown

---

docs/content/direct/troubleshooting.md
docs/content/direct/user-guide-intro.md
docs/mkdocs.yml

This PR introduces the start on a troubleshooting guide.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-troubleshooting/direct/troubleshooting/
Fixes #

📖 Start writing troubleshooting guide

---

pkg/binding/bindingpolicy-resolution.go
pkg/binding/bindingpolicy-resolver.go
pkg/binding/bindingpolicy.go
pkg/binding/selectors.go
test/e2e/ginkgo/multiple_cluster_deployment_test.go
test/util/util.go

This PR updates the binding controller to respect the create-only bit.
This is part of #2336

✨ Make the binding controller respect the create-only bit

---

pkg/transport/generic_transport_controller.go
pkg/transport/generic_transport_controller_test.go

This PR updates the generic transport controller to respect the create-only bit.
This implements part of #2336

✨ Support create-only in generic transport controller

---

scripts/create-kubestellar-demo-env.sh

 :seedling: 🌱 other/misc Added create-kubestellar-demo-env script + Update script based on suggestions

---

docs/content/direct/core-chart.md

Fix unhandled merge conflicts introduced by #2172 
Fixes #
#2351

📖 Fix merge conflicts introduced by previous PR

---

docs/content/direct/pr-signoff.md
docs/mkdocs.yml

This PR updates the document on PR signoff in two ways: (1) note that there are two cases, individual vs corporate contributor, and (2) note the difference between "sign-off" and "signing".
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-update-718/direct/pr-signoff/
Fixes #

📖 Brush up the doc on PR "signing"

---

README.md

This PR updates the README file at the root of the repo to include a pointer to the website.
Fixes #

✨ Add website reference to README

---

Makefile
docs/content/direct/packaging.md
scripts/deploy-transport-controller.sh
test/e2e/common/setup-kubestellar.sh

addressed minor comments written by @MikeSpreitzer in #2384.
Fixes #

🌱 addressed previous PR comments

---

pkg/status/singletonstatus.go

This PR fixes a bug in `func (c *Controller) reconcileSingletonByBdg`, which was not properly handling the case of a Binding that has been deleted.
Fixes #

🐛 Make reconcileSingletonByBdg handle deletion of Binding

---

pkg/status/binding.go
pkg/status/combinedstatus.go
pkg/status/controller.go
pkg/status/statuscollector.go
pkg/status/workstatus.go

This PR makes some debug logging improvements in the status controller.
Fixes #

🌱  Add debug logging around CombinedStatus resolution

---

pkg/status/binding.go
pkg/status/combinedstatus-resolver.go
pkg/status/statuscollector.go
pkg/util/log-wrappers.go

This PR adds a bit more debug logging in the status controller.
Fixes #

🌱  More debug logging

---

pkg/status/singletonstatus.go
pkg/status/workstatus.go

As shown in the title.
Also handles https://github.com/kubestellar/kubestellar/pull/2409#discussion_r1723976138.
Part of #2413

🐛 Add missing lister for cluster-scoped workload object when updating status

---

pkg/status/workstatus.go
pkg/util/authority.go

Getting hands on with the authority issue of downsynced object content #1851.

✨ Do not update statuses for namespaces in WDS

---

docs/content/direct/packaging.md

This PR updates the packaging document to account for the work already done on moving transport source from the ks/ocm-transport-plugin repo to the ks/ks repo.
Fixes #

📖 Update doc wrt OTP partial move already done

---

docs/content/direct/packaging.md

This PR makes one more update to packaging.md, tracking the work done months ago now to consolidate on a single quickstart recipe.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-getting-started-packaging/direct/packaging/

📖 Track 'Getting Started' changes into packaging.md

---

core-chart/templates/postcreatehooks/wds.yaml
core-chart/values.yaml

Add Helm chart control over bundling parameters
This PR depends on https://github.com/kubestellar/ocm-transport-plugin/pull/36
Fixes #2425

✨ Add Transport Controller Bundling parameters to the Helm chart

---

config/postcreate-hooks/kubestellar.yaml
core-chart/values.yaml
docs/content/direct/release-notes.md
docs/mkdocs.yml
oldocs/README.md

This PR updates the self-references in preparation for release 0.24.0.
Fixes #

✨ Update self-references for release 0.24.0

---

test/performance/README.md
test/performance/kshelper.py
test/performance/metrics_collector.py
test/performance/requirements.txt
test/performance/workloads/cluster-density-k8s/bindingPolicy.yaml
test/performance/workloads/cluster-density-ocp/bindingPolicy.yaml

This PR provides scripts to collect the creation & update timestamp for the KS sample workload. Using these values, we'll be able to compute the e2e latency to down sync objects from a WDS to WEC and identify any bottleneck latency.
Fixes #

✨ Collect the creation & update timestamps for KS sample workload 

---

api/control/v1alpha1/types.go
config/crd/bases/control.kubestellar.io_statuscollectors.yaml
pkg/crd/files/crds.yaml
pkg/status/combinedstatus-resolution.go
pkg/status/combinedstatus-resolver.go
pkg/status/workstatus.go
pkg/util/log-wrappers.go
test/e2e/ginkgo/multiple_cluster_deployment_test.go

This PR fixes the implementation of status combination to correctly handle the case of aggregation over zero rows.
Fixes #

🐛 Correct aggregation of zero rows

---

docs/content/direct/get-started.md

Reworded pages to page in the get-started documentation.

 📖 Updated grammar in docs get started

---

pkg/status/status-controller.go

🐛 Make WorkStatus event handlers check WDS name

---

.gitignore

This PR updates `.gitignore` to add local-only stuff associated with the new monitoring stuff from @dumb0002 .
Fixes #

✨ Add monitoring local stuff to .gitignore

---

VERSION
test/e2e/common/setup-kubestellar.sh

Streamline the `run_test --released` to actually test the latest released core-chart and controller images.
Fixes #

🐛 Fix `run_test --released`

---

config/postcreate-hooks/kubestellar.yaml
core-chart/values.yaml
docs/content/direct/release-notes.md
docs/mkdocs.yml

This PR updates the self-references in preparation for test release 0.24.0-alpha.1.test.1.
Fixes #

✨ Self-ref prep for test release 0.25.0-alpha.1.test.1

---

docs/content/direct/core-chart.md
docs/content/direct/pre-reqs.md

This PR updates the documentation of prerequisites to include `yq` where appropriate.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prereq-yq/direct/pre-reqs/ and https://mikespreitzer.github.io/kcp-edge-mc/doc-prereq-yq/direct/core-chart/#kubeconfig-files-and-contexts-for-control-planes .
Fixes #2475

📖 Document pre-req of yq

---

config/postcreate-hooks/kubestellar.yaml
core-chart/values.yaml
docs/content/direct/release-notes.md
docs/mkdocs.yml

This PR updates the self-references in preparation for test release 0.25.0-alpha.1.test.2.
Doc preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep-0250a1t2/direct/user-guide-intro/
Fixes #

✨ Self-ref prep for release 0.25.0-alpha.1.test.2

---

hack/check_pre_req.sh

Added installation suggestions.
Fixes #2245

:bug: Update check_pre_req.sh

---

test/e2e/common/setup-kubestellar.sh

This PR changes the script that does setup for E2E testing to align it with what the Getting Started instructions tell users, which is to use `scripts/create-kind-cluster-with-SSL-passthrough.sh` to create the hosting cluster and let the core Helm chart install KubeFlex in the hosting cluster; formerly the E2E test setup used `kflex init` and had the core Helm chart _not_ install KubeFlex in the hosting cluster. This change is good because we want to regularly test the recipe that we tell users to do.
This is also good because it moots #2491 . I am not saying this fully resolves #2491 , because we do not forbid users to use `kflex init` and we also have a dependency-checking script that does not check versions.

✨ Change E2E setup to let core chart install kubeflex in hosting cluster

---

docs/content/direct/troubleshooting.md

📖  Update to troubleshooting guide for issues with default settings in rancher desktop

---

docs/content/direct/get-started.md

I have tripped over this so many times - it is time to stop hiding it as a passing note.
Fixes #

🐛 Update get-started.md to include rename of context

---

pkg/transport/generic/generic_transport_controller.go
pkg/transport/generic/generic_transport_controller_test.go
pkg/transport/ocm-transport-controller/pkg/ocm.go
pkg/transport/transport.go
test/e2e/ginkgo/ginkgo_suite_test.go
test/e2e/ginkgo/multiple_cluster_deployment_test.go
test/util/util.go

This PR updates the OCM transport plugin to implement the expanded wrapping interface. And then cleans up the interface by removing the un-expanded wrapping method.
Fixes #2469 
Fixes #2332 
This is a hack that alleviates the most pressing need to properly address #1851 .

✨ Finish implementing expanded transport ifc, simplify

---

docs/content/direct/get-started.md

Add link to troubleshooting page
This PR is a doc update that mainly adds a missing link to the troubleshooting guide.
@KPRoche is the author of the changes here.
Preview at https://kproche.github.io/kubestellar/doc-linktrouble/direct/get-started/
Fixes #

📖 Update get-started.md

---

.github/spellcheck/.wordlist.txt
.github/workflows/spellcheck_action.yml
CODE_OF_CONDUCT.md
docs/content/Community/partners/turbonomic.md
docs/content/Contribution guidelines/operations/code-management.md
docs/content/direct/architecture.md
docs/content/direct/binding.md
docs/content/direct/combined-status.md
docs/content/direct/core-chart.md
docs/content/direct/galaxy-intro.md
docs/content/direct/knownissue-kind-config.md
docs/content/direct/pr-signoff.md
docs/content/direct/pre-reqs.md
docs/content/direct/release-notes.md
docs/content/direct/release.md
docs/content/direct/transforming.md
monitoring/README.md
test/e2e/ginkgo/README.md
test/e2e/performance/README.md
test/performance/README.md

Also some indentation fixes and quoting fixes.
This PR fixes some spelling misteaks, adds some missing words to the wordlist, and makes some fixes to indenting and quoting (so that the spell-checker will properly recognize quoted code blocks --- I hope).
Website preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-speling-1011/readme/
Fixes #

📖 Mostly spelling fixes

---

pkg/binding/selectors.go

This PR enhances a debug log message to include the name of the relevant Binding[Policy].
Fixes #

🌱 Add Binding[Policy] name to a debug log message

---

core-chart/values.yaml

We will use the new OSA release to see whether #2040 is resolved.
Fixes #

🌱 Update dependency of ocm status addon to release 0.2.0-rc13

---

scripts/create-kubestellar-demo-env.sh

✨ minor updates to script for formatting and verbiage

---

docs/content/direct/get-started.md
docs/content/direct/known-issues.md
docs/content/direct/knownissue-wsl-ghcr-helm.md
docs/mkdocs.yml

This PR updates the website to document the trouble and workaround reported in Issue #2544 . This is an alternative to PR #2519 .
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-wsl-fail/direct/knownissue-wsl-ghcr-helm/
and https://mikespreitzer.github.io/kcp-edge-mc/doc-wsl-fail/direct/get-started/#note-for-windows-users

📖  Document the WSL-helm-ghcr fail and workaround

---

scripts/create-kubestellar-demo-env.sh

This PR clarifies a progress message that confused me when I saw it go by.
Fixes #

🌱  Clarify progress message

---

core-chart/values.yaml
docs/content/direct/get-started.md
docs/content/direct/release.md
docs/content/direct/start-from-ocm.md
docs/mkdocs.yml

This PR updates the self-references in preparation for release 0.25.0-rc.2.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0250rc2/readme/
Fixes #

🌱  Update self-references for release 0.25.0-rc.2

---

ADOPTERS.md

✨ Create ADOPTERS.md

---

core-chart/templates/NOTES.txt

This PR makes a long-forgotten update to the NOTES.txt of the core Helm chart.
Fixes #

🌱  Do planned update since making a release

---

scripts/create-kubestellar-demo-env.sh

✨  increased timeout for job/its1 wait to 300s

---

docs/content/direct/combined-status.md

This PR extends the documentation of the combined status/reported-state feature with full API objects.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-combined-status-example/direct/combined-status/#number-of-wecs
Fixes #

📖  Fill out an example of combining status

---

api/control/v1alpha1/types.go
config/crd/bases/control.kubestellar.io_combinedstatuses.yaml
pkg/crd/files/crds.yaml
test/e2e/common/setup-kubestellar.sh

This PR fixes the definition of the BINDINGPOLICY printer column on CombinedStatus.
Fixes #2564

🐛  Fix the BINDINGPOLICY print column on CombinedStatus

---

core-chart/values.yaml
docs/content/direct/release.md
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for test release 0.25.0-rc.3.
Fixes #

🌱  Update self-references for release 0.25.0-rc.3

---

docs/content/direct/pre-reqs.md

This PR updates the documentation of the dependency checking script to note that it is suitable for curl-to-bash style usage.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-curl-to-bash-check-prereq/direct/pre-reqs/#automated-check-of-prerequisites-for-kubestellar
Fixes #

📖  Document curl-to-bash-ability of check_pre_req.sh

---

docs/content/direct/start-from-ocm.md

This PR updates the start-from-ocm doc to mention the general idea.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-update-1101b/direct/start-from-ocm/ .
Fixes #

📖  Note general idea in start-from-ocm

---

docs/content/direct/pre-reqs.md

This PR updates the prerequisites doc to mention that you will need ginkgo if running the ginkgo based test.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-need-ginkgo/direct/pre-reqs/#additional-software-for-building-kubestellar-from-source-and-testing
Fixes #

📖  Document the need for ginkgo in testing

---

core-chart/values.yaml
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for release 0.25.0.
Fixes #

✨  Update self references for release 0.25.0

---

docs/content/direct/get-started.md

Modified get-started.md documentation to include  possibility of using quick automated script.
You should be able to see modifications [here directly](https://katamyra.github.io/kubestellar/doc-krish2/direct/get-started/)

📖 Adding documentation for quick automated script

---

docs/content/direct/example-scenarios.md

This PR revises the example scenarios document to take the prompts out of some commands that readers will try to copy-and-paste.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-no-dollar/direct/example-scenarios/#optional-propagate-helm-metadata-secret-to-managed-clusters
Fixes #2559

📖  Remove dollar signs from commands to copy-and-paste

---

scripts/create-kubestellar-demo-env.sh

This PR removes a TODO note that was overlooked when the task was done.
Fixes #

🌱  Remove TODO that has been done

---

docs/overrides/home.html

✨ added link to footer of webpage for trademarks

---

README.md
docs/content/direct/roadmap.md
docs/mkdocs.yml

required for us to get a higher percentage grade at https://clomonitor.io/projects/cncf/kubestellar
Fixes #

✨ add Roadmap placeholder

---

pkg/abstract/primitive-map-ops.go
pkg/transport/generic/generic_transport_controller.go
pkg/transport/generic/generic_transport_controller_test.go
pkg/transport/ocm-transport-controller/pkg/ocm.go
pkg/transport/transport.go
pkg/util/gvk-obj-ref.go
test/e2e/ginkgo/multiple_cluster_deployment_test.go

This PR changes the way that the transport controller decides what changes it has to make in wrapped objects. The old code was not logical.
Fixes #2586 
Fixes #2511

🐛  Revise generic transport controller update logic

---

README.md

✨ update trademark link in readme

---

README.md

✨ openssf badge needed for clomonitor rating increase

---

core-chart/values.yaml
docs/content/direct/release-notes.md
docs/content/direct/release.md
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR does the self-reference updates in preparation for release 0.25.1.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0251/readme/
Fixes #

✨  Prepare for 0.25.1 release

---

README.md

✨ artifact-hub badge needed for clomonitor rating - root readme.md

---

docs/content/readme.md

preview at https://clubanderson.github.io/kubestellar/artifact-hub-part2/readme/
Fixes #

✨ Artifact-hub now added to doc readme - with preview

---

SECURITY-INSIGHTS.yml
THREAT-MODEL.md

✨ added support for OpenSSF security insights

---

README.md

✨ added support for OpenSSF scorecard for clomonitor scoring

---

hack/check_pre_req.sh

setting up for next step to use this in the create-demo-env as an option to use k3d instead of kind, which will then be used to load the Kueue demo env
needed for community promotion/education/adoption
Fixes #

✨ add optional check for k3d

---

core-chart/values.yaml
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for release 0.26.0-alpha.1.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0260a1/readme/
Fixes #

✨  Update self-references for 0.26.0-alpha.1

---

docs/content/direct/get-started.md
hack/check_pre_req.sh
scripts/create-kubestellar-demo-env.sh

✨ add option to create kubestellar on k3d

---

.github/ISSUE_TEMPLATE/bug_report.yaml
docs/content/direct/troubleshooting.md

This PR improves bug-reporting clues in two places. One is the GitHub template for a bug-report style of Issue. The other is the "Making a good trouble report" section of the Troubleshooting page of the website.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-report-more/direct/troubleshooting/#making-a-good-trouble-report
Fixes #

📖  Improve bug reporting clues

---

docs/content/direct/get-started.md
docs/content/direct/release.md
scripts/create-kubestellar-demo-env.sh

✨ updated to use links in repo, not in my fork

---

scripts/create-kubestellar-demo-env.sh

✨ updated to add --assert to the command for check_pre_req.sh

---

scripts/kubestellar-snapshot.sh

This PR extends the snapshot script to dump the Binding objects too.
Fixes #

✨  Add Binding objects to snapshot output

---

core-chart/values.yaml
docs/content/direct/get-started.md
docs/content/direct/release-notes.md
docs/content/direct/release.md
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for release 0.26.0-alpha.2
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0260a2/readme/
Fixes #

✨  Update self-references for 0.26.0-alpha.2 release

---

scripts/kubestellar-snapshot.sh

Fix ITS detection based on the new core-chart
Fixes #

🐛 Fix ITS detection based on the new core-chart

---

scripts/kubestellar-snapshot.sh

This PR extends the kubestellar-snapshot script to report the versions of the ocm-status-addon and of the OCM manager.
Fixes #

✨  Add OSA and OCM versions to snapshot script

---

ADOPTERS.md

Added Cornell University to the list of kubestellar adopters, though I had to take the scenic route on signing commits 😁 Wrt to gpg, I also wanted to share a [Stackoverflow fix](https://stackoverflow.com/questions/39494631/gpg-failed-to-sign-the-data-fatal-failed-to-write-commit-object-git-2-10-0) on how to deal with gpg signing errors (if installed using brew on macOS) in case it may be of use to other first-time committers to the repo.
Fixes #

:book: Adding Cornell to the list of KubeStellar adopters.

---

.github/workflows/goreleaser.yml
.goreleaser.yaml

Skips uploading binaries during release.
Fixes #2653

✨ skip uploading binaries during release

---

scripts/create-kind-cluster-with-SSL-passthrough.sh

Found typo and corrected it
Fixes #2706

🐛  Update create-kind-cluster-with-SSL-passthrough.sh

---

scripts/ocm-local-up-for-ingress.sh

:bug: Update ocm-local-up-for-ingress.sh

---

core-chart/values.yaml
docs/content/direct/release-notes.md
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for the next alpha release.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0260a4/readme/
Fixes #

📖  Update self-references for release 0.26.0-alpha.4

---

scripts/kubestellar-snapshot.sh

This PR updates the snapshot script to cope with both the old and new container names in the ITS initialization Job.
Fixes #2720

🐛  Accept whatever container names exist in ITS initialization Pod

---

docs/content/direct/teardown.md
docs/content/direct/user-guide-intro.md
docs/mkdocs.yml

This PR introduces a document describing how to teardown a KubeStellar system.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-teardown/direct/teardown/
Fixes #

📖  Document teardown procedure

---

.github/workflows/goreleaser.yml
.goreleaser.yaml

Added sbom generation within go-releaser itself.
Fixes #2613

✨CI: Added sbom generation in goreleaser

---

.github/workflows/add-contributors.yml
README.md

As per @clubanderson comment - https://github.com/kubestellar/ui/pull/19#issuecomment-2604920732
Fixes #

:sparkles: add contributor to readme.md file

---

pkg/status/binding.go
pkg/status/combinedstatus-resolver.go

As shown in the title.
This PR is created as a response to https://github.com/kubestellar/kubestellar/pull/2643#discussion_r1920986572.

📖 Update go doc comment for MissingStatusCollectors

---

core-chart/values.yaml
docs/content/direct/release-notes.md
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for test release 0.26.0-alpha.5.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0260a5/readme/
Fixes #

✨  Update self-references in preparation for 0.26.0-alpha.5

---

docs/content/Community/_index.md

fix: correct Contribution Guidelines link
Fixes #

📖 Update _index.md

---

docs/overrides/home.html

fix: remove / from link
Fixes #

📖 Update home.html

---

scripts/create-kubestellar-demo-env.sh

This PR removes the concurrency from the demo env creation script, because of mysterious and non-mysterious failures that appear to be associated with that concurrency.
Might resolve #2700, #2701, #2702, #2715, #2716, #2725, #2726.
Will not resolve #2717 .
#2765 resolved #2579 on MacOS but not Linux hosts nor Linux under WSL on Windows.

🐛  Remove concurrency from create-kubestellar-demo-env.sh

---

scripts/create-kind-cluster-with-SSL-passthrough.sh

This PR pins the version of the nginx ingress controller used, so that the fixed patch to its arguments is safe.
Fixes #2772

🐛  Pin the version of ingress-nginx

---

docs/content/direct/troubleshooting.md

This PR updates the Troubleshooting page to add a description of using the snapshot script.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-snapshot/direct/troubleshooting/#use-the-snapshot-script
Fixes #

🌱  Add snapshot script to Troubleshooting page

---

scripts/create-kind-cluster-with-SSL-passthrough.sh

This PR updates `scripts/create-kind-cluster-with-SSL-passthrough.sh` so that it no longer assumes that the first controller Pod that it sees is the one corresponding to the patched version of the controller Deployment.
Fixes #2788

🐛  Wait for the right version of the ingress controller Pod

---

scripts/kubestellar-snapshot.sh

- move the creation of the tar file to a trap function to make sure that it is saved even on error
- do not exit after missing postgresql error
- check the presence/absence of KubeFlex, KubeStellar, and OCM CRDs
- #2786: do not exit after missing postgresql error
Fixes #2783

✨ Improve the snapshot script

---

scripts/kubestellar-snapshot.sh

Further protect the logs commands in the snapshot script to prevent potential crashes.
Fixes #

🐛  Further protect the logs commands in the snapshot script

---

.github/workflows/goreleaser.yml

🐛 :Fixing create SBOM functionality

---

docs/content/direct/pre-reqs.md
hack/check_pre_req.sh
scripts/check_pre_req.sh

This PR enhances the check_pre_req.sh script to check whether `helm show chart oci://ghcr.io/kubestellar/kubestellar/core-chart` succeeds. This is good because helm is unusable when that fails but nothing gives the user a clear clue about this.
Fixes #

✨  Check helm health in preflight

---

core-chart/values.yaml
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for the next test release, 0.26.0-rc.2
Fixes #

✨  Update self-references in preparation for 0.26.0-rc.2

---

core-chart/values.yaml
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for release 0.26.0
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0260/readme/
Fixes #

✨  Update self-references for release 0.26.0

---

docs/content/direct/transforming.md

This PR adds the doc part of #2805 to the release-0.26.0 branch.

📖 Backport doc updates to release-0.26.0

---

LICENSE
README.md
core-chart/LICENSE
docs/overrides/home.html

🌱 Update year for copyright and license

---

docs/content/direct/core-chart.md

This PR fixes a missing single quote in the --set-json flag example at line 234 of core-chart.md.
Fixes #2822

:bug: fix: add missing quote in core-chart.md example

---

core-chart/values.yaml
docs/content/direct/release-notes.md
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for test release 0.27.0-rc.1
Fixes #

✨  Update self-references for release 0.27.0-rc.1

---

scripts/create-kubestellar-demo-env.sh

This PR removes another pull from DockerHub, continuing to address #2786 .
One more remains, in example scenario 3. I think that is OK.
Fixes #

🐛 Remove another pull from DockerHub

---

scripts/create-kubestellar-demo-env.sh

This PR updates the demo environment creation script to also make KubeFlex debuggable.
This might help diagnose Issue #2717 .

✨  Make kubeflex debuggable too in demo env

---

core-chart/values.yaml
docs/mkdocs.yml
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references in preparation for release 0.27.0.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0270/readme/
Fixes #

✨  Update self-references for release 0.27.0

---

docs/content/Community/kubecon/eu2025/contribfest.md

Add Helm issues to the KubeCon-EU-2025 page
Fixes #

📖 KubeCon-EU-2025 add Helm issues

---

docs/content/direct/acquire-hosting-cluster.md
scripts/create-kubestellar-demo-env.sh
scripts/ocm-local-up-for-ingress.sh

This PR updates the version for ingress-nginx in the remaining places where it appears, to finish avoiding the recently disclosed vulnerabilities in ingress-nginx.
Fixes #

🐛  Update version of ingress-nginx in remaining places

---

docs/content/direct/pre-reqs.md

This PR fixes some botches in the pre-reqs website page regarding Helm.
Website preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-rel0271-fix-helm-doc/direct/pre-reqs/#software-prerequisites-for-using-kubestellar
Fixes #

📖  [release-0.27.1] Fix the pre-reqs.md remark about Helm

---

scripts/kubestellar-snapshot.sh

Fix `kubectsllear-snapshot.sh` errors related to JQ parsing of incomplete YAML during KubeStellar bring up.
Here is an example of the error being fixed:
```text
Control Planes:
- its1: type=vcluster, pch=its-with-clusteradm, context=kind-kubeflex, namespace=its1-system
WARNING: the Control Plane is not ready, the kubeconfig is not available!
- Post Create Hook: pod=, ns=its1-system, status=
- Status addon controller: pod=, ns=its1-system, version=, status=
- wds1: type=k8s, pch=wds, context=kind-kubeflex, namespace=wds1-system
WARNING: the Control Plane is not ready, the kubeconfig is not available!
jq: error (at <stdin>:8): Cannot iterate over null (null)
- KubeStellar controller manager: version=, pod= namespace=wds1-system, status=
jq: error (at <stdin>:8): Cannot iterate over null …
```

🐛 Fix kubectsllear-snapshot errors related to JQ parsing

---

docs/content/direct/known-issues.md
docs/content/direct/knownissue-cpu-insufficient-for-its1.md

As mentioned in the following [comment](https://github.com/kubestellar/kubestellar/issues/2782#issuecomment-2849492969), the given fix is now part of the known issues documentation.
Fixes #https://github.com/kubestellar/kubestellar/issues/2782

📖  add new known issue markdown

---

docs/content/direct/installation-errors.md
docs/content/direct/known-issues.md
docs/content/direct/knownissue-cpu-insufficient-for-its1.md
docs/mkdocs.yml

This PR adjusts the recent known issues about CPU and host filesystem config for docker-in-docker techniques, and fixes up the pointers to them.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-cpu-issue/direct/known-issues/
Fixes #2782
Fixes #2777 
This PR includes some fixing that is part Issue #2825 .

📖  Adjust recent known issues and fill out indexing

---

.github/workflows/verify.yml

The current `pr-verifier.yaml` workflow is vulnerable to command injection when processing PR titles. Unescaped characters or injected commands can be executed in the shell during the GitHub Actions run.
- Secure the PR title handling by escaping characters properly using `printf %q`.
- Prevent command injection by avoiding direct evaluation of untrusted input in the shell.
- Add `set -euo pipefail` for shell safety.
- Updated `pr-verifier.yaml` to:
- Add safe shell practices.
- Properly handle and escape PR title.
- Ensure the PR title is validated securely without running injected commands.
This change prevents arbitrary command execution via PR titles, improving the security of the GitHub Actions workflow.
Please review the changes and merge if acceptable. Let me know if any further …

🌱  Test :  Fix command injection vulnerability in PR title validation

---

README.md

This PR makes an insignificant change, as fodder for testing Prow.
Fixes #

:bug: title from cli

---

README.md

Another insignificant change, for testing Tide.
Fixes #

🌱  Prow test 7

---

README.md

This PR makes another insignificant change, as fodder for testing Prow.
Fixes #

🌱  Another insignificant change, for Prow testing

---

core-chart/values.yaml
docs/content/direct/release-notes.md
docs/mkdocs.yml
scripts/check_pre_req.sh
scripts/create-kubestellar-demo-env.sh

This PR updates the self-references for test release 0.28.0-alpha.2.
Fixes #

✨  Update self-references for release 0.28.0-alpha.2

---

.gha-reversemap.yml
.github/workflows/spellcheck_action.yml

This is the principled version of #2936 .
Fixes #

🌱  Bump rojopolis/spellcheck-github-actions from 0.48.0 to 0.49.0

---

scripts/create-kind-cluster-with-SSL-passthrough.sh

🐛fix typo for prefetch_pids[i] 

---

.gha-reversemap.yml
.github/workflows/spellcheck_action.yml

This is the principled version of #2989 
Fixes #

🌱  Bump rojopolis/spellcheck-github-actions from 0.50.0 to 0.51.0

---

docs/content/direct/observability.md
docs/content/direct/user-guide-intro.md
docs/mkdocs.yml

📖  improve user guide and add observability page 

---

.github/ISSUE_TEMPLATE/bug_report.yaml
.github/ISSUE_TEMPLATE/doc_issue.yaml
.github/ISSUE_TEMPLATE/feature_request.yaml
.github/pull_request_template.md

This PR updates the PR and Issue templates in a few ways.
- Be more explicit and clear about the leading icon, coding, and meaning.
- Say to look for overlapping ones before creating a new one.
- Request a preview of website updates.
Fixes #

📖  Update the PR and Issue templates

---

docs/overrides/stylesheets/kubestellar.css

* Added dark/light mode toggle now feels smooth and responsive, with minimal code changes and maximum compatibility.
* Added a single CSS rule to apply a smooth background-color and color transition to all elements.
Preview at https://arpit529srivastava.github.io/kubestellar/doc-issue2742/direct/get-started/
Fixes #2742

📖 add smooth transitions for elements and theme toggle button

---

.github/workflows/pr-verifier.yaml

This PR updates the PR title checking workflow, to print diagnostic information in case of failure.
Fixes #

🌱  Add diagnostic to PR title failure

---

.gha-reversemap.yml
.github/workflows/greetings.yml

This PR bumps actions/first-interaction to version 2.0.0.
This is the principled version of #3086
Fixes #

🌱  Bump com/actions/first-interaction to version 2.0.0

---

docs/content/direct/wec-registration.md

This PR enhances the WEC registration documentation by incorporating all feedback provided in the review of PR #2997.
- ✅ Mapped OCM terminology with references to official documentation  
- ✅ Corrected typo in the introduction (“what how to register” → “how to register”)  
- ✅ Improved explanation of verification commands  
- ✅ Reduced duplication across Kind, K3d, and OpenShift sections  
- ✅ Added clear cleanup instructions for both agent namespaces  
- ✅ Clarified labeling examples as illustrative only  
- ✅ Included detailed troubleshooting and management sections  
- ✅ Refined structure and overall readability for better comprehension
Preview → https://rishi-jat.github.io/kubestellar/doc-wec-registration/direct/wec-registration/
Addresses feedback from PR #2997 by @MikeSpreitzer

📖 revise WEC registration based on feedback from #2997 

---

scripts/create-kind-cluster-with-SSL-passthrough.sh

🌱more refined logic for kind cluster creation with ssl-passthrough

---

docs/content/direct/wds.md

Before making this PR, I liaised with @rishi-jat. We can guarantee that this PR solely enhances the WDS documentation while simultaneously preventing any overlaps or duplication of efforts in other PRs, as mentioned in #3023 and #2993. 
Fixes #3000 and addresses feedback from PR #3023 by @MikeSpreitzer
Preview → https://tob-iee.github.io/kubestellar/doc-fix-wds/direct/wds/

📖 improve WDS page based on feedback from #3023

---

docs/content/direct/wds.md

This PR makes more improvements in the website page about WDSes.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-wds-more/direct/wds/
This PR continues work on Issue #3000

📖  Fix up WDS doc page

---

GOVERNANCE.md
docs/content/direct/core-chart.md
docs/content/direct/known-issues.md
docs/content/direct/wec-registration.md

This PR fixes multiple broken links in the docs that are discovered by running [Broken Links Crawler](https://github.com/kubestellar/kubestellar/actions/workflows/broken-links-crawler.yml)  workflow.
Preview: https://greninja517.github.io/kubestellar/doc-fix-broken-links/
Still there is another broken link at https://greninja517.github.io/kubestellar/doc-fix-broken-links/direct/get-started/#note-for-windows-users that is referencing to a file `docs/content/direct/knownissue-wsl-ghcr-helm.md` introduced by this [PR](https://github.com/kubestellar/kubestellar/pull/2548/) which is non-existent now. That file must have been renamed to `docs/content/direct/knownissue-helm-ghcr.md` but the content inside this new file is not related to WSL users rather it's generic. 
So, I thought it's better …

📖 Fix multiple broken links in docs discovered via crawler

---

.gha-reversemap.yml
.github/workflows/goreleaser.yml

This PR bumps anchore/sbom-action/download-syft to v0.20.4. This is the principled version of #3117 .
Fixes #

🌱  Bump anchore/sbom-action/download-syft to v0.20.4

---

docs/content/contribution-guidelines/operations/docs-styleguide.md

Preview: https://kproche.github.io/kubestellar/doc-updatestyleGPT/contribution-guidelines/operations/docs-styleguide/
Adds to the paragraph with cautions about use of generative AI:
- adds the concern about derivative works, 
- reworded to clarify that there may be additional problems with prose created with generative AI tools.
Fixes #3161

📖 update generative AI paragraph in initial style guide

---

core-chart/values.yaml
monitoring/README.md

This PR bumps the ks/OSA dependency to 0.2.0-rc16, to pick up recent security fixes.
Fixes #

🌱 Bump kubestellar/ocm-status-addon to 0.2.0-rc16

---

core-chart/values.yaml
docs/content/direct/release.md
docs/mkdocs.yml
scripts/check_pre_req.sh
scripts/create-kubestellar-demo-env.sh

Update self-references in preparation for 0.29.0-alpha.1 .
This goes hand-in-hand with #3169 .
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0290a1/readme/
Fixes #

✨ Update self-references in preparation for 0.29.0-alpha.1

---

docs/content/contribution-guidelines/contributing-inc.md

added double-space at end of each line to make this read better. also removed language on asking maintainer to assign someone.
Fixes #

✨ Update contributing-inc.md

---

scripts/create-kubestellar-demo-env.sh

This PR enhances the `Kubeflex cluster creation with K3d` wait logic by replacing `sleep` with `kubectl wait`, improving reliability and efficiency of script. 
Fixes #

🌱 Refactor: Enhance K3d cluster creation wait to use kubectl wait instead of sleep for more reliability

---

.gha-reversemap.yml
.github/workflows/goreleaser.yml

This PR bumps anchore/sbom-action/download-syft to 0.20.5, including the update to the database of approved Action versions.
Fixes #

🌱 Bump anchore/sbom-action/download-syft to 0.20.5

---

.gha-reversemap.yml
.github/workflows/greetings.yml

This PR bumps actions/first-interactions from 2.0.0 to 3.0.0, including updating the database of approved Action versions.
Fixes #

🌱 Bump actions/first-interactions from 2 to 3.0.0

---

.gha-reversemap.yml
.github/workflows/goreleaser.yml

This PR bumps goreleaser/goreleaser-action from 6.3.0 to 6.4.0 .
This is the principled version of #3240 
Fixes #

🌱 Bump goreleaser/goreleaser-action from 6.3.0 to 6.4.0

---

.prow.yaml
Makefile
test/e2e/ci/test-demo-env.sh

This PR creates a new `prowjob` that automatically tests the `/scripts/create-kubestellar-demo-env.sh` script for both platform `kind|k3d` on every pull request that change this `/scripts/create-kubestellar-demo-env.sh` script. This will ensure that any changes made to `demo-env` script won't break it.
Fixes #3176

✨ Add prowjob to test the kubestellar-demo-env script

---

README.md

✨added deepwiki badge in the readme
