kubestellar/kubestellar

README.md
No matter which convention we use, at least there should be a full stop at the end of a list.
Fixes #23
=> :book: Improve punctuation for list items in README

README.md
This patch fixes the `availabke` typo and replace it with `available`.
Fixes #
=> 📖 fix typo in README.md

cmd/placement/main.go, pkg/indexers/indexers.go, pkg/reconciler/scheduling/placement/controller.go
reverted order of imports in indexers.go, main.go, and controller.go
reverted order of imports in indexers.go, main.go, and controller.go
Fixes #
=> :bug: reverted order of imports in indexers.go, main.go, and controller.go

hack/verify-contextual-logging.sh
This PR makes the `hack/verify-contextual-logging.sh` script `set -x`, to:
- debug where complaints are coming from, and
- cause a repeat of the checking, to see whether the current contents of the `main` branch pass the current checking.
Fixes #
=> 🌱 Make log checking script echo commands, to debug

Makefile
This PR updates the Makefile so that CI uses the latest release of logcheck, picking up the fix to the bug that bit #67 
Fixes #
=> 🌱 Use latest release of logcheck

Makefile, cmd/placement/cmd/placement.go, pkg/indexers/indexers.go, pkg/reconciler/scheduling/placement/controller.go, pkg/reconciler/scheduling/placement/indexes.go, pkg/reconciler/scheduling/placement/reconcile.go, pkg/reconciler/scheduling/placement/reconcile_namespace.go, pkg/reconciler/scheduling/placement/reconcile_placement.go
Make everything under kcp-dev sort together in the last block of imports.
Because openshift-goimports is rather opinionated and does not have a way to separate kcp-dev/kcp from kcp-dev/edge-mc with both coming after kubernetes.
Actually invoked `make imports` --- whose effects have not appeared in earlier PRs and whose effects will appear in future PRs that include the effects of `make codegen`.
Fixes #
=> 🌱 Improve and use `make imports`

Makefile, cmd/placement/cmd/placement.go, pkg/client/clientset/versioned/cluster/clientset.go, pkg/client/clientset/versioned/cluster/fake/clientset.go, pkg/client/clientset/versioned/cluster/typed/edge/v1alpha1/edge_client.go, pkg/client/clientset/versioned/cluster/typed/edge/v1alpha1/edgeplacement.go, pkg/client/clientset/versioned/cluster/typed/edge/v1alpha1/fake/edge_client.go, pkg/client/clientset/versioned/cluster/typed/edge/v1alpha1/fake/edgeplacement.go, pkg/client/clientset/versioned/cluster/typed/edge/v1alpha1/fake/singleplacementslice.go, pkg/client/clientset/versioned/cluster/typed/edge/v1alpha1/singleplacementslice.go, pkg/client/informers/externalversions/edge/v1alpha1/edgeplacement.go, pkg/client/informers/externalversions/edge/v1alpha1/singleplacementslice.go, pkg/client/informers/externalversions/factory.go, pkg/client/informers/externalversions/generic.go, pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go, pkg/client/listers/edge/v1alpha1/edgeplacement.go, pkg/client/listers/edge/v1alpha1/singleplacementslice.go, pkg/indexers/indexers.go, pkg/reconciler/scheduling/placement/controller.go
This PR switches to using the latest version of https://github.com/openshift-eng/openshift-goimports --- which can support import groups between openshift and the module being organized --- and grouping the non-edge kcp imports together before the edge-mc imports.
Fixes #
=> 🌱 Separate edge-mc imports from other kcp-dev imports

docs/poc2023q1/mailbox-controller.md
This PR corrects the documentation of how the mailbox controller constructs the name of mailbox workspaces
Fixes #153
=> :book: Corrected doc on mailbox workspace name

cmd/mailbox-controller/main.go
This PR moves the comment on imports in the mailbox controller to someplace that openshift-goimports does not mess with, to avoid https://github.com/openshift-eng/openshift-goimports/issues/16 .
Fixes #
=> 🌱 Work around comment drifting in openshift-goimports

go.mod
This PR makes all the k8s.io imports be at v0.24.3, since that is what kcp-dev/kcp's go.mod says.  Note that the later replace statements, which are not changed here, are what really determine the version used.
This PR also does `go mod tidy`, which causes proper treament of github.com/evanphx/json-patch.
Fixes #
=> 🌱 Some tidying of go.mod

config/crds/edge.kcp.io_edgeplacements.yaml, config/crds/edge.kcp.io_singleplacementslices.yaml, config/exports/apiexport-edge.kcp.io.yaml, config/exports/apiresourceschema-edgeplacements.edge.kcp.io.yaml, config/exports/apiresourceschema-singleplacementslices.edge.kcp.io.yaml, pkg/apis/edge/v1alpha1/edge-placement.go, pkg/apis/edge/v1alpha1/single-placement.go
This PR saves a few keystrokes when we use kubectl, e.g. `get singleplacementslices` -> `get sps`.
Short name `ep` is taken by kube endpoints, so using `epl` for edgeplacements.
=> ✨ Short names for edgeplacements and singleplacementslices

cmd/placement-translator/main.go, hack/logcheck.out, pkg/placement/client-tracker.go, pkg/placement/cluster-name-and-path.go, pkg/placement/declarations.go, pkg/placement/dummies.go, pkg/placement/external-name.go, pkg/placement/main.go, pkg/placement/map-types.go, pkg/placement/reducer_test.go, pkg/placement/relay-map.go, pkg/placement/set-binder-test.go, pkg/placement/simple-reducer.go, pkg/placement/single-placement-set.go, pkg/placement/test-apimap-provider.go, pkg/placement/test_uider.go, pkg/placement/test_uider_test.go
This PR is the first draft of the internal interfaces among the parts of the placement translator process of the 2023q1 PoC.
This draft assumes that #155 will be resolved by switching to using the SyncTarget UID instead of its name in the construction of the mailbox workspace name.
Fixes #
=> ✨ Start drafting placement translator internal interfaces

docs/content/en/docs/Coding Milestones/PoC2023q1/outline.md
This PR documents the roadmap thoughts, such as they are at the moment, for the 2023q1 PoC.
This PR also removes one exclusion that we decided we no longer like: "Support for workload object types that are not either built into kcp or imported via a kcp APIBinding".
Fixes #
=> 📖 Document the roadmap thoughts, as they are now.

docs/content/en/docs/Coding Milestones/PoC2023q1/placement-translator.md
This PR attempts to fix the reference from placement-translator.md to example1.md, in a way that works after it runs through the conversion to github pages.
Fixes #
=> 🐛 Attempt to fix broken reference to example1

docs/content/en/docs/Coding Milestones/PoC2023q1/outline.md
This PR updates the 2023q1 PoC outline to be more correct and expansive regarding APIBinding objects and also expand options in the roadmap section.
This includes calling out a scenario in which workload objects in mailbox workspaces (as well as all other workspaces) are visible in an APIExport view.
This PR replaces #238 with a more extensive revision.
Fixes #
=> ✨ Update thoughts on APIBindings and roadmap options

pkg/mailboxwatch/interface.go
This PR introduces an API for staying informed of objects in mailbox workspaces.
Fixes #
=> ✨ First draft of API for reading objects from mailbox workspaces

cmd/scheduler/cmd/scheduler.go, cmd/scheduler/options/options.go, docs/content/en/docs/Coding Milestones/PoC2023q1/edge-scheduler.md
This PR handles #270. Now the scheduler doesn't need an explicit `kcp-kubeconfig` flag, as long as (and already documented) environment variable `$KUBECONFIG` is pointed to the kcp server.
This PR also cleans up some legacy code in response to @MikeSpreitzer 's previous review (Thanks!), for example, the scheduler doesn't really need kubeSharedInformerFactory and related stuff.
Closes #270.
=> ✨ Tweak `kcp-kubeconfig` flag for the scheduler

docs/content/en/docs/Coding Milestones/PoC2023q1/roadmap-uses.md
This PR fixes the `linkTitle` for the roadmap doc.
It currently is "Details", the same as in outline.md.
Fixes #
=> 📖 Fix link title for roadmap doc

cmd/scheduler/cmd/scheduler.go, cmd/scheduler/options/options.go, pkg/client/options.go, pkg/scheduler/reconcile_on_location.go, pkg/scheduler/reconcile_on_synctarget.go
This PR
- puts (and tweaks) code for preparing client options into pkg (as suggested [here](https://github.com/kcp-dev/edge-mc/pull/271#issuecomment-1487603900), thanks to @MikeSpreitzer ) so that controllers can share them;
- use that part of code to allow more configurable flags for the scheduler @dumb0002 .
This PR also improves the English language in logs, thanks to @KPRoche the native speaker.
=> ✨ Make client options code in pkg and let the scheduler use it

cmd/mailbox-controller/controller.go, cmd/mailbox-controller/main.go, docs/content/en/docs/Coding Milestones/PoC2023q1/mailbox-controller.md
This PR adds missing functionality to the mailbox controller: creating an APIBinding in each mailbox workspace that binds to the edge API.
For now, this controller will tolerate other parties modifying the spec of this binding, in case we need to override what the controller says.  Probably we eventually want the controller to undo any conflicting changes to the spec.
Fixes #
/cc @yana1205 
@yuji-watanabe-jp 
@dumb0002
=> ✨ Make mailbox controller create APIBinding for edge

cmd/mailbox-controller/main.go, docs/content/en/docs/Coding Milestones/PoC2023q1/mailbox-controller.md
This PR fixes an oversight in the previous mailbox controller PR (#298), in which I forgot to make the calls to register the client options in the command line flag set.
This PR also updates the documentation to be consistent with the code.
Fixes #
=> 🐛 Make mailbox controller register its client config flags, and document

pkg/mailboxwatch/listwatch.go
This PR expands the comment on TypedContextualListWatcher and fixes a typo.
The expansion provides an example of how to usefully instantiate that generic type.
Fixes #
/cc @yana1205 
/cc @waltforme
=> 📖 Fix typo, expand comment on TypedContextualListWatcher

pkg/placement/what-resolver.go
This PR fixes a bug that will cause the placement translator to crash IFF an EdgePlacement has a NonNamespacedObjectReferenceSet with exactly one entry in its ResourceNames.
Fixes #
/cc @yana1205 
/cc @waltforme
=> 🐛 Fix typo

pkg/syncer/controller/syncerconfigcontroller_test.go, pkg/syncer/controller/syncerconfigmanager.go, pkg/syncer/syncer.go, pkg/syncer/syncers/upsyncer.go
https://github.com/kcp-dev/edge-mc/blob/main/pkg/apis/edge/v1alpha1/edge-placement.go#L136
```
// `namespaces` is a list of acceptable namespaces.
// An entry of `"*"` means that all match.
// Empty list means nothing matches (you probably do not want this
// for namespaced resources).
Namespaces []string `json:"namespaces,omitempty"`
```
UpsyncSet allows wildcard in `namespaces` field. I added its support. 
Fixes #
=> 🐛 Fix to support the case for namespace to be wildcard in upsync

pkg/placement/declarations.go, pkg/placement/main.go, pkg/placement/workload-projector.go
This PR fixes a bug in the placement translator.  It was including APIBinding objects among those to downsync in SyncerConfig objects.
Fixes #
/cc @yana1205 
/cc @dumb0002 
/cc @waltforme
=> 🐛 Do not ask syncer to downsync resources that do not go

docs/content/en/docs/Coding Milestones/PoC2023q1/placement-translator.md
This PR documents the exclusion of Namespace objects from those that the placement translator might delete in a mailbox workspace.
Fixes #
/cc @waltforme
=> 📖 Document non-deletion of Namespace objects

pkg/placement/what-resolver.go, pkg/placement/workload-projector.go
This PR tries to avoid a mysterious condition sometimes seen where an object returned from a Get-ish function along with an error appears to be non-nil and yet consequent calls cause a nil pointer fault inside the `unstructured` package.
Fixes #
=> 🐛 More cover for IsNotFound(err) and mystery nil

docs/content/en/docs/Coding Milestones/PoC2023q1/outline.md
This PR refreshes the 2023 PoC outline, primarily to remove the idea of using the TMC syncer.
Fixes #
=> 📖 Update outlline of 2023q1 PoC

Makefile
This PR extends the behavior of `make build` to ensure that `bin` has a copy of the scripts from `scripts`.  This means that a user will need only the contents of the `bin` directory.
Fixes #
=> ✨ Have `make build` copy scripts to bin

cmd/emc-customize/main.go, go.mod, go.sum, pkg/customize/customize.go, pkg/jsonpath/jsonpath.go
This PR begins the implementation of customization.  The customization is not yet implemented in the placement translator, but this PR introduces a CLI for exercising the prescribed customization.  The command is "emc-customize".
In this first draft, we do not have a full implementation of JSONPath for use in a Customizer's Replacements.  For now the syntax and semantics of a Replacement's Path are what is implemented in https://github.com/tidwall/sjson - with one nod toward JSONPath.  The Replacement's Path must start with "$.", and this is stripped off and the remainder of the path is handled by sjson.
I have exercised this and it is able to do the customization needed for the current MVI usage.
Fixes #
/cc @waltforme
=> ✨ First draft of customization command

hack/make-release-container.sh, hack/make-release-full.sh, hack/make-release-platform-archive.sh
this utility build the go container for syncer and deposits is in the quay.io registry for kcpedge/syncer.  Also, removing syncer from make-release-platform-achrive.sh since it is covered by make-release-container.sh
Fixes #
=> first commit of script to build container for specified version

Makefile
The fixes a misunderstanding in the Makefile.
Why is `bin` handled differently than `build`?
Fixes #
=> 🐛 Do not assume the build directory exists

docs/content/en/docs/Coding Milestones/PoC2023q1/example1.md, docs/content/en/docs/Coding Milestones/PoC2023q1/scripts.md, scripts/mailbox-prep.sh
This PR changes the `mailbox-prep.sh` script to take the pathname of the edge service provider workspace as a parameter (with a default value of "root:espw") rather than use the current workspace.
Users who use the revised script according to its old interface will not be surprised as long as they are following our convention of using "root:espw" as the pathname of the ESPW.
This PR also updates `scripts.md` to show using the scripts from the `bin` directory.
Fixes #
/cc @dumb0002
=> ✨ Make the ESPW path a parameter of mailbox-prep.sh

pkg/placement/binding-organizer.go, pkg/placement/hash-domain.go, pkg/placement/join-dynamic-12vwith13_test.go, pkg/placement/join-dynamic-12vwith13w_test.go, pkg/placement/join-dynamic-12with13.go, pkg/placement/map-map.go, pkg/placement/map-relation.go, pkg/placement/map-set-differencer.go, pkg/placement/map-set-differencer_test.go, pkg/placement/map-set.go, pkg/placement/relation-types.go, pkg/placement/rotations_test.go, pkg/placement/set-binder-assembly.go, pkg/placement/set-binder-test.go, pkg/placement/set-project.go, pkg/placement/set-types.go, pkg/placement/workload-projector.go
This PR removes some explicit type parameterizations.  This makes lint stop telling me about unnecessary type arguments in those cases.
Unfortunately lint is so stupid that it complains about unnecessary type arguments when only some of the type arguments can be inferred, but go does not have an option to specify only some of the type parameters.
Fixes #
/cc @waltforme
=> 🌱 Rely more on type inference.

docs/content/en/docs/Coding Milestones/PoC2023q1/edge-scheduler.md, docs/content/en/docs/Coding Milestones/PoC2023q1/example1.md, docs/content/en/docs/Coding Milestones/PoC2023q1/placement-translator.md
This PR updates the various instructions to stop installing the edge CRD objects in the ESPW.  The contents of `config/exports/` are all that is needed, and adding the CRD objects might actually be causing a redundancy problem.
Fixes #
/cc @yana1205 
/cc @dumb0002 
=> 🐛 Remove installation of edge CRDs in ESPW

hack/make-release-platform-archive.sh
This PR fixes an old oversight: the syncer-gen plugin needs to be included in the script that builds a release archive.
Fixes #
/cc @yana1205 
=> 🐛 Fixed oversight in platform archive construction

bootstrap/bootstrap-kubestellar.sh
This fix is due to @francostellari .
This fixed a problem that Mike had when testing, in which the first attempt to create a workspace fails with an authorization failure.  Adding this wait made the authorization failure go away.
Fixes #
/cc @dumb0002 
/cc @waltforme
=> 🐛 Wait for root:compute workspace to be usable before proceeding

scripts/kubectl-kubestellar-prep_for_syncer
This PR adds some waiting in the prep-for-syncer plugin, for the asynchronous actions of the mailbox controller.  This is intended to resolve a failure that I saw when testing.
Fixes #
/cc @yana1205 
/cc @dumb0002
=> 🐛 Add waits for needed MBWS state

QUICKSTART.md
This PR adjusts the commands at the end to correctly set the current workspace before proceeding with the teardown.
Fixes #
/cc @dumb0002 
=> 🐛 Correctly set current workspace at start of teardown

QUICKSTART.md
This PR removes the problematic literal version "0.2.0" from the quickstart, because it will soon be wrong, is always impossible to keep correct when using proper release discipline, and the default does what we want.
Fixes #
/cc @dumb0002 
=> 🐛 Remove overspecific and unnecessary args to bootsrap in quickstart

QUICKSTART.md, bootstrap/bootstrap-kubestellar.sh, docs/content/en/docs/Coding Milestones/PoC2023q1/commands.md
This PR extends the command line parsing in the bootstrap strip to recognize the literal "latest" to mean the same thing as omitting that flag: use the latest regular release.
Fixes #
@dumb0002
=> ✨ Extend bootstrap command line to recognize "latest"

bootstrap/bootstrap-kubestellar.sh
This PR updates the bootstrap script so that the default version of kcp is v0.11.0.  That is the only version of kcp that this release will work with.
Fixes #
/cc @dumb0002 
=> ✨ Make default kcp version be v0.11.0

bootstrap/bootstrap-kubestellar.sh, docs/content/en/docs/Coding Milestones/PoC2023q1/commands.md
This PR expands the conditions underwhich bootstrap-kubestellar.sh calls `kubestellar start`, to include absence of the ESPW.
I am factoring #403 into two pieces, and this is one of them, to obey the necessary evolutionary discipline.  This change will get to users before a new release is made, and so has to work with the current release.
Fixes #402
=> 🐛 Fix bootstrap-kubestellar condition for calling start

docs/content/en/docs/Coding Milestones/PoC2023q1/commands.md, hack/make-release-platform-archive.sh
This PR updates the script that creates a release archive to inject a command that reports the release's semver.
This addresses part 1 of #395 but not part 2.  I am not sure that this PR has the right answer.  And for part 2, maybe the answer lies in using commit-based tags rather than release semver; or content-based hash.
Fixes #
/cc @dumb0002
=> ✨ Add kubestellar-release command to report release semver

docs/overrides/main.html
This PR fixes the warning banner on the website to refer to the "latest release" rather than the "latest version", and also clarifies a bare "latest" to "latest release".  This is needed because the latest release is older and generally different from the latest version.
Fixes #
/cc @dumb0002
=> 🐛 Update warning banner to say latest _release_

hack/make-release-container.sh
This PR updates `hack/make-release-container.sh`, to add a second tag on the built image that contains identifying git information: the commit ID and also a warning if the working tree does not equal (modulo ignored files) the commit contents.
This supports #422 
Fixes #
=> ✨ Add syncer image tag holding git info

Makefile
This PR updates the way GIT_DIRTY is determined in the Makefile, so that GIT_DIRTY now reflects whether the build contents will correspond (modulo ignored files) to the commit contents.
Fixes #423
=> 🐛 Fix GIT_DIRTY in Makefile

docs/content/Coding Milestones/PoC2023q1/commands.md, scripts/kubestellar
This PR starts the process of factoring the ESPW control out of the process control.  In particular:
- `kubestellar init` is a new command that just ensures that the ESPW is setup;
- `kubestellar start` still implicitly ensures that the ESPW is setup, so that the bootstrap script does not have to change simultaneously;
- `kubestellar stop` no longer destroys the ESPW (this change is OK to make here because we have no script that invokes `kubestellar stop` and the only recipe, the quickstart, follows it with such obliteration that this detail matters not).
This is part of the project of factoring #403 to respect evolutionary discipline; the other part is #408.
This is the first permissible steps to addressing #401
=> ✨ Introduce kubestellar init

scripts/kubectl-workspace-ensure
kcp plugin to ensure a workspace tree
E.g. kubectl workspace ensure my-org:wmw-1 [--enter] [-V]
This could be used by the bootstrap script
@mikenairn 
@dumb0002 
@andreyod 
Fixes #
=> ✨kcp workspace ensure plugin

docs/content/Coding Milestones/PoC2023q1/edge-syncer.md, pkg/syncer/README.md
- Correct broken links in docs related with syncer ([kubesteller](https://docs.kubestellar.io/main/Coding%20Milestones/PoC2023q1/edge-syncer/) and [README.md](https://github.com/kcp-dev/edge-mc/blob/main/pkg/syncer/README.md))
Fixes #
=> :bug: Correct broken links in docs related with syncer

docs/content/Community/partners/argocd.md
This PR fixes a typo in a recently added documentation, in response to a spelling check here: https://github.com/kcp-dev/edge-mc/actions/runs/5140080321/jobs/9251187073
=> 🐛 Fix a typo in 'partners' docs

bootstrap/bootstrap-kubestellar.sh
Update bootstrap-kubestellar.sh to support M1 arm64
#533
Fixes #
#533
=> 🐛 Update bootstrap-kubestellar.sh to support M1 arm64 Issue 533

docs/content/Coding Milestones/PoC2023q1/commands.md, scripts/kubestellar
This PR extends what `kubestellar init` does, making it also add the RBAC objects to the `root:compute` workspace that enable the syncer to update the `status` sub-objects of the objects whose Kind is defined by the kube APIExport from `root:compute`.
Fixes #477 
Fixes #546
/cc @yana1205 
/cc @dumb0002
=> 🐛 Make `kubestellar init` support syncer updating status

docs/mkdocs.yml
This PR fixes a typo in the documentation which renders into a table of contents for PoC2023q1. Screenshot:
=> 📖 Fix a typo in docs

cmd/mc-client-test/main.go, pkg/mcclient/clientset/clientset.go, pkg/mcclient/listwatch/listwatch.go, pkg/mcclient/mcclient.go
1. Make multi-cluster client singleton safe for concurrent use.
2. Change confusing import name from `mcclient` to `mcclientset`
3. Add missing boilerplates.
Fixes #
/cc @ezrasilvera 
/cc @effi-ofer
=> :sparkles:Make client singleton safe for concurrent use.

.ci-operator.yaml, .prow.yaml, hack/verify-go-versions.sh
This PR replaces the openshift CI operator with basic in-repo Prowjobs.
Note that the verify and lint jobs purposefully do not use the `preset-goproxy`, as this seems to cause weird compatibility issues and errors like
```
< ../../../../pkg/mod/github.com/kcp-dev/kcp@v../pkg/admission/limitranger/admission.go::: github.com/kcp-dev/kubernetes@v..--aaaaabd: reading http://athens-proxy.athens.svc.cluster.local/github.com/kcp-dev/kubernetes/@v/v..--aaaaabd.zip:  Internal Server Error
< ../../../../pkg/mod/github.com/kcp-dev/kcp@v../pkg/admission/plugins.go::: github.com/kcp-dev/kubernetes@v..--aaaaabd: reading http://athens-proxy.athens.svc.cluster.local/github.com/kcp-dev/kubernetes/@v/v..--aaaaabd.zip:  Internal Server Error
```
(see …
=> 🌱 Add Prowjobs

.github/spellcheck/.wordlist.txt, docs/content/Coding Milestones/PoC2023q1/edge-syncer.md, pkg/syncer/README.md, pkg/syncer/scripts/edge-syncer-bootstrap.template.yaml
Fix the section **What kubestellar syncer-gen plugin does**
- CRD creation (step 10) is required only for non-mailbox workspace. Move CRD creation to the step for workspace creation (step 2). Also the location of CRD is fixed (`./pkg/syncer/config/crds/edge.kcp.io_edgesyncconfigs.yaml` => `./config/crds/edge.kcp.io_edgesyncconfigs.yaml`.)
- Fix edge-syncer-bootstrap.template.yaml
- This template is only used for this section.  There is no impact on kubestellar syncer-gen plugin.
Fix misspelling in Syncer related docs
Fixes #
=> :book: Fix documentation about syncer-gen plugin

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md
This PR fixes a typo in the example1 recipe.  It should say `kubectl apply` rather than `kubectl create`.
Fixes #
/cc @amanroa 
/cc @fileppb
=> 📖 Fix typo in example1

pkg/syncer/syncers/common.go, pkg/syncer/syncers/downsyncer.go, pkg/syncer/syncers/upsyncer.go, test/e2e/kubestellar-syncer/syncer_syncerconfig_test.go
As reported in #625, there is a bug that upsynced objects are not updated. I fixed the bug and made sure that it addressed the issue with the issue opener (Tayebeh).   
What 's the changes
- Fix to set UID and Resource Version of the target k8s cluster's one when downsyncer/upsyncer push updated objects from upstream/downstream 
- Fix not to downsync upsynced objects (exactly saying not downsync objects having `edge.kcp.io/upsynced` annotation) and similarly not to upsync downsynced objects (`edge.kcp.io/downsynced` annotation) 
- Update tests
Fixes #625
=> :bug: Fix to set correct UID and resource version when syncing updated objects and do not downsync upsynced objects

pkg/clustermanager/controller.go, pkg/clustermanager/reconcile_clusterprovider.go, pkg/clustermanager/reconcile_logicalcluster.go
Refactoring for cluster manager controller to use both LogicalCluster and ClusterProviderDesc informers.
Fixes #
=> :sparkles:Cluster manager controller refactor.

docs/content/Community/partners/turbonomic.md
This PR lists the steps to integrate turbonomic with kubestellar.
The term ‘edge cluster’ is still used here because #552 is not resolved yet.
#513
=> 📖 Populate the steps to integrate turbonomic

.prow.yaml
This brings the Prow names in-sync with the new repo name. As there are now 2 orgs handled by the same Prow instance, the org name is included in the job names (pull-kubestellar-kubestellar-....)
=> 🌱 rename prowjobs to match new github org

cluster-provider-client/kind/kind.go, cluster-provider-client/provider.go, hack/logcheck.out, pkg/clustermanager/controller.go, pkg/clustermanager/discovery.go, pkg/clustermanager/reconcile_clusterprovider.go, pkg/clustermanager/reconcile_logicalcluster.go
This will add the ability to stop cluster provider discovery loop when provider object is deleted. 
Fixes #
=> :sparkles:Add stop for cluster discovery.

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md
This PR adds `echo` commands that print messages about the identities of the mailbox workspaces involved, both to explain better what is going on and to help debug doc-executable failures.
Fixes #
/cc @dumb0002
=> ✨ Add some informative prints to example1

pkg/clustermanager/controller.go
In controller process queueItem should be used in queue and not key string.
Fixes #
=> :bug:Fix controller queue bug.

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md
I moved the command to clone the KubeStellar Repo to the 'Get KubeStellar' section. 
#692
=> :book: moved kubestellar clone to get kubestellar section

docs/README.md
=> :sparkles: moved 'serving up documents locally' up higher in the doc

clusterprovider/kind/kind.go, config/samples/clusterproviderdesc.yaml, config/samples/logicalcluster_dev.yaml, pkg/clustermanager/controller.go, pkg/clustermanager/provider.go, pkg/clustermanager/providerclient/client_interface.go, pkg/clustermanager/reconcile_logicalcluster.go
1. Do not return from provider watch loop.
2. Enqueue for all object changes on update event.
3. Do not use controller context and logger outside the controller.
4. Change some log messages.
Fixes #
=> :bug:Fix logical clusters issues.

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-4.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md, docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler-subs/kubestellar-scheduler-0-pull-kcp-and-kubestellar-source-and-start-kcp.md, docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler-subs/kubestellar-scheduler-1-build-kubestellar.md, docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler-subs/kubestellar-scheduler-1-export-kubeconfig-and-path-for-kcp.md, docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler-subs/kubestellar-scheduler-2-ws-root-and-ws-create-edge.md, docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler-subs/kubestellar-scheduler-imports.md, docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler-subs/kubestellar-scheduler-process-start.md, docs/content/Coding Milestones/PoC2023q1/kubestellar-scheduler.md, docs/content/Coding Milestones/PoC2023q1/mailbox-controller-subs/mailbox-controller-process-start.md, docs/content/Coding Milestones/PoC2023q1/mailbox-controller.md, docs/content/Coding Milestones/PoC2023q1/placement-translator-subs/placement-translator-process-start-without-cd-kubestellar.md, docs/content/common-subs/pre-req.md, docs/content/common-subs/save-some-time.md, docs/content/common-subs/teardown-the-environment.md, docs/scripts/docs-ecutable.sh
This PR changes the executable docs to not fetch the KubeStellar repo but rather use the copy of the repo that they find themselves executing in.
This makes the executable documents useful as tests, to developers and to CI.
Fixes #720
=> ✨ No nested fetch

pkg/placement/workload-projector.go
This PR updates the comment in the workload projector file's outline comment, to track the addition (done months ago) of monitoring of projected objects.
Fixes #
=> 🐛 Fix comment on workload projector

cmd/kubestellar-where-resolver/cmd/where-resolver-cmd.go, pkg/where-resolver/controller.go
This PR removes the 'all cluster' kcp clientset from the scheduler because it is proved that the scheduler doesn't need it.
Thanks to @MikeSpreitzer 's [previous review](https://github.com/kubestellar/kubestellar/pull/206#discussion_r1134941611).
#711 
=> ✨ Remove 'all cluster' kcp clientset from the kubestellar-scheduler

cmd/kubestellar-where-resolver/cmd/where-resolver-cmd.go, cmd/kubestellar-where-resolver/options/options.go
This PR removes unnecessary privileges from the where-resolver, by switching from the `shard-admin` user to the `kcp-admin` user.
Below are the two relevant contexts in kcp's admin-kubeconfig:
```yaml
- context:
cluster: base
user: kcp-admin
name: base
- context:
cluster: base
user: shard-admin
name: system:admin
```
/cc @MikeSpreitzer 
#711
=> ✨ Make the where-resolver less privileged

VERSION
Add a way to reliably determine the latest and stable release of KubeStellar 
#760
Fixes #
=> ✨Create VERSION to reliably state/track the latest/stable binary release

.github/workflows/goreleaser.yml, .goreleaser.yaml, Makefile
Currently there is no .goreleaser.yaml that is required for goreleaser github action. I created .goreleaser.yaml whose configuration is to create and push syncer image to `quay.io/kubestellar/syncer:<release tag>` in goreleaser github action. Note that the section `builds` and `release` in  .goreleaser.yaml are disabled since we have another way to build binaries and publish the archive to release artifacts.  
Here is the example in the case of forked github repository with setting my personal quay.io repository to `kos[].repository` in gorelease.yaml.
Github action job: https://github.com/yana1205/kubestellar/actions/runs/5479915632/jobs/9982395090
The pushed image is kubestellar-syncer:0.3.2 (https://quay.io/repository/yanagawa_takumi1205/kubestellar-syncer?tab=tags.)
The following …
=> :sparkles: Use goreleaser for automating to build and push syncer image to quay.io

docs/content/Community/partners/argocd.md, hack/boilerplate/boilerplate.sh.txt
This PR changes the word 'edge-mc' to 'kubestellar' for all external references in the Argo CD integration doc.
The external references has also been updated before this PR.
Fixes #768 
=> 🐛 Change edge-mc to kubestellar in external references

VERSION
Bump `latest` version in VERSION to v0.4.0
Stay `stable` version at v0.3.1
Fixes #
=> ✨ Bump latest version in VERSION to 0.4.0

.gitignore, README.md, docs/README.md, docs/content/Coding Milestones/PoC2023q1/outline.md, docs/content/Coding Milestones/PoC2023q1/roadmap-uses.md, docs/content/Coding Milestones/PoC2023q3/outline.md, docs/content/readme.md, docs/mkdocs.yml
Also describe how to use a Python virtual environment to preview the docs.
This PR updates the roadmap remarks on the website.  That consists of the following three things.
1. Clarify that the `roadmap-uses.md` doc was about use cases that guided thoughts about roadmapping the 2023q1 PoC.
2. Start writing a definition of the 2023q3 PoC.
3. Add to the project README a bigger roadmapping throught in terms of a march of PoCs.
This PR also updates the instructions in `docs/README.md` to add guidance for those who prefer to use Python virtual environments to disentangle their various Python-based projects.
Fixes #697
=> 📖 Update roadmap remarks on website to support PoC2023q4

scripts/kubectl-kubestellar-prep_for_cluster, scripts/kubectl-kubestellar-prep_for_syncer
Add a `-s|--silent` option to both `kubestellar-prep_*` plugins to enable easier piping of the syncer yaml:
```shell
kubectl kubestellar prep-for-cluster --silent --imw root:example-imw kind-edge env=prod -o - 2> /dev/null 1> syncer.yaml
```
#803
Fixes #
#803
=> ✨ Add `--silent` option to `kubestellar-prep_*` plugins for easier piping of syncer yaml

clusterprovider/kubeflex/kubeflex.go, pkg/apis/logicalcluster/v1alpha1/cluster-provider-desc.go, pkg/clustermanager/provider.go
Add kubeflex provider to logical clusters.  
This PR replaces PR #789 now that logical clusters have been merged to main.
Fixes #
=> :sparkles: add kubeflex provider to logical clusters

cmd/emc-customize/main.go, cmd/placement-translator/main.go, hack/logcheck.out, pkg/customize/customize.go, pkg/placement/main.go, pkg/placement/workload-projector.go
pkg/placeholder/workload-projector.go needs to use Kubestellar edge.kcp.io rather than TMC scheduling.kcp.io. This should have been included in Feature 814's changes, but was overlooked.
814
836
Fixes #
836
=> 🐛 Fix 836 Ensure workload-projector uses Kubestellar locations.edge.kcp.io instead of KCP's locations

pkg/clustermanager/provider.go, pkg/clustermanager/reconcile_clusterprovider.go
This will allow provider client to access the provider by using config from provider description object.
Fixes #
=> :sparkles:Use provider config field for provider client

scripts/kubectl-kubestellar-prep_for_syncer
This PR undoes the regression noted in https://github.com/kubestellar/kubestellar/pull/823#pullrequestreview-1553979529
=> 🐛 Restore progress on moving SyncTarget to KubeStellar repo

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md
This PR hopefully improves the wording in example1 about how to get (and build if necessary) a local copy of KubeStellar.  This includes ending the use of `go run` (which was precluding the use of pre-built archives).
Fixes #
=> 📖 Improve wording on getting KubeStellar

docs/content/Coding Milestones/PoC2023q1/commands.md, scripts/kubestellar-ensure-ca, scripts/kubestellar-ensure-kcp-server-creds, scripts/kubestellar-make-kcp-server-cert, scripts/switch-domain, scripts/wait-and-switch-domain
This PR adds a first draft of scripts designed to support more complex deployment scenarios, as outlined in #788.  These scripts are concerned with the following two things.
1. Support generation of server credentials to pass to kcp or plain kube server via `--tls-sni-cert-key`.
2. Create alternate kubeconfig files by replacing the protocol://host:port prefix of cluster server URLs and the CA certificate data.
These scripts are factored so that the user can launch the kcp server in their own way and support multiple sets of clients needing to connect to the kcp server using different domain names.
Fixes #
=> ✨ Draft scripts to support external processes

docs/content/Coding Milestones/PoC2023q1/commands.md, scripts/kubestellar-ensure-kcp-server-creds, scripts/kubestellar-make-kcp-server-cert
This PR updates `scripts/kubestellar-make-kcp-server-cert` to make the name of the file that holds the server certificate depend on the domain name in the certificate, so that certs for different domain names can coexist at the same time.
Fixes #
=> 🐛 Make server cert filename depend on domain name

scripts/kubestellar-ensure-kcp-server-creds, scripts/kubestellar-make-kcp-server-cert
This PR changes the `kubestellar-ensure-kcp-server-creds` and `kubestellar-make-kcp-server-cert` scripts to work around the fact that EasyRSA does not want to work with long filenames.  It also fixes a bug in the idempotency logic in `kubestellar-ensure-kcp-server-creds`.
Fixes #
=> 🐛 Fix file name issues in kubestellar-ensure-kcp-server-creds

docs/content/Coding Milestones/PoC2023q1/commands.md, scripts/switch-domain, scripts/wait-and-switch-domain
This PR changes the `switch-domain` and `wait-and-switch-domain` commands to simply take an output pathname rather than compute it from other parts.  This one usage we have does not want to use the output path that was being computed.
Fixes #
=> ✨ Change switch-domain to take output pathname

CONTRIBUTING.md, bootstrap/bootstrap-kubestellar.sh, docs/content/Coding Milestones/PoC2023q1/commands.md, docs/content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md
This PR adds an option to the bootstrap script to skip deploying kcp and KubeStellar, to focus only on fetching them.
This PR also updates the commands doc to make all the headings get indexed and remove documentation of the curl-to-bash scripts that we are no longer recommending to users.
This is an alternative to #856 
Fixes #
=> 🌱 Make bootstrap script able to not deploy

docs/content/Coding Milestones/PoC2023q1/environments/dev-env.md, docs/content/Contribution guidelines/CONTRIBUTING.md
This PR adds some missing documentation for contributors.  It extends the dev env remarks about kind clusters with a pointer to how to load a locally built Docker image.  It extends the CONTRIBUTING.md remarks about testing to describe the current story about how to build and test a new container image for the center components.
Fixes #
=> 📖 Document build and test of center image

cmd/go-template-execute/README.md, cmd/go-template-execute/go.mod, cmd/go-template-execute/go.sum, cmd/go-template-execute/main.go
This PR adds a utility command that simply executes a given go template with some given data.
It can be helpful in developing Helm charts, and can be used in preliminary development before there is an actual Helm chart.  It can remove the need to make many variants of one config file.
Fixes #
=> ✨ Create generic command to execute a go template

docs/content/Coding Milestones/PoC2023q1/commands.md
This PR documents the fact that `kubectl kubestellar deploy`, `kubectl kubestellar get-internal-kubeconfig`, and `kubectl kubestellar get-external-kubeconfig` accept `-X` and `-h` on the command line.
This should have been included from the start but was overlooked.
Fixes #
/cc @ronenkat 
/cc @dumb0002 
@clubanderson
=> ✨ Document -X and -h for new commands

docs/content/Coding Milestones/PoC2023q1/commands.md, scripts/kubectl-kubestellar-get_log
This PR adds a command for use by the KubeStellar platform administrator when the central KubeStellar components are deployed as workload in a hosting Kubernetes cluster.
Fixes #
=> ✨ Add command to fetch central process log

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md
This PR updates example1 to walk through both ways of deploying kcp and KubeStallar: the old way (as bare processes) and the new way (as workload in a Kubernetes cluster).
Fixes #
/cc @ronenkat 
/cc @dumb0002 
=> 📖 Make example1 show both ways of deploying

docs/content/Coding Milestones/PoC2023q1/commands.md
This PR changes an example port number to make it more obvious that this particular bit of documentation has zero normative force regarding the port number but rather is trying to talk about how to cope with whatever port number is coming from the actual usage context.
Fixes #
/cc @ronenkat 
@clubanderson 
/cc @dumb0002
=> 📖 Make port number more clearly an example

hack/make-release-platform-archive.sh
This PR adds the Helm chart to the stuff put into a platform archive, because the `kubectl kubestellar deploy` command uses it.
Fixes #
/cc @ronenkat 
/cc @dumb0002 
@clubanderson 
=> 🐛 Add helm chart to platform archive

config/samples/my-org_space.yaml, config/samples/space1.yaml, pkg/space-manager/provider.go, pkg/space-manager/providerclient/client_interface.go, pkg/space-manager/reconcile_space.go, space-provider/kcp/kcp.go, space-provider/kind/kind.go
This will allow to use KCP workspace hierarchy by setting parent workspace in Space object annotation. Provider that doesn't implement hierarchy may ignore this annotation.
https://github.com/kubestellar/kubestellar/issues/869
Fixes #
=> :sparkles:Support workspace hierarchy in KCP space provider

docs/content/Coding Milestones/PoC2023q1/commands.md
This PR documents how to undo deployment of kcp+KubeStellar as a workload in a Kubernetes cluster.
Fixes #
/cc @dumb0002 
/cc @ronenkat 
=> 📖 Document teardown of deployment to Kubernetes

hack/logcheck.out, pkg/placement/workload-projector.go, scripts/kubestellar
This PR fixes the logic in the placement translator to avoid processing Workspace objects while they are still being set up, and adds error checking for empty cluster IDs in other places.
This PR also updates the logic in `kubestellar init` to print an explanatory message if the first attempt to use the kcp server fails.
This PR also changes the `kubestellar` script to eschew `&>>` redirection in favor of `>> file 2>&1` because bash on the Mac is astonishingly back-level.
Fixes #935 
Fixes #936
=> ✨ Avoid empty cluster IDs

pkg/syncer/syncers/downsyncer.go
This PR updates the syncer to make it choose how to update the status of an upstream object based on the API group. This is better than the previous code but not fully correct; the correct code would somehow depend on whether the resource actually has a status subresource.
This partially addresses #945 .
=> 🐛 Choose update status method according to API group

scripts/kubectl-kubestellar-prep_for_syncer
This PR updates the prep-for-syncer plugin in the `release-0.4` branch to use the syncer image built from #946 .
This partially addresses #945
=> 🐛 release-0.4: Update prep-for-syncer plugin to use PR 946

scripts/kubectl-kubestellar-prep_for_syncer
This PR changes the prep-for-syncer plugin to use the syncer image that I built for `main` just after #947 merged into `main`.
This partially addresses #945
=> 🐛 Make prep-for-syncer plugin use status write hack

space-provider/kcp/kcp.go
This PR will change KCP space provider to use LogicalCluster informer instead of `watch` API call which is unstable. 
Fixes #
https://github.com/kubestellar/kubestellar/issues/964
=> :bug: Use informer in KCP space provider

pkg/syncer/controller/syncerconfigcontroller_test.go, pkg/syncer/controller/syncerconfigmanager.go, test/e2e/kubestellar-syncer/common_test.go, test/e2e/kubestellar-syncer/syncer_kyverno_test.go, test/e2e/kubestellar-syncer/syncer_namespaced_objects_test.go, test/e2e/kubestellar-syncer/syncer_syncerconfig_test.go, test/e2e/kubestellar-syncer/testdata/kyverno/syncer-config-namespaced-objects-coexist.yaml, test/e2e/kubestellar-syncer/testdata/kyverno/syncer-config-namespaced-objects.yaml, test/e2e/kubestellar-syncer/testdata/namespaced-objects/configmap-test1-cm1.yaml, test/e2e/kubestellar-syncer/testdata/namespaced-objects/configmap-test1-cm2.yaml, test/e2e/kubestellar-syncer/testdata/namespaced-objects/configmap-test2-cm1.yaml, test/e2e/kubestellar-syncer/testdata/namespaced-objects/configmap-test2-cm2.yaml, test/e2e/kubestellar-syncer/testdata/namespaced-objects/configmap-test3-cm1.yaml, test/e2e/kubestellar-syncer/testdata/namespaced-objects/secret-test1.yaml, test/e2e/kubestellar-syncer/testdata/namespaced-objects/secret-test2.yaml, test/e2e/kubestellar-syncer/testdata/namespaced-objects/secret-test3.yaml, test/e2e/kubestellar-syncer/testdata/namespaced-objects/syncer-config.yaml, test/e2e/kubestellar-syncer/testdata/syncerconfig/syncer-config-namespaced-objects.yaml
- Extend Syncer to support newly introduced namespacedObject field in SyncerConfig
- It keeps backward compatibility and also supports the new format.
- Add test cases
- [Existing SyncerConfig](https://github.com/yana1205/kubestellar/blob/cd9892c5abfaf910cc9a0316cc0852e65ee017d3/test/e2e/kubestellar-syncer/testdata/kyverno/syncer-config.yaml) (used namespaceScoped field) for backward compatibility
- [New SyncerConfig](https://github.com/yana1205/kubestellar/blob/cd9892c5abfaf910cc9a0316cc0852e65ee017d3/test/e2e/kubestellar-syncer/testdata/kyverno/syncer-config-namespaced-objects.yaml) (used namespacedObject field)
- [Union](https://github.com/yana1205/kubestellar/blob/cd9892c5abfaf910cc9a0316cc0852e65ee017d3/test/e2e/kubestellar-syncer/testdata/kyverno/syncer-config-namespaced-objects-coex …
=> :sparkles: Syncer supports NamespacedObjects in syncerconfig

cmd/cluster-watchall/README.md, cmd/cluster-watchall/main.go, pkg/apiwatch/resources.go
Also fix doc nits and remove unused client.
This PR does a little cleanup in preparation for bigger things. The one does the following.
1. Switch the cluster-watchall command to use the library for kubectl options.
2. Add missing fenced code block tags in the README for cluster-watchall.
3. Remove an unused internal field in pkg/apiwatch.
Believe it or not, this is part of working on #772 .  The placement-translator is going to need to know whether to update a status "subresource" or a plain field (#945).
=> ✨ cleanup cluster-watchall and apiwatch

.secrets.baseline, cmd/syncer/main.go, cmd/syncer/options/options.go, docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-1-syncer-gen-plugin.md, pkg/cliplugins/kubestellar/syncer-gen/edgesync.go, pkg/cliplugins/kubestellar/syncer-gen/edgesync_test.go, pkg/cliplugins/kubestellar/syncer-gen/kubestellar-syncer.yaml, pkg/syncer/scripts/kubestellar-syncer-bootstrap.template.yaml, pkg/syncer/syncer.go, test/e2e/framework/kubestellar_syncer.go
This is the PR for #874.
- Remove the dependency of kcp logical cluster function from Syncer
I reviewed Syncer code whether Syncer really depends on logical cluster id or not and concluded it's not required. I have removed the dependent codes on the logical cluster stuff from Syncer. As a result, Syncer does no longer require `--from-cluster` option.
UT passed
```
$ make test-syncer COUNT=1
go test -count 1 `go list ./... | grep "/pkg/cliplugins\|/pkg/syncer"`
?       github.com/kubestellar/kubestellar/pkg/syncer   [no test files]
?       github.com/kubestellar/kubestellar/pkg/syncer/clientfactory     [no test files]
?       github.com/kubestellar/kubestellar/pkg/syncer/shared    [no test files]
?       github.com/kubestellar/kubestellar/pkg/syncer/syncers   [no test files]
ok …
```
=> :seedling: Remove the dependency of core.kcp.io/v1alpha1/logicalclusters from Syncer

pkg/cliplugins/kubestellar/syncer-gen/edgesync_test.go, pkg/cliplugins/kubestellar/syncer-gen/kubestellar-syncer.yaml, scripts/kubectl-kubestellar-prep_for_syncer
This is followup change for https://github.com/kubestellar/kubestellar/pull/999#issuecomment-1720389062
> * After that merges we can build a syncer image from main and start using that. We can change prep-for-syncer to default to the new syncer image.
> * At that same time or later, we change syncer-gen to not emit the --from-cluster flag.
Mike has made the latest image (syncer:pr-999) built after https://github.com/kubestellar/kubestellar/pull/999 is merged. 
The PR contains 
- remove --from-cluster flag
- switch the default image to this image
Fixes #
=> :seedling: Remove --from-cluster flag and temporally use syncer:pr-999 for transitioning to the new syncer-gen

Makefile, docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer.md
This PR changes the command that builds the syncer image so that the image depends only on the code and other functional stuff that goes into it, to support managing the image references in a functional style without self-reference problems.
This PR also updates the Makefile variables relevant to building the syncer image, so that their default values match what we normally want.  This also includes renaming the variable "ARCHS" to "SYNCER_PLATFORMS" because (a) its usage is specific to building the syncer image and (b) "platform" is the word used in in the documentation about this sort of building.
Fixes #
=> ✨ Make syncer image not depend on commit ID

scripts/kubectl-kubestellar-deploy
This PR updates the `kubectl kubestellar deploy` command to use the container image built from the latest sources.  This picks up the API change in #884 and the syncer CLI change in #999 and #1003 (although I expect the syncer change is not relevant to the contents of the center container image).
Fixes #
=> ✨ Update kubectl-kubestellar-deploy to latest KS ctr image

docs/content/Getting-Started/user-guide.md
This PR makes two enhancements to the glossary.  One is add some material on kcp.  The other is to distinguish between "physical space" and "space object".
Fixes #
=> 📖 Add kcp, Space object-vs-physical distinction to glossary

space-framework/config/crds/space.kubestellar.io_spaces.yaml, space-framework/config/exports/apiresourceschema-spaces.space.kubestellar.io.yaml, space-framework/pkg/apis/space/v1alpha1/space.go, space-framework/pkg/space-manager/provider.go, space-framework/pkg/space-manager/reconcile_space.go, space-framework/pkg/space-manager/reconcile_spaceprovider.go, space-framework/test/e2e-sh-tests/space1.yaml, space-framework/test/e2e-sh-tests/space2.yaml
Introduce a Type for the space object.  The type can be: managed, unmanaged, or imported.  Where imported implies a space without a provider object.  An imported space can be a space residing on a regular kubernetes cluster which does not enable creation of multiple spaces.
Fixes #
=> ✨ introduce a Type for the space object

bootstrap/install-kcp-with-plugins.sh, bootstrap/install-kubestellar.sh
Improve automatic arch detection to include the $HOSTTYPE reported by arm-based Macs
#971
#979
Fixes #
#979
=> :bug: Fix arch detection for Mac arm in install-kcp-with-plugins.sh

Makefile, center.Dockerfile
This PR updates the Makefile so that building the central container image now applies two tags, rather than just the previous one; the new tag identifies the git commit, while the old tag identifies the build time.  Adding this information helps with understandability of the produced artifacts, while keeping it out of the image contents avoids an offense against making the image depend only on its _functional_ input.
This PR also fixes a bug in the center.Dockerfile that was introduced in a recent space PR.
Fixes #
=> 🌱 Also tag center KS image with git commit

cmd/mailbox-controller/main.go, cmd/placement-translator/main.go, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-teardown.md, docs/content/Coding Milestones/PoC2023q1/example1.md, docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-0-deploy-florin.md, docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-0-deploy-guilder.md, docs/content/Coding Milestones/PoC2023q1/mailbox-controller.md, docs/content/Coding Milestones/PoC2023q1/placement-translator.md, docs/content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-b-create-imw-and-wmw.md, docs/content/Getting-Started/quickstart-subs/quickstart-2-apache-example-deployment-d-create-and-deploy-apache-into-clusters.md, pkg/placement/main.go, scripts/kubectl-kubestellar-prep_for_syncer
This PR will remove the usage of space hierarchy and all KubeStellar spaces will be created at the same level under root.
This includes the mailbox spaces, previously resided under core space. 
https://github.com/kubestellar/kubestellar/issues/976
Fixes #
=> :sparkles:Remove the usage of workspace hierarchy

Makefile, docs/content/Coding Milestones/PoC2023q1/commands.md, docs/content/Contribution guidelines/CONTRIBUTING.md
This PR stupidifies the built images to not mention that v2 of the x86-64 ISA is required, because OpenShift nodes refuse to pull images that _do_ say they are built for that (even when run on a machine that has those instructions). This PR also adds a note to the building instructions about this.
Fixes #
=> 🐛 Adopt hack for OpenShift vs amd64/v2 problem

scripts/kubectl-kubestellar-deploy
This PR updates the default reference to the core kubestellar image, to refer to the latest build --- which was built from the commit to which `main` refers right now.
Fixes #
=> 🌱 Update default core image reference to latest build

pkg/placement/workload-projector.go
This PR fixes a nil pointer fault that happens when reporting a failure to update a downsynced object in the mailbox workspace.
This PR also fixes the severity of the log message: this could be a transient condition that will be healed soon.
This fixes the appearance of #1076 in the `main` branch; the problem was experienced in v0.7.0.
=> 🐛 Stop using nil from failed Update

docs/content/Coding Milestones/PoC2023q1/commands.md, scripts/kubestellar
This PR does two things.
(1) Make waiting for a "kcp" process optional.
(2) Add non-optional waiting for the server to be fully ready.
I think this needs to go in before #1077 so that can use this.
=> ✨ Improve `kubestellar init` wrt waiting for kcp

scripts/kubectl-kubestellar-deploy
This PR updates the default reference to the core image to refer to a build of the `main` branch as it is right now, just after merging #1031 . An update to the default should have been part of that PR, but I forgot.
Fixes #
=> 🐛 Update default core image ref to build of current main

pkg/syncer/syncers/common.go, pkg/syncer/syncers/downsyncer.go, scripts/kubectl-kubestellar-prep_for_syncer
This makes the syncer modify existing objects in the WEC regardless of whether they have the annotation that the syncer applies. This is because Thanos expects such rough play. Hopefully this will not break anything!
This is intended to address #1102 in the `release-0.7` branch.
=> ✨ Make the syncer more assertive

Makefile, core.Dockerfile
This PR fixes a bug in the current dance for building the core image, in which the `core.Dockerfile` creates a git working tree that appears to be dirty but in reality just contains the needed subset of a clean tree.
Fixes #
=> 🐛 Enable unconfusion regarding git tree state

pkg/placement/what-resolver.go, pkg/placement/workload-projector.go, scripts/kubectl-kubestellar-deploy
This PR changes the placement translator to do the filtering out of the system objects in the what resolver rather than in the workload projector because in the part of the latter that deals with SyncerConfig there is not enough information to filter accurately.
Fixes #1068
=> 🐛 Filter out system objects earlier in placement translator

.secrets.baseline, Makefile, test/e2e/framework/kubestellar_syncer.go
Originally this change is to address errors at Syncer E2E tests along with the works for moving to kcp 0.20.0(https://github.com/kubestellar/kubestellar/pull/1070). The original PR of this change is https://github.com/MikeSpreitzer/kcp-edge-mc/pull/2. This change results in some kind of cleanup of unused methods and scripts, which is benefit for maintenance. So, I would like to open this PR to main branch.
What's changes:
- Remove unused code paths in syncer e2e setup (test/e2e/framework/kubestellar_syncer.go)
- Fix Makefile
- to setup root:compute workspace by `kubestellar init`
- to use bootstrap-kubestellar.sh instead of install-kcp-with-plugins.sh for kcp installation
- install-kcp-with-plugins.sh is no longer referred by any code so the issue …
=> :bug: Cleanup and refactoring syncer e2e related parts

bootstrap/bootstrap-kubestellar.sh, bootstrap/install-kcp-with-plugins.sh, bootstrap/install-kubestellar.sh, core-container/entry.sh, docs/content/Coding Milestones/PoC2023q1/commands.md, scripts/kubestellar
Create a consistent experience to ensure IMWs and WMWs across all scripts.
- update `kubestellar init` to accept `--ensure-imw "imw-list"`  and `--ensure-wnw "wmw-list"`, where the list are comma separated and accept fully qualified kcp paths (default is `imw1` and `wmw1` to respect current behavior, use "" to create nothing)
- update `bootstrap-kubestellar` to leverage the above `kubestellar init` code instead of its own copy of the code
- update container `entry.sh`  to leverage the above `kubestellar init` code instead of its own copy of the code
Fixes #
#1098
=> ✨ Ensure IMWs and WMWs across all scripts

scripts/kubectl-kubestellar-deploy
This PR updates the core image tag used by `kubectl kubestellar deploy` to a build of the latest (as of now) core code.
This picks up the changes in #1111 .
=> 🌱 Update default core image tag to build of PR 1111

outer-scripts/kubectl-kubestellar, outer-scripts/kubectl-kubestellar-deploy, outer-scripts/kubectl-kubestellar-ensure, outer-scripts/kubectl-kubestellar-ensure-location, outer-scripts/kubectl-kubestellar-get_external_kubeconfig, outer-scripts/kubectl-kubestellar-get_internal_kubeconfig, outer-scripts/kubectl-kubestellar-prep_for_cluster, outer-scripts/kubectl-kubestellar-prep_for_syncer, outer-scripts/kubectl-kubestellar-remove, outer-scripts/kubectl-kubestellar-remove-location, outer-scripts/kubectl-kubestellar-remove-wmw, overlap-scripts/kubectl-kubestellar-ensure-wmw
This PR makes some usability improvements to the kubectl plugins.
1. They accept `--help` as well as `-h`.
2. The missing interior nodes in the command tree have been added.
3. kubectl flag gathering is expanded to allow one parameter-less flag at the end of the command line (this is better than allowing nowhere at all, we will wait for #414 to get a fully good answer here).
Fixes #1119
=> 🐛 Remove some sharp edges from kubectl plugins

space-framework/space-provider/kubeflex/kubeflex.go, space-framework/test/e2e-sh-tests/space-kflex1.yaml, space-framework/test/e2e-sh-tests/spaceproviderdesc-kflex.yaml
The Get() function in the kubeflex provider somehow lost the space name usage.
Fixes #
=> :bug: fix Get function in kflex provider

docs/content/Getting-Started/quickstart-subs/quickstart-1-install-and-run-kubestellar.md
This PR fixes the display in the quickstart of the initial load of spaces after deploying the core as workload in a Kube cluster.
Fixes #1142
=> 🐛 Fix display of initial spaces after deploy in kube

bootstrap/bootstrap-kubestellar.sh, docs/content/Coding Milestones/PoC2023q1/commands.md
This PR generalizes the bootstrap script so that the namespace in the hosting cluster is controllable, and changes the default behavior so that the chart goes into `kubestellar` rather than `default` (which removes the inconsistency #1141).
Fixes #1141
=> ✨ Generalize bootstrap wrt namespace in hosting cluster

core-helm-chart/values.yaml
This PR updates the default core image tag in the release-0.8 branch to say "release-0.8".
Fixes #
=> 🌱 Chart release 0.8

core-helm-chart/values.yaml
This PR updates the default core image tag in the Helm chart's `values.yaml` to be named after the coming release. The theory is that a tag naming a release branch can be advanced along backward-compatible changes to pick up improvements and bug fixes while being specific enough to insulate a user of one branch from work on the next branch.
Fixes #
=> 🌱 Align default core image ref in chart with coming release

docs/content/Coding Milestones/PoC2023q1/environments/dev-env.md
Change the port used in the example from `6443` to `1024` to match the instructions in the core-helm-chart README.md
Fixes #
=> 📖Update dev-env.md

inner-scripts/kubestellar, outer-scripts/kubectl-kubestellar-deploy
This PR injects usage of `realpath` into scripts that navigate from `$something/bin` to `$something/config` or `$something/core-helm-chart` because sometimes that `bin` is a symlink and the `config` or `core-helm-chart` is adjacent to where that symlink points.
This PR also removes a redundant variable holding the `bin` pathname.
Fixes #1152
=> 🐛 Use realpath to see through symlinks

docs/content/Coding Milestones/PoC2023q1/commands.md
This PR updates the commands reference to describe how to remove a syncer from a WEC.
This partially addresses #1163
=> 📖 Document syncer removal

outer-scripts/kubectl-kubestellar-get_internal_kubeconfig
This PR updates the `kubectl kubestellar get-internal-kubeconfig` command to fetch the mid-level kubeconfig --- the one using the kubestellar service name rather than the core Pod IP address. This is more broadly useful, while still being consistent with what the documentation says (vaguely, sigh). This is a backward-compatible change.
This PR also fixes a bug in the help message.
Fixes #
=> ✨ Make get-internal-kubeconfig fetch mid-level kubeconfig

docs/content/Coding Milestones/PoC2023q1/commands.md, outer-scripts/kubectl-kubestellar-remove-wmw, overlap-scripts/kubectl-kubestellar-ensure-wmw
This PR makes `kubectl-kubestellar-ensure-wmw` and `kubectl-kubestellar-remove-wmw` insensitive to the current workspace, because since #1015 the parent must be `root`.
This is a backward-compatible change.
This PR also does some overdue updates to the documentation for those commands that should have been included with earlier PRs that expanded the Kubernetes API supported (implementing #522).
Reimplementation for #414 should take note.
Fixes #1159
=> ✨ Make ensure/remove wmw insensitive to current workspace

pkg/cliplugins/kubestellar/syncer-gen/edgesync_test.go, pkg/cliplugins/kubestellar/syncer-gen/kubestellar-syncer.yaml, pkg/syncer/scripts/kubestellar-syncer-bootstrap.template.yaml
Old name is still used in the syncer bootstrap manifest (e.g. container name). I fixed it to display the name as "kubestellar".  
Before:
- "kcp" appears somewhere (`name: kcp-syncer` is the field for container name)
```
$ KUBECONFIG=~/.kube/config kubectl --context kind-florin get pod -n kubestellar-syncer-florin-q8lheni0 kubestellar-syncer-florin-q8lheni0-599855f7c4-t5jq7 -o yaml | grep kcp
- --from-kubeconfig=/kcp/kubeconfig
name: kcp-syncer
- mountPath: /kcp/
name: kcp-config
- name: kcp-config
```
After
- no longer appears
```
$ KUBECONFIG=~/.kube/config kubectl --context kind-florin get pod -n kubestellar-syncer-florin-1zgupzpd kubestellar-syncer-florin-1zgupzpd-5c77df59fc-nwn69 -o yaml | grep kcp
```
- the container name
```
$ KUBECONFIG=~/.kube/config kubectl --context kind-florin …
```
=> :bug:fix syncer bootstrap manifests to change names like container name from kcp to kubestellar

pkg/placement/workload-projector.go
This PR fixes a couple of typos that cause log messages to hold the hex value of a function rather than the (intended) result of calling the function.
Fixes #
=> 🐛 Fix stupid typos

docs/content/Getting-Started/user-quickstart-kind.md, docs/content/Getting-Started/user-quickstart-openshift.md, docs/content/common-subs/kubestellar-apply-apache-kind.md, docs/content/common-subs/kubestellar-apply-apache-openshift.md
This PR updates the openshift quickstart to add a RoleBinding that authorizes the httpd Pod to run. It probably grants more privilege than necessary, but I found that granting only `anyuid` is not enough --- that led to complaints about using a host port.
Fixes #
=> 🐛 Update openshift quickstart to authorize workload on OpenShift

cmd/cluster-watchall/main.go, cmd/placement-translator/main.go, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md, pkg/apis/meta/v1alpha1/resources.go, pkg/apiwatch/apibindings.go, pkg/apiwatch/crds.go, pkg/apiwatch/definition-tracking.go, pkg/apiwatch/resources.go, pkg/placement/apiwatch-map-provider.go, pkg/placement/main.go, pkg/placement/what-resolver.go, pkg/placement/what-resolver_test.go
This PR extends the apiwatch package so that it can reveal what object(s) define a given resource, when the definer is a CRD or APIBinding.  This PR modifies the cluster-watchall command to exercise the extended functionality.
This lays a foundation for addressing #1064 and #1080
=> ✨ Make apiwatch package reveal definers of resources

Makefile, cmd/kubestellar-list-syncing-objects/README.md, cmd/kubestellar-list-syncing-objects/main.go, docs/content/Coding Milestones/PoC2023q1/commands.md
This PR adds a demo/utility command that lists or watches the objects of a given kind in the mailbox workspaces.
Example usage:
```
kubestellar-list-mid-dynamic --api-group apps --api-kind ReplicaSet
```
Fixes #
=> ✨ Introduce kubestellar-list-syncing-objects

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md, docs/content/Getting-Started/user-quickstart-kind.md, docs/content/Getting-Started/user-quickstart-openshift.md, docs/content/common-subs/kubestellar-list-syncing.md
This PR updates the example1 and user quickstarts to show the use of the new `kubestellar-list-syncing-objects` command.
This also fixes the command shown in example1 to wait for the placement translator to do its job to _only_ wait on that much.
Fixes #
=> 📖 Update example1 and user quickstarts to use new command

cmd/kubestellar-where-resolver/cmd/where-resolver-cmd.go, cmd/mailbox-controller/controller.go, cmd/mailbox-controller/main.go, cmd/placement-translator/main.go, core.Dockerfile, hack/logcheck.out, pkg/placement/main.go, pkg/placement/what-resolver.go, pkg/placement/what-resolver_test.go, pkg/placement/where-resolver.go, pkg/placement/where-resolver_test.go, pkg/placement/workload-projector.go, pkg/where-resolver/controller.go, pkg/where-resolver/reconcile_on_edgeplacement.go, pkg/where-resolver/reconcile_on_location.go, pkg/where-resolver/reconcile_on_synctarget.go
Initial replacement of KCP APIExport/APIBinding for view of exports with kube-bind in KubeStellar controllers
Fixes #
=> :sparkles:Initial replacement of KCP-bind with kube-bind

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md, docs/content/Coding Milestones/PoC2023q1/outline.md, pkg/placement/workload-projector.go
This PR updates the design outline to explicitly discuss reported state of Namespace and CustomResourceDefinition objects, and fixes some bugs in the workload-projector in those areas.
This PR also expands example1 so that one of the EdgePlacement's "what predicate" explicitly matches a Namespace object.
Fixes #1226
=> 🐛 Consistency wrt dynamicDuo.preInformer

inner-scripts/kubestellar, overlap-scripts/kubectl-kubestellar-ensure-wmw
This PR reproduces the kube-bind README.md scenario, but inside our kubestellar deployment's init container, via some initial scripting.
After `helm install`, I checked the syncing of a mangodb object between `wmw1` and `espw` to make sure it behaves as expected, including all CRUD operations.
/cc @ezrasilvera
=> ✨ Reproduce kube-bind example for wmw1 and imw1 in the init container

pkg/syncer/clientfactory/client.go, pkg/syncer/clientfactory/clientfactory.go, pkg/syncer/syncers/downsyncer.go, test/e2e/kubestellar-syncer/syncer_update_status_test.go, test/e2e/kubestellar-syncer/testdata/update-status/non-subresource/sample-crd-cr.yaml, test/e2e/kubestellar-syncer/testdata/update-status/non-subresource/sample-crd.yaml, test/e2e/kubestellar-syncer/testdata/update-status/non-subresource/sample-subresource-crd-cr.yaml, test/e2e/kubestellar-syncer/testdata/update-status/non-subresource/sample-subresource-crd.yaml, test/e2e/kubestellar-syncer/testdata/update-status/non-subresource/status.yaml, test/e2e/kubestellar-syncer/testdata/update-status/non-subresource/syncer-config.yaml
MCAD has fixed to move `status` field of [appWrapper](https://github.com/cwiklik/multi-cluster-app-dispatcher/blob/mcad133/config/crd/bases/mcad.ibm.com_appwrappers.yaml) in subresource since v1.33. In the previous versions (at least before v1.31), the `status` hadn't been subresource. Such `status` can not be updated by [UpdateStatus method.](https://github.com/kubernetes/client-go/blob/v0.28.3/dynamic/interface.go#L36C4-L36C4) In order to address this issue, we made a tentative fix so that we use UpdateStatus method for built-in k8s resources while just [Update method](https://github.com/kubernetes/client-go/blob/v0.28.3/dynamic/interface.go#L35). (The corresponding git issue is   https://github.com/kubestellar/kubestellar/pull/947/files#diff-8f3c8f861fc2c427af64605adf617851b657a18cb8518 …
=> :bug: support status update for both cases of subresource and non subresource

docs/content/common-subs/required-packages.md
Restore notes about installing go as a prerequisite if the user intends to build kubestellar locally
Instructions for all OS tabs were added to the file
Fixes #
=> :book: Restore and Update installation info for go in required packages documentation

docs/content/Coding Milestones/PoC2023q1/example1.md
This PR updates the example1 script to wait for the expected ReplicaSet status rather than fail if it is not there at once.
Fixes #1234
=> 🐛 Make example1 wait for readyReplicas==1

docs/content/common-subs/install-helm-test.md
This PR makes the user-quickstart-test use the local copy of the helm chart rather than fetch one from the repo.
Fixes #
=> ✨ Test the local helm chart rather than a released one

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-4.md, pkg/apiwatch/apibindings.go, pkg/apiwatch/crds.go, pkg/apiwatch/resources.go, pkg/placement/apiwatch-map-provider.go, pkg/placement/binding-organizer.go, pkg/placement/doc.go, pkg/placement/slices.go, pkg/placement/what-resolver.go
This PR modifies the meaning of the downsync part of the "what predicate" in an EdgePlacement to implicitly include `CustomResourceDefinitions` and `APIBinding` objects that define the kinds of other selected objects.
This PR also makes the meaning downsync part of the "what predicate" exclude the things that match upsync part.
I think this addresses the concerns behind #1064 and #1080.
=> ✨ Add implicit selection of CRDs, APIBindings

.secrets.baseline, go.mod, pkg/cliplugins/kubestellar/syncer-gen/edgesync.go
- Fix syncer-gen (`kubectl kubestellar syncer-gen`) to generate the service account token for the service account for Syncer to connect to MBS for K8Ss environments that no longer generate SA token automatically.
(Thanks Paolo for giving the manual sequences.)
I verified in two kcp environments (regular k8s and k8s compounded in kubestellar v0.12.0 where workspace is configured so that SA token is not generated automatically) that the generated kubeconfig can be accessible to MBS.
Fixes #
=> :bug: fix syncer-gen to generate SA token for later K8Ss that no longer generate SA token automatically

core.Dockerfile, inner-scripts/kubestellar, overlap-scripts/kubectl-kubestellar-ensure-mbw, overlap-scripts/kubectl-kubestellar-ensure-wmw
This PR, along with previous PRs, finishes step 2 of the 'Use kube-bind' section listed in #1208.
Just a partial copy of that list:
1. the KS container image (used by all KS containers) should include the KB needed executables
2. Setup scripts that build the ESPW, WDS, and IS should be changed to:
- Run dex,
- ESPW: Run backend engine + import all KS CRDs + add KB export label + import the KB CRDs
- IS, WDS: Run konnector, bind all KS resources
=> ✨ Kube-bind KubeStellar resources for IMWs, WMWs, and MBWs

.gitignore, core.Dockerfile, docs/content/common-subs/build-syncer-image.md
This PR changes `core.Dockerfile` to suppress the golang version check in the `make innerbuild`. This is needed because RedHat recently updated what `dnf` in the `redhat/ubi9` image finds when asked to install `golang`, from release 1.19.something to 1.20.10, causing the aforementioned version check to fail.
This PR also makes a few improvements in building and testing: add the temp script generated by docs-ecutable to .gitignore; adjust the way the syncer image is recursively built to work more broadly.
Fixes #
=> 🐛 Make core.Dockerfile accept advance in golang version

docs/content/Coding Milestones/PoC2023q1/kubestellar-syncer-subs/kubestellar-syncer-1-syncer-gen-plugin.md
Also explain in the text how it is outdated.
This PR updates the syncer doc so that (a) the text briefly outlines how part is outdated and (b) the outdated part is no longer docs-ecuted.
Fixes #
=> 🐛 Stop executing outdated part of syncer doc

bootstrap/bootstrap-kubestellar.sh, bootstrap/install-kcp-with-plugins.sh, core.Dockerfile, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md, outer-scripts/kubectl-kubestellar-prep_for_syncer
This PR is #1249 but without the problematic merge of `main` into the PR's branch. I also added a commit that updates example1 to use the patched kcp when deploying bare processes.
Fixes #1248
=> 🐛 Rebased update bootstrap and container image to use the patched kcp 0.11

docs/content/Getting-Started/user-quickstart-test.md, docs/content/common-subs/install-helm-test.md, pkg/placement/declarations.go, pkg/placement/map-types.go, pkg/placement/marshal.go, pkg/placement/what-resolver.go, pkg/placement/where-resolver.go, pkg/placement/workload-projector.go
This PR extends the test user quickstart to exercise a downsynced ServiceAccount object.
This PR also replaces the use of brew to get user executables with building the local sources and fetching a patched kcp release archive. This is the last step in the campaign to address #1060 .
This PR also reacts to a change snuck in through an earlier update to `go.mod`, advancing the required version of `klog/v2` (from v2.70.1 to v2.100.1) through a big change (https://github.com/kubernetes/klog/pull/375) in the way it logs `any` values. Now they are logged by marshaling as JSON! Previously those values were rendered with `fmt.Sprintf("%v", .)`. This klog change means that every private field of a struct being logged is now invisible in the log. This PR changes many structs to make their fields …
=> ✨ Make test user quickstart exercise ServiceAccount

space-framework/pkg/msclientlib/client.go, space-framework/pkg/msclientlib/controller.go
Today the space aware client can return space config by space name. This PR will add an API to return space config by reference that is set in space object annotation. This will allow us to use kube-bind special namespace which is set for service provider resource after binding, to get config for the consumer space that owns the resource.
We assume that there is one to one mapping between service provider and consumer space.
Fixes #
=> :sparkles: Get space config by reference in annotation

pkg/apis/edge/v2alpha1/edge-placement.go, pkg/placement/binding-organizer.go, pkg/placement/declarations.go, pkg/placement/dummies.go, pkg/placement/set-binder-test.go, pkg/placement/what-resolver.go, pkg/placement/what-resolver_test.go, pkg/placement/workload-projector.go, pkg/syncer/syncers/downsyncer.go
This PR makes the placement translator respect the create-only annotation introduced in #1099 .  This will allow us to go back to using kcp v0.11.0, which is good because kube-bind depends on some of the functionality that is disabled in our patched version of kcp.
This PR also moves the declaration of the annotation key into the relevant API file, because it is part of the interface.
This PR also makes the code consistently decode the annotation by comparing its value to "false".
This is part of the campaign in #1274
=> 🐛 Make placement translator respect create-only setting on object

bootstrap/bootstrap-kubestellar.sh, bootstrap/install-kcp-with-plugins.sh, core.Dockerfile, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-start-kcp.md, docs/content/Coding Milestones/PoC2023q1/outline.md, docs/content/Getting-Started/user-quickstart-test.md, pkg/cliplugins/kubestellar/syncer-gen/edgesync.go
This PR undoes most of #1256, to revert to using plain kcp v0.11.0 instead of the patched variant that disables the Token controller for ServiceAccounts.
This is part of the campaign #1274
=> 🌱 Revert to plain kcp

outer-scripts/kubectl-kubestellar-deploy, outer-scripts/kubectl-kubestellar-prep_for_syncer
This PR updates the default image references to use the tag `release-0.15`. I recently built syncer and core images from `main` as it is at the moment, commit c414165a9335d47a067bf22ccfcabe05c164457f, and added the `release-0.15` tag to them.
Fixes #
=> 🌱 Update default image refs to release-0.15 tag

hack/inspect-image.py
This PR adds a utility in hack/ for fetching the manifests for all the tags of a given image (repository). This is better than `curl` or `wget` of just the first page of tags, and takes the extra step of fetching the associated manifests.
Fixes #
=> ✨ First draft of image repo listing utility

pkg/placement/workload-projector.go
A very minor function-naming fix targeting a typo located while reading code 😃
=> :sparkles: minor typo fix

config/crds/edge.kubestellar.io_singleplacementslices.yaml, config/exports/apiexport-edge.kubestellar.io.yaml, config/exports/apiresourceschema-singleplacementslices.edge.kubestellar.io.yaml, pkg/apis/edge/v2alpha1/single-placement.go
Typo fix in a comment. 
This API is imported as `logicalcluster`, and that was the intention of Mike.
=> :sparkles: comment typo fix

pkg/kbuser/object_ids.go, pkg/kbuser/space_ids.go, pkg/kbuser/space_ids_test.go
This PR adds the implementation of the ID mapping support for users of kube-bind documented in #1289 .
Fixes #
=> ✨ Add kube-bind ID mapping support

cmd/mailbox-controller/controller.go, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md, inner-scripts/kube-bind, inner-scripts/kubestellar, outer-scripts/kubectl-kubestellar-prep_for_syncer, overlap-scripts/kubectl-kubestellar-ensure-mbw, overlap-scripts/kubectl-kubestellar-ensure-wmw
This PR makes the kube-bind cluster namespace available for the mailbox controller go code to consume. The cluster namespace will be available at the time of the 1st successful binding, of any CRD offered by the provider.
=> ✨ Parse the kube-bind cluster namespace at binding time

scripts/overlap/kubectl-kubestellar-ensure-wmw
This PR will add binding for singleplacementslices in kubectl-kubestellar-ensure-wmw script.
Fixes #
=> :sparkles:Add bind for singleplacementslices in WMW

core.Dockerfile, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
This PR uses a hot fix of kube-bind to sync labels.
The fix lives in the `syncmore` branch of my fork of kube-bind.
Tested it using example 1 locally:
```
ubuntu@ip-172-31-67-225:~$ kc ws tree
.
└── root
├── compute
├── espw
├── imw1
├── rzfwtmtzwqwwpog8-mb-52542adf-e1e9-4501-8b28-8a7612d9644d
├── rzfwtmtzwqwwpog8-mb-e4318a18-e02b-4b5b-af88-67e47c610a7d
├── wmw-c
├── wmw-s
└── wmw1
ubuntu@ip-172-31-67-225:~$ kc ws root:imw1
Current workspace is "root:imw1".
ubuntu@ip-172-31-67-225:~$ kc get synctarget.edge
NAME      AGE
florin    3m48s
guilder   3m46s
ubuntu@ip-172-31-67-225:~$ kc label synctarget.edge florin time="0248"
synctarget.edge.kubestellar.io/florin labeled
ubuntu@ip-172-31-67-225:~$ kc ws root:espw
Current workspace is "root:espw".
ubuntu@ip-172-31-67-225:~$ kc get …
```
=> ✨ Use a hot fix of kube-bind to sync labels

.secrets.baseline, pkg/cliplugins/kubestellar/base/option.go, pkg/cliplugins/kubestellar/syncer-gen/edgesync.go
This is the PR for https://github.com/kubestellar/kubestellar/issues/1314.
- pick up the minimum codes from utility codes in kcp cliplugin to remove the dependency on kcp repo
Summary: No regressions
UT passed.
```
$ go test ./pkg/cliplugins/...
?       github.com/kubestellar/kubestellar/pkg/cliplugins/kubestellar/base      [no test files]
ok      github.com/kubestellar/kubestellar/pkg/cliplugins/kubestellar/syncer-gen        0.587s
```
Case1: the target space is kcp workspace
1. Run syncer-gen
<details><summary>Details</summary>
```
$ go run ./cmd/kubectl-kubestellar-syncer_gen/main.go cluster1 --syncer-image syncer-image:latest -o /tmp/syncer-kcp.yaml
Creating service account "kubestellar-syncer-cluster1-nmoarlfc"
Creating cluster role "kubestellar-syncer-cluster1-nmoarlfc" to give …
```
=> :seedling: Remove kcp modules from syncer-gen codes

docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-kcp.md
As the title.
@ezrasilvera I think we should keep `scripts/outer/kubectl-kubestellar-ensure-location-ex1` for now, until we see that #1265 passes example1 after this PR merges to `kube-bind` branch.
/cc @ezrasilvera
=> 🌱 Switch to the script that labels objects after their creation

space-framework/pkg/space-manager/provider.go, space-framework/pkg/space-manager/providerclient/client_interface.go, space-framework/space-provider/kcp/kcp.go, space-framework/space-provider/kind/kind.go, space-framework/space-provider/kubeflex/kubeflex.go
The provider secret for kcp now include two configs: one named kubeconfig which is the default config used by the space manager to access the provider, and one named incluster or external.  This is needed for kcp so we can generate the in-cluster and external secrets when creating spaces.  The applicable changes to the helm install and the other scripts will follow in #1268 .
Fixes #
=> :sparkles: add external secret ref to provider

Makefile
if one of the apis defined under `pkg/apis/` is deleted, current command `make codegen` leaves garbage generated code. 
This can be easily solved by removing generated code under `pkg/client` before the code generation.
in order to test this fix I tried the following:
1. deleted syncer config api file.
2. ran `make codegen`.
BEFORE this fix, the following screenshot is the result:
AFTER this fix, I ran the same and the following screenshot is the result:
as it can be seen in the screenshots, if this fix is not introduced, a lot of unnecessary generated code is still there even if we delete a file from the api.
Fixes #
=> 🐛 fixed make codegen to work correctly in case of deleteion from pkg/apis

.github/spellcheck/.wordlist.txt
This PR removes 'kcp' from `.github/spellcheck/.wordlist.txt`.
@clubanderson Does this PR do what you suggsted? I'm asking because I'm not 100% sure how it is going do change the behavior of our CI. If I can get some more explanations that will be great. Thank you.
=> 🌱 Remove 'kcp' from .wordlist

config/crds/edge.kubestellar.io_edgeplacements.yaml, config/exports/apiexport-edge.kubestellar.io.yaml, config/exports/apiresourceschema-edgeplacements.edge.kubestellar.io.yaml, pkg/apis/edge/v2alpha1/edge-placement.go
This PR fixes an editing oversight in #1202, which modifies the EdgePlacement API.
_This_ PR is backwards compatible.
Fixes #1296
=> 🐛 Mark DownsyncObjectTest.APIGroup as optional

.github/workflows/docs-ecutable-example1.yml, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-1a.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-2.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-stage-3.md
This PR changes example1 so that the controller logs go to /tmp files and are dumped at the end of a CI run.
Fixes #
=> 🌱 Dump example1 verbose logs at the end of CI

scripts/inner/kubestellar-kube-bind
This PR tries to better handle errors when `kubectl bind` is called in the `kubestellar-kube-bind` script.
It resolves #1416.
=> ✨ Better error handling of `kubectl bind`

docs/content/Coding Milestones/PoC2023q1/commands.md, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-teardown.md, docs/content/common-subs/teardown-the-environment.md, scripts/outer/kubectl-kubestellar-remove-wmw
This PR updates some scripting that deletes Space objects to supply the missing specification of the namespace holding the Space object.
This PR also removes some obsolete commands from `docs/content/common-subs/teardown-the-environment.md`.
Fixes #1432
=> 🐛 Add missing specification of namespace holding Space

pkg/placement/main.go, pkg/placement/workload-projector.go
This PR fixes bugs in how the name of a SyncerConfig object in the KCS is handled.
Fixes #1431
=> 🐛 Fix bugs wrt name of projected SyncerConfig

hack/count-commit.sh
This PR updates the hack/count-commit.sh script to add `kubestellar-kube-bind-logs/` and `build/` to the directories not counted.
Fixes #
=> 🐛 Also don't count kubestellar-kube-bind-logs/ and build/

hack/count-commit.sh, scripts/inner/kubestellar-kube-bind
In this PR, the configmaps are created before doing `kubectl bind apiservice`, so that the problem documented in #1452 can be avoided.
=> ✨ Create configmap before binding

cmd/kubestellar-where-resolver/cmd/where-resolver-cmd.go, cmd/kubestellar-where-resolver/options/options.go, cmd/mailbox-controller/main.go, cmd/placement-translator/main.go, pkg/placement/what-resolver_test.go, space-framework/cmd/space-client-test/main.go, space-framework/pkg/msclientlib/client.go, space-framework/pkg/msclientlib/controller.go
This PR introduces new boolean flag for KubeStellar controllers. This flag indicates whether a controller needs external or in-cluster access to the spaces. The flag value is `true` for external, or default `false` for in cluster access.
Fixes #
=> :sparkles: Add cli flag for external access to space provider

pkg/apiwatch/definition-tracking.go, pkg/apiwatch/resources.go
Also simplify a for loop.
This PR fixes a bug in the apiwatch package, where it was incorrectly assuming that when a discovery call returns an error the associated data structure(s) are empty. That meant that one problematic API group would make them all disappear.
This PR also simplifies a loop statement to stop the nagging from linters.
Fixes #
=> 🐛 Don't ignore available discovery results in err case

space-framework/pkg/space-manager/provider.go, space-framework/pkg/space-manager/reconcile_space.go
use finalizers by the dedicated GetFinalizers/SetFinalizers functions and not directly.
this is the best practice for working with objects that implements the `meta` interface.
Fixes #
=> 🌱 update the use of ObjectMeta Finalizers in space framework

cmd/mailbox-controller/controller.go, docs/content/Coding Milestones/PoC2023q1/outline.md, pkg/kbuser/object_ids.go, pkg/placement/what-resolver.go, pkg/placement/where-resolver.go, pkg/placement/workload-projector.go, pkg/where-resolver/reconcile_on_edgeplacement.go, pkg/where-resolver/reconcile_on_location.go, pkg/where-resolver/reconcile_on_synctarget.go
this return value wasn't used anywhere in the code. in case the need arises in the future, the original function was commented out.
the namespace of the original object wasn't used anywhere in the code. 
in case the need arises in the future, the original function was commented out.
Fixes #
=> 🌱 updated kube bind `AnalyzeObject` func not to return the namespace of the original object.

scripts/inner/kubestellar-kube-bind
This PR removes the check/cleanup of one line of unwanted text in the 'request file' for `kubectl bind apiservice`.
These was a bug in the `autobind` branch in my fork of kube-bind, which emits the unwanted text. That bug is now fixed, so we don't need this check any more.
=> 🌱 Remove the check and cleanup of the request file

pkg/pluggable-transport-where-resolver/README.md, pkg/pluggable-transport-where-resolver/controller.go, pkg/pluggable-transport-where-resolver/reconcile_on_edgeplacement.go, pkg/pluggable-transport-where-resolver/reconcile_on_location.go, pkg/pluggable-transport-where-resolver/reconcile_on_synctarget.go, pkg/pluggable-transport-where-resolver/store.go
Duplicated where-resolver in order to modify to work with EdgePlacementDecision resources, without making conflicts with existing code. Refer to the new package's README for more info.
=> :sparkles: preparation for work on where-resolver for pluggable transport

core.Dockerfile, docs/content/Coding Milestones/PoC2023q1/example1-subs/example1-post-provider.md
Previously, kube-bind binaries are built from three different branches from waltforme/kube-bind, namely `autobind`, `syncmore` and `main`. Now the three branches are consolidated into one branch `kubestellar`.
With that, we first simplify the builds in example1.
Next, on the `kubestellar` branch, images were built for the kube-bind binaries. In `core.Dockerfile`, we then use the prebuilt kube-bind images to accelerate the build of kubestellar core image. Also, we use a prebuilt dex image for the same reason.
Note that the prebuilt kube-bind images are multi-platform images, including ppc64le, so #1487 is resolved.
A side effect of this PR is the reduced build time for `make kubestellar-image`, which is now roughly half an hour on my setup.
```
[+] Building 2060.3s (139/139) FINISHED …
```
=> ✨ Use prebuilt images for kube-bind related binaries

cmd/mailbox-controller/controller.go
When calling kube-bind from within the mailbox-controller we should assume it is done in-cluster.  If kubestellar is running as processes on a host, rather than as an image, then the in-cluster will have no effect since external==in-cluster in such a scenario.  
Fixes #
=> ✨ kube-bind is in-cluster when called from mailbox-controller

space-framework/pkg/space-manager/reconcile_space.go
best practices is to use the Get/Set functions instead of ObjectMeta directly.
in addition, in order to check whether an object has marked for deletion, one should use the built-in IsZero() function
Fixes #
=> 🌱 removed the use of ObjectMeta directly in space-framework (part2)

core.Dockerfile
This PR uses cross-compilation instead of emulation to speed up `make kubestellar-image`.
On my MacBook with an M1 Max chip it now takes 200+ seconds to build the image:
```
[+] Building 214.7s (145/145) FINISHED                                       docker-container:kubestellar
```
The time above is now mostly consumed by `make innerbuild` --- as it should be.
The time above doesn't include the extra time to push to quay.io. Pushing time varies from machine to machine. On my MacBook at home it takes roughly 200 secnods; on my dev Ubuntu on AWS it takes roughly 100 seconds.
#1499
=> ✨ Use cross-compilation to speed up core image build

core.Dockerfile
This PR fixes a bug described here: https://github.com/kubestellar/kubestellar/pull/1509#issuecomment-1887634647
Thanks for @MikeSpreitzer 's time to try and diagnose.
I built the image with tag `git-b0b5d47a7-clean` on my Mac with M1 Max, then helm installed KS on my Ubuntu dev machine with amd64 CPU:
```
ubuntu@ip-172-31-67-225:~/kubestellar$ while ! kubectl exec -n kubestellar $(kubectl get pod --selector=app=kubestellar -o jsonpath='{.items[0].metadata.name}' -n kubestellar) -c init -- ls /home/kubestellar/ready &> /dev/null; do
sleep 10
echo -n "."
done
echo "KubeStellar is now ready to take requests"
.........KubeStellar is now ready to take requests
ubuntu@ip-172-31-67-225:~/kubestellar$ kc -n kubestellar get deploy kubestellar -oyaml | yq .spec.template.spec | grep image:
image: …
```
=> 🐛 Download yq for specific target platform

Makefile, core.Dockerfile
We have this bug because `GOOS` and `GOARCH` are not variable names in the Makefile. As a result, `make innerbuild` was always building KS binaries for the **build** platform, but not the target platform.
This PR fixes this bug.
BTW, in #1522, we saw the message `KubeStellar is now ready to take requests` from the init container. But the init container doesn't check the three KS controllers. That's why this bug was overlooked there.
To be sure the bug is fixed in this PR, following checks are done on a Ubuntu VM with amd64 CPU. The image is built on a MacBook with M1 Max chip:
```
ubuntu@ip-172-31-67-225:~$ kc -n kubestellar get deploy
NAME          READY   UP-TO-DATE   AVAILABLE   AGE
kubestellar   1/1     1            1           19m
ubuntu@ip-172-31-67-225:~$ kc -n kubestellar get po …
```
=> 🐛 Fix cross-complie for innerbuild

Makefile, test/e2e/multi-cluster-deployment/README.md, test/e2e/multi-cluster-deployment/cleanup.sh, test/e2e/multi-cluster-deployment/run-test.sh, test/e2e/multi-cluster-deployment/setup-kubestellar.sh, test/e2e/multi-cluster-deployment/workload-deployment.sh
This PR makes a few minor improvements to the one e2e test.
- Move "cleanup" from the end to the start, so that users can examine and build on the state established by the test. Modify the cleanup commands so that they nominally succeed regardless of the starting state.
- Make the scripts echo their commands, so that users can understand what is going on.
- Remove the self-referential and unnecessary instructions for how to use `git`.
- Rename `DEFAULT_KIND_CLUSTER` to `KIND_HOSTING_CLUSTER` to better describe its meaning/use.
- Rename and simplify the make target `ko-build` to `ko-build-local`, because it is only used to build an image used locally in testing and ko with podman does not really succeed to build a multi-platform manifest.
- Update the make target `ko-build-local` to …
=> 🌱 Brushup e2e 1

.github/workflows/pr-test-singleton-status.yml, .github/workflows/pr-test.yml, README.md, test/e2e/multi-cluster-deployment/README.md, test/e2e/multi-cluster-deployment/run-test.sh, test/e2e/singleton-status/run-test.sh
This PR replaces references to branch `ks-0.20` with references to branch `main` or relative references.
This is part of the merging of branch `ks-0.20` into `main`.
Fixes #
=> 🐛 Replace references to ks-0.20 with main

pkg/syncer/syncers/downsyncer.go
Syncer to avoid adding an entry to nil map
- There is a case that an object is annotated as `downsync-overwrite` in MBS but the object on WEC has empty annotation. In this case, Syncer crashed due to adding an entry to nil map at [downsyncer.go#L303](https://github.com/kubestellar/kubestellar/blob/release-0.14/pkg/syncer/syncers/downsyncer.go#L303)
We were reported that Syncer was crashed by MCAD integration teams and found that the above is the root cause.  
Fixes #
=> :bug: Fix Syncer to avoid adding entry to nil map

pkg/ocm/ocm.go, pkg/placement/controller.go, pkg/placement/manifest.go, pkg/placement/placement.go
This PR applies accurate 'managed-by' labels on Manifestworks which are delivered by the placement controller, thus handles #1541.
#1541 already clearly described the issue. Below is a visualization/example of that situation.
Closes #1541
=> ✨ Accurate labeling on ManifestWorks

Makefile
This PR attempts to restore the `deploy-docs` Makefile target, so that the `docs-gen-and-push.yml` workflow will work again.
I am not sure how to safely test this. `make serve-docs` never worked for me, and I dared not try `make deploy-docs` for fear of messing up the website.
Fixes #
=> ✨ Restore deploy-docs and serve-docs make targets

Makefile, pkg/client/client.go, pkg/crd/crds.go, pkg/util/kubeconfig.go
This PR updates the rule for ordering go-language import, putting kubeflex in place of kcp.
This PR is built on #1603 (because I have been plagued by the test flakiness) and will be rebased after that merges.
Fixes #
=> 🌱 Improved ordering of go imports

pkg/placement/placement.go
The ManifestWork object in the IMBS does not get deleted automatically when `wantSingletonReportedState: true` upon the user deleting the associated Placement object from the WDS. This corrects that bug.
Fixes #1596
=> :bug: Fix lack of singleton ManifestWork object removal upon Placement deletion

api/edge/v1alpha1/types.go, pkg/generated/clientset/versioned/typed/edge/v1alpha1/edge_client.go, pkg/generated/clientset/versioned/typed/edge/v1alpha1/fake/fake_edge_client.go, pkg/generated/clientset/versioned/typed/edge/v1alpha1/fake/fake_placement.go, pkg/generated/clientset/versioned/typed/edge/v1alpha1/placement.go, pkg/generated/informers/externalversions/edge/v1alpha1/interface.go, pkg/generated/informers/externalversions/edge/v1alpha1/placement.go, pkg/generated/listers/edge/v1alpha1/expansion_generated.go, pkg/generated/listers/edge/v1alpha1/placement.go
This PR fixes the markup of the Placement interface to tell code-generator that Placement is cluster-scoped.
Fixes #
=> 🐛 Add missing comment about Placement being not namespaced

.prow.yaml, go.mod
This PR updates the `go.mod` to require at least go 1.20, to be consistent with Kuberentes release 1.28 (which is what is imported).
Fixes #
=> 🌱 Update go version to track Kubernetes release 1.28

Makefile
This PR narrows the inputs that controller-gen looks at, so that it no longer picks up the examples that `make codegenclients` puts in `hack/tools`.
Fixes #
=> 🐛 Fix over-broad input to controller-gen

.prow.yaml
This PR updates the Prow jobs to use the infra container image that has the current point release of the minimal required version of go. This is the latest edition of the intfra container image that is available.
Fixes #
=> 🌱 Update prow jobs to use latest ghcr.io/kcp-dev/infra/build

docs/content/v0.20/packaging.md, hack/update-codegen-clients.sh
This PR adds a preflight check to hack/update-codegen-clients.sh,
objecting if the local repo pathname is not good for code-generator.
This PR also fixes a little organizational bug in `packaging.md`.
Fixes #
=> 🌱 Add preflight check to update-codegen-clients.sh

.github/workflows/docs-ecutable-example1.yml, .github/workflows/docs-ecutable-user-quickstart-test.yml
This PR adjusts when the example1 and user-quickstart-test workflows trigger, to restrict that to legacy KubeStellar. These workflows are currently disabled in the GitHub web UI and we would like to re-enable them for maintenance of legacy KubeStellar.
I do not understand GitHub workflows well enough to know whether I need to make this change to `main` or `release-0.14` or both. Unless and until I learn otherwise, I will attempt both.
This is part of issue #1585 
Fixes #
=> 🌱 Restrict CI workflows to legacy KubeStellar, for main

pkg/util/unstructured.go
1. isCRD function is using always version "v1". this is incorrect (a bug) since CRDs might have different versions. 
for example - KS CRDs are using v1alpha1 version.
2. making the getObjectGVK function simpler
Fixes #
=> 🐛 minor fix in helper functions

pkg/syncer/syncers/common.go, pkg/syncer/syncers/downsyncer.go
This is the fix for Syncer not to overwrite managedFields. This bug was discovered while performance test. Thanks @dumb0002.
(This is same change as [the first commit](https://github.com/kubestellar/kubestellar/pull/1578/commits/e48f8ea765bd796958f91cc7127a6c9e1bb95fa6) in this PR (https://github.com/kubestellar/kubestellar/pull/1578))
Fixes #
=> Fix Syncer not to overwrite managedFields

pkg/transport/generic_transport_controller.go
In #1588, the initial code that was merged into main did not handle the current state, but only the desired state.
That was done as part of splitting PRs into smaller pieces.
This PR adds the functionality of getting current state, calculating the desired state as specific in the PlacementDecision CR and converging current state to the desired state (if needed).
This PR also handled some minor points that were raised by @MikeSpreitzer as part of the code review of #1588, for example: 
- in add/remove finalizer functions the deep copy is done only if there is a need to update the object
- clean object uses deep copy in order not to update an object that was fetched using the client 
Fixes #
=> ✨ transport handling of converging actual state to the desired state

.github/workflows/docs-ecutable-example1.yml, .github/workflows/docs-ecutable-user-quickstart-test.yml
This PR adjusts when the example1 and user-quickstart-test workflows trigger, to restrict that to legacy KubeStellar. These workflows are currently disabled in the GitHub web UI and we would like to re-enable them for maintenance of legacy KubeStellar.
I do not understand GitHub workflows well enough to know whether I need to make this change to `main` or `release-0.14` or both. Unless and until I learn otherwise, I will attempt both. The complement to this PR is #1652 .
This is part of issue #1585 
Fixes #
=> 🌱 Restrict CI workflows to legacy KubeStellar, for release-0.14

api/edge/v1alpha1/types.go, config/crd/bases/edge.kubestellar.io_placementdecisions.yaml, pkg/crd/files/edge.kubestellar.io_placementdecisions.yaml
This field is required in order to trigger reconciliation in cases where the list of objects to downsync hasn't changed (their identifiers hasn't changed), but spec of at least one of the objects has changed. in such cases we need to trigger distribution of the updates changes.
Fixes #1671
=> 🐛 added `WorkloadGeneration` field to the downsync objects section of PlacementDecision

docs/content/v0.20/architecture.md
Explain that informers are started only on a subset of  ServerPreferredResources
=> 📖  clarification on architecture doc for ServerPreferredResources

.github/workflows/pr-test-multicluster.yml, .github/workflows/pr-test-singleton-status.yml, pkg/crd/crds.go, pkg/ocm/ocm.go, pkg/placement/controller.go, pkg/placement/crd.go, pkg/placement/manifest.go, pkg/placement/placement-decision.go, pkg/placement/placement-resolution.go, pkg/placement/placement-resolver.go, pkg/placement/placement.go, pkg/placement/selectors.go, pkg/util/gvk-gvr-mapper.go, pkg/util/keys.go, pkg/util/labels.go, pkg/util/unstructured.go, test/e2e/common/setup-shell.sh
Implemented PlacementDecision calculation and handling logic, alongside a few fixes
The implementation:
- Fixes a race-condition that was present in the use of gvkMapper, while also introducing gvr-mapping
- Adds a supporting struct: PlacementDecisionResolver that maintains the resolutions of all placement-decisions
- Adds handling for placement-decision objects, which includes handling out-of-sync objects and creating/updating objects when a decision is changed
- Marks code-pieces to be deleted when Nir's transport code is ready
The flow is as follows:
An object changes -> placement-decision resolutions are updated -> modified placement-decisions are enqueued to be synced by workers -> new spec is calculated and patched for each updated resolution.
~~- This PR SHOULD NOT BE MERGED~~
~~- …
=> ✨Implemented Placement-Decision Logic

go.mod, pkg/binding/controller.go, pkg/binding/crd.go, pkg/binding/placement.go, pkg/client/client.go, pkg/status/controller.go, pkg/util/kubeconfig.go, pkg/util/labels.go, pkg/util/unstructured.go
Deleted unused functions and constants, set unused function parameters to underscore.
This was done in order to remove deletion noise from the to-be-made PR for issue #1730, which will delete a lot of functions.
#1730
=> :sparkles: deleted unused code

cmd/kubestellar-operator/main.go, config/default/manager_auth_proxy_patch.yaml, core-helm-chart/templates/operator.yaml, core-helm-chart/values.yaml, pkg/binding/controller.go, pkg/binding/crd.go, pkg/binding/placement.go, pkg/status/controller.go, pkg/util/resources.go, pkg/util/resources_test.go, pkg/util/unstructured.go
Add startup option with flag `--resources` to start informers only for selected resources. This feature is mostly useful when the WDS has a large number of API resources and users want to track only a subset of resources. For example, in an OCP cluster used as WDS with ~ 380 API resources, as we recently found in issue #1697.
Also, improve logging with contextual logging for Placement and Status controllers, and fix a race condition found on Status controller that showed up in testing after enabling the `--resource` flag.
Fixes #1697
=> ✨ add startup option to select allowed resources

.github/workflows/pr-test-multicluster.yml, .github/workflows/pr-test-singleton-status.yml, docs/content/v0.20/pre-reqs.md, test/e2e/common/setup-kubestellar.sh
add step to install post-install hooks in e2e tests and upgrade kflex to v0.4.2
Fixes #1737
=> ✨ add step to install post-install hooks in e2e tests and upgrade kflex to v0.4.2

cmd/kubestellar-operator/main.go, core-helm-chart/templates/operator.yaml, pkg/binding/controller.go, pkg/binding/placement-decision.go, pkg/binding/placement.go, pkg/binding/selectors.go, pkg/crd/crds.go, pkg/status/controller.go, pkg/util/keys.go
This PR makes a few improvements in Context handling and logging.
It uses one `context.Context` created in `func main` and passed down in the usual way, instead of making many new `context.Background()` in several places.
FYI: https://go.dev/ref/spec#Receive_operator says that it is valid to apply the receive operator to a `nil` channel, and it will (as you would expect) never actually receive anything. This PR simplifies more complex code that used `Context.WithCancel` unnecessarily.
This PR switches from zap to using normal klog leveled and structured logging, getting better log messages: the timestamps have microsencond precision rather than whole second, and the source filename is mentioned.
Log statements that refer to an API object have been changed to not stringify the reference …
=> ✨ Context and Logging improvements

pkg/binding/bindingpolicy.go, pkg/binding/controller.go, pkg/ocm/ocm.go, pkg/util/labels.go, test/e2e/multi-cluster-deployment/update-delete.sh
Add an informer on managedclusters so when it changes (IUD) the BindingPolicies are re-evaluated.
Test case added to test/e2e/multi-cluster-deployment.
Fixes #1679
=> 🐛 add informer on managedclusters

pkg/util/unstructured.go, test/e2e/common/setup-kubestellar.sh
This PR changes the explicitly coded API group for WorkStatus to `control.kubestellar.io`.
Also updates the helm chart for status addon (in the e2e tests) which incorporated the 'original' WorkStatus API group change.
Fixes #1701.
=> ✨ Change the explicitly coded API group for WorkStatus

docs/content/v0.20/architecture.md, pkg/transport/cmd/generic-main.go, pkg/transport/cmd/options.go
This PR moves the generic transport controller code that was in `cmd/` to `pkg/transport/cmd/`.
This PR also updates the architecture document to be a little more explicit about the structure here.
Fixes #1750
=> 🌱 Refactor and rename common part of transport controller

test/e2e/multi-cluster-deployment/update-delete.sh
This PR fixes a new section of the multi-cluster-deployment E2E test, removing quoting that captured spaces where that is not appropriate.
Fixes #
=> 🐛 Remove troublesome quoting

config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml
This PR fixes the kustomization file that gets invoked by `make chart`, to keep putting the `-v=2` among the command line arguments of the kubestellar controller-manager.
This PR also updates the _other_ file that looks like a customization file for the same Deployment to point the reader to the kustomize input that matters.
Fixes #
=> 🐛 Put -v in kustomize YAML for the Helm chart

pkg/binding/bindingpolicy.go
It was overlooked during the renaming because it was not spelled correctly thus not returned by searches. Now let's fix this.
=> 🌱 Fix a typo (and replace it) for the binding controller

cmd/kubestellar-operator/main.go, pkg/binding/controller.go
This PR refactors the binding controller for testability, in two ways. One is remove the dependency on the controller-runtime `Manager` object (which was only used in the most trivial way). The other is to separate out the step of getting the CRDs installed.
This PR also adds some comments on fields in the `Controller` struct, identifying which client is use for what.
Fixes #
=> 🌱 Refactor binding controller to make it testable

.github/workflows/pr-test-multicluster.yml, .github/workflows/pr-test-singleton-status.yml
This PR updates the GitHub workflows that run the E2E tests to specify the same version of Go as is in `go.mod`.
This is good because `go vet ./...` fails in #1769 without it (something in Kubernetes needs something introduced in go 1.20).
Fixes #
=> 🐛 Update E2E test workflows with right go version

test/e2e/multi-cluster-deployment/update-delete.sh, test/e2e/multi-cluster-deployment/use-kubestellar.sh, test/e2e/singleton-status/use-kubestellar.sh
The e2e tests should be checking end to end objects rather than intermediary ones like the manifestworks.  
Fixes #
=> 🐛  e2e tests should not check internal objects

config/postcreate-hooks/kubestellar.yaml
This PR updates the kubestellar-controller-manager PostCreateHook to adjust the self-reference to refer to the upcoming release 0.20.0.
Fixes #
=> ✨ Update KCM PCH for coming release 0.20.0

docs/content/v0.20/examples.md
This PR changes the tense of the examples document, to reference its own release (adding self-reference problems) rather than a past release.
Fixes #
=> 📖 Make examples.md reference its own release instead of a past one

pkg/binding/controller.go, pkg/binding/crd.go
This PR excludes API groups, rather than groupVersions, when start informers in the binding controller.
I doubt there is a use case where in an API group, some versions should be watched and some other versions should not. So I think the group level granularity is sufficient.
Closes #1781.
=> 🐛 Exclude groups rather than groupVersions to watch

Makefile, scripts/add-helm-code.sh
Issuing ko-build-local now builds a local images with a tag that is based on the local timestamp.
The created images is loaded into the kubeflex cluster using make kind-load-image. 
The image is installed into the WDS using make install-local-chart.  The BUILD_TIME_TAG image is the one used.  
Fixes #1740
=> ✨ enable local image and chart

test/e2e/common/setup-kubestellar.sh
This PR increases the verbosity of the transport controller's log in the E2E tests. Log verbosity is good in tests.
Fixes #
=> 🌱 Make transport-controller -v=4 in E2E tests

test/e2e/common/setup-kubestellar.sh
This PR adds a `go mod tidy` into the recipe for building ks/OTP using the local version of ks/ks. This may be needed when the local version of ks/ks has different dependencies than the version that ks/OTP normally builds with. I needed it while working on #1760.
I am not a fan of this building, see https://github.com/kubestellar/kubestellar/issues/1786#issuecomment-1964802834 ; as long as we are doing this building, this extra step is sometimes needed.
Fixes #
=> 🐛 Add `go mod tidy` when building possibly-new integration

hack/run-integration-tests.sh
This PR adjusts hack/run-integration-tests.sh to fetch the etcd binary that is right for the platform where it is being used. (Previously this worked on Macs only if/where configured to automatically emulate linux-amd64.)
This PR also switches to the latest release of etcd.
Fixes #
=> 🌱 Fetch and use right etcd for platform

test/e2e/common/setup-kubestellar.sh
This PR replaces the use of wget in e2e kubestellar setup with curl.
I've added the flag -s (silent, no progress bar) and -O (write the output on file system, same as wget does).
Fixes #1833
=> 🐛 replaced wget with curl in e2e setup

pkg/transport/filtering/job.go, pkg/transport/filtering/object_filtering_map.go, pkg/transport/filtering/service.go, pkg/transport/generic_transport_controller.go, test/e2e/README.md, test/e2e/object-fields-filtering/use-kubestellar.sh
This PR updates the generic transport controller code to remove the apiserver-maintained fields of a JobSpec.
The corresponding test enhancement will be done in #1824 or follow-on.
This is an alternative to #1803, which we decided not to pursue (in favor of #1812).
Fixes #1766
=> 🐛 Add cleaning for Job objects

pkg/binding/controller.go, pkg/binding/crd.go, pkg/util/resources.go, pkg/util/resources_test.go, test/integration/controller-manager/crd-handling_test.go
Large number of CRDs (e.g. in an OpenShift cluster) may cause issues like #1705 . This PR makes several changes to handle large number or CRDs.
Three things are done in this PR:
1. Change the way that the binding controller handles CRD objects. Previously, for each CRD object, the controller computes the symmetric difference of existing resources and watched resources, in a holistic manner. That requires repeated requests to apiserver for discovery. With this change, the controller focuses on the CRD object only, in a incremental manner, which saves the requests to the apiserver and is more efficient.
2. Make the client-side rate limiter adaptive to: the number of GVRs in the apiserver when the binding controller starts. Together with 1, the client-side throttling is eliminated (see the …
=> ✨ Handle CRDs at scale

docs/content/direct/example-wecs.md, test/e2e/common/setup-kubestellar.sh
Add `--singleton` flag in `clusteradm join` command.
According to OCM docs https://open-cluster-management.io/getting-started/installation/register-a-cluster/ :
"To reduce the footprint of agent in the managed cluster, singleton mode is introduced since v0.12.0. In the singleton mode, the work and registration agent will be run as a single pod in the managed cluster."
Without `--singleton` flag:
```
kubectl --context cluster1 get deployments -n open-cluster-management-agent
NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
klusterlet-registration-agent   1/1     1            1           19h
klusterlet-work-agent           1/1     1            1           19h
```
With `--singleton` flag:
```
kubectl --context cluster1 get deployments -n open-cluster-management-agent
NAME …
```
=> :sparkles: Reduce agent footprint for OCM transport

chart/templates/controller-manager.yaml, config/manager/kustomization.yaml
This PR replaces a couple of literal tags that get replaced by the publishing workflow (`.github/workflows/goreleaser.yml`) with a statement to that effect.
Fixes #
=> ✨ Use descriptive placeholder instead of obsolete tags

pkg/binding/controller.go
In `shouldSkipUpdate` which is called in informers update events handling, the code was assuming that individual deltas get individual events. Then based on this assumption, a binding-policy would get skipped if the update involved increasing the size of the object finalizers list.
This can cause the skipping of the handling of binding-policies that satisfy the latter, while containing other changes.
This issue was found and opened by @MikeSpreitzer 
Fixes #1841
=> :bug: undo the assumption of individual delta events in binding controller

pkg/ocm/ocm.go, test/e2e/multi-cluster-deployment/update-delete.sh, test/e2e/multi-cluster-deployment/use-kubestellar.sh
This PR fixes the implementation of ocm::FindClustersBySelectors to support OR in BindingPolicy spec's `clusterSelectors`, as well as support complex label selectors such as [set-based selectors](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#set-based-requirement).
Fixes #1699
Fixes #1655
=> :bug: fix Binding cluster selection implementation

cmd/controller-manager/main.go, pkg/binding/controller.go, pkg/status/controller.go, pkg/util/unstructured.go, test/integration/controller-manager/crd-handling_test.go, test/integration/controller-manager/matching_test.go
This PR improves the status controller in two aspects.
1. Idiomatic synchronization between the status controller and the binding controller using a channel. So that the status controller doesn't need to check everyone of the per-resource informers for cache sync. Instead it proceeds immediately when the binding controller knows that all caches are synced.
2. Removal of watch to bindingpolicies.
Closes #1862
=> ✨ Improve the Status Controller

scripts/deploy-transport-controller.sh
This PR simplifies `scripts/deploy-transport-controller.sh` by removing the provision of hostAliases for `wds1.localtest.me` and `imbs1.localtest.me`. These host aliases are not needed. The init containers in the transport-controller Deployment extract the _in-cluster_ kubeconfigs for wds1 and imbs1, and these use Kubernetes Service domain names to reach the relevant apiserver. It is the _external_ kubeconfigs that use `<something>.localtest.me`. But the transport-controller belongs in the kubeflex hosting cluster (as long as we are using kubeflex at all, and those init containers are specific to using kubeflex), so the external kubeconfigs are irrelevant.
Fixes #
=> 🌱 Remove irrelevant hostAliases for transport-controller pod

docs/content/direct/example-wecs.md
This PR modifies one step in example-wecs.md to replace the use of the `watch` command with English language saying to repeat the `kubectl` command.  This is good because `watch` is not built into all OSes (for example, it is not in MacOS Sonoma) and is not listed among the prerequisites for using KubeStellar. This is the only place that the `watch` command is used in KubeStellar instructions. We _could_ instead add `watch` as a prerequisite, but I think that is more heavyweight approach.
Fixes #
=> 📖 Remove use of `watch` command in example-wecs.md

test/e2e/common/cleanup.sh
This PR removes a command from the cleanup script that is no longer needed and should have been removed as part of #1863 .
Fixes #
=> 🌱 Remove obsolete command from E2E cleanup script

pkg/binding/bindingpolicy.go, pkg/binding/controller.go, pkg/binding/crd.go, pkg/status/controller.go, pkg/util/concurrent-map.go, test/integration/controller-manager/crd-handling_test.go
This PR fixes race conditions over controller field maps that may occur due to concurrent read/writes across goroutines.
The maps are:
```
listers               map[schema.GroupVersionResource]cache.GenericLister
informers             map[schema.GroupVersionResource]cache.SharedIndexInformer
stoppers              map[schema.GroupVersionResource]chan struct{}
```
When a CRD is being handled by a worker, the following call may be made:
```
if len(toStartList) > 0 {
go c.startInformersForNewAPIResources(ctx, toStartList)
}
```
Where `c.startInformersForNewAPIResources` contains writes to these maps. 
Which means that there are 2 levels of concurrency here: different workers may handle different CRD objects, and each handling may contain executions of the above inner block.
Therefore, this PR …
=> :bug: fix race-conditions over Binding controller field maps

Makefile
This test removes the dependency of our _unit_ tests on `envtest`. This is good because our unit tests are not relying on `envtest` and because `envtest` is (a) designed to support integration tests rather than unit tests and (b) made for working with controller-runtime based controllers but our controllers are not full-fledged controller-runtime based controllers and our trend is to make them less so rather than more.
Fixes #
=> 🌱 Make unit tests not require envtest

Makefile
Currently make ko-build-local also make test which takes up to 4 minutes on CICD.  I am removing the make test part of ko-build-local.
Fixes #1893
=> ✨ remove make test from make ko-build-local

pkg/transport/generic_transport_controller.go, test/e2e/ginkgo/multiple_cluster_deployment_test.go, test/util/util.go
The background of this PR is documented in #1852. In the discussions of #1852, we agreed with an approach to (a) let the names be generated in WDSes, (b) clean the `.metadata.generateName` field in workload objects; (3) wrap the objects with name already generated for transport.
This PR implements the approach.
Fixes #1852
=> 🐛 Clean metadata.generateName in workload objects before wrapping

docs/content/direct/example-wecs.md, docs/content/direct/examples.md
This PR increases the indenting of lines in numbered list items, because Python-markdown requires at least _4_ spaces in order to recognize the nesting.
Fixes #1928
=> 📖 Increase indenting to please Python-markdown

pkg/binding/controller.go
When we call reconcile in the binding controller we log messages that use the term sync.  I changed these to reconcile as well as lowered the logging level from 2 to 4.
Fixes #1932
=> 🐛 change a reconcile log message text and level

GOVERNANCE.md, docs/content/Contribution guidelines/governance.md
This PR replaces the use of `include-markdown` in `docs/content/Contribution guidelines/governance.md` with making that file into a symlink. Apparently mkdocs was not rendering the fragment references correctly.
Fixes #1929
=> 🐛 Replace include statement with sylink, so fragment refs work

docs/overrides/main.html, docs/scripts/deploy-docs.sh
This PR updates deploy-docs.sh to consider release-0.21.1 to be the stable release, instead of 0.3.
BTW, a better fix would take the stable number from the VERSION file.
This PR is based in #1948. We can ether just merge this one, or merge that one first and then I will rebase this one.
Fixes #
=> 📖 Stable is release-0.21.1

docs/overrides/main.html
This PR changes the warning message that appears on the website in certain circumstances, to not confuse "latest" with "stable".
Fixes #
=> 📖 Remove confusion between "latest" and "stable"

.github/workflows/pr-test-e2e.yml, test/e2e/ginkgo/README.md, test/util/util.go
This PR fixes three problems with test/e2e/ginkgo. This PR removes the strange requirement to set the envar KUBECONFIG to its default value. This PR also makes the workflow that runs the test more verbose, to give contributors a chance to debug problems. This PR also adds helpful clues to the README for the ginkgo tests.
This PR addresses 3 of the 4 problems in #1951
=> 🐛 Improve test/e2e/ginkgo and its README

pkg/binding/selectors.go, pkg/status/controller.go, pkg/util/labels.go
Today the singleton status label value is set to the `BindingPolicy` name and this value is unused. This PR propose to set it to true/false and then the status controller will remove the status from the workload object when singleton status label value is set to `false` in the `WorkStatus`, and will add the status if it's `true`.
https://github.com/kubestellar/kubestellar/issues/1838
https://github.com/kubestellar/kubestellar/issues/1856
Fixes #
Together with https://github.com/kubestellar/ocm-status-addon/pull/42, should fix https://github.com/kubestellar/kubestellar/issues/1838
=> :sparkles: Set the singleton status label value to be true or false

pkg/status/controller.go, pkg/transport/generic_transport_controller.go, pkg/util/unstructured.go
1. Filter out the status when down syncing a resource. The OCM transport does not filter out the status which is not a subresource(for example Argo Workflow resource).
2. The status controller should update the status regardless to subresource or not.
Fixes https://github.com/kubestellar/kubestellar/issues/1894
=> :bug: Filter and update status if not subresource

docs/content/direct/architecture.md, pkg/binding/crd.go
This PR updates crd.go and architecture.md to catch up with our recent changes from using GVK to GVR to index informers, listers and stoppers.
=> 🌱 Updates to catch up with changes from GVK to GVR

docs/content/direct/deploy-on-k3d.md
Initial version. Would be a bit simpler with work on other components.
Fixes #
=> :book: Describe how to deploy KubeStellar on K3D-based hub and wec clusters

.github/workflows/test-latest-release.yml
Add e2e tests for the latest release.
Fixes #1590
=> ✨ e2e tests for the latest release

cmd/controller-manager/main.go, pkg/binding/controller.go, pkg/client/client.go, pkg/crd/crds.go, pkg/util/unstructured.go, test/integration/controller-manager/crd-handling_test.go, test/integration/controller-manager/matching_test.go
This PR introduces a few optimizations to address the client-side throttling.
From the binding controller's [log](https://github.com/kubestellar/kubestellar/files/14652779/cm.log), I identified two sources which independently trigger client-side throttling.
1. The API discovery of the WDS apiserver when the binding controller ensures the two KS CRDs (bindingpolicise, bindings). This source is tracked by #1916. This kind of client-side throttling is so severe that the binding controller just failed to start because of context timeout (for applying CRDs).  
1. The API discovery of the WDS apiserver when the binding controller retrieves the kubeconfigs of the WDS and the IMBS. This source is tracked by #1953.
This PR handles both sources, as follows.
1. For source 1, this PR replaces the …
=> ✨ Optimizations against client-side throttling

.github/workflows/pr-test-e2e.yml, test/util/util.go
This PR revises the CleanupWDS func used in the ginkgo-based E2E test, to use retry loops around all calls to the apiserver. This is good because it brings the test code up to par with normal kube client conventions.
The addresses one source of the flakiness noted in #1951
=> 🐛 Make CleanupWDS use retry loops

pkg/util/kubeconfig.go
Verify secret reference exist in the `ControlPlane` before accessing its fields, to prevent controller-manager crash.
Fixes https://github.com/kubestellar/kubestellar/issues/1995
=> :bug: Verify secret reference exist

pkg/binding/controller.go
The binding controller does not need to reconcile workstatuses and in some setups this can cause a race condition with the status addon. For details see https://github.com/kubestellar/kubestellar/issues/1913
Fixes https://github.com/kubestellar/kubestellar/issues/1913
=> :bug: Do not watch workstatuses in binding controller

chart/templates/controller-manager.yaml, config/manager/manager.yaml, pkg/binding/controller.go, pkg/status/controller.go
This PR increases the memory limit of the controller manager, and adjusts the verbosity levels for the logging messages from the event handlers.
Changes in this PR are built into quay.io/junatibm/controller-manager:1711835357. I tested the image, with the increased memory limit, in the same environment as #1990. The controller ran for minutes without `OOMKilled`:
```
👉 Downloads $ oc cluster-info
Kubernetes control plane is running at https://c115-e.us-south.containers.cloud.ibm.com:30829
To further debug and diagnose cluster problems, use 'kubectl cluster-info dump'.
👉 Downloads $ oc -n wds2-system get deploy,po
NAME                                             READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/kubestellar-controller-manager   1/1     1            1           8d …
```
=> 🐛 Updates for the controller manager to watch everything

docs/content/direct/examples.md
This is @francostellari 's work from PR #1985, changing examples.md to use the OTP helm chart to install the transport controller. I rebased it to remove the merges of `main` into the PR branch.
I have added a commit that restores the indentation that is needed to make the list numbering render properly for the GitHub pages (the website).
Fixes #1866
=> 📖 Make examples.md use OTP helm chart

.github/workflows/broken-links-crawler.yml, .github/workflows/docs-gen-and-push.yml
This PR makes the broken links crawler do something when invoked manually. This PR also stops the docs-gen-and-push workflow from being triggered by mere PR activity.
I have tested the former using `main` in my fork. I am unable to test the latter because it has a condition that restricts it to only running on the shared repo.
Fixes #1986 
Fixes #1987
=> 🐛 Fix triggering problems in doc workflows

Makefile
This PR updates the Makefile to specify the version of kustomize to use. This is good because the latest version does not install.
Fixes #2028
=> 🐛 Specify non-broken release of kustomize

pkg/transport/filtering/job.go
This PR continues the campaign for cleaning Job objects, by removing `spec.suspend` if it exists.
This is unsatisfying to me. This change **assumes** that `suspend: true` is present (when it is found) because the scenario is one where the WDS is _not_ denatured wrt Job execution. That is not the only possible scenario. It is also possible that the WDS _is_ denatured wrt Job execution and the user is trying to exert remote control over when the job is executed in the WEC.
This addresses part of #1936
=> ✨ Remove spec.suspend when cleaning a Job

Makefile, chart/templates/controller-manager.yaml, chart/values.yaml, cmd/controller-manager/main.go, pkg/util/kubeconfig.go
This PR generalizes the kubestellar controller-manager so that it can be told which ITS to use. This enables more than one ITS in the system!
This addresses part of #2025 . Fully addressing it would involve adding testing and making any needed doc updates.
=> ✨ Enable kubestellar-controller-manager to be told ITS name

pkg/binding/bindingpolicy.go, test/e2e/ginkgo/multiple_cluster_deployment_test.go, test/util/util.go
This PR fixes #1945. More details are documented at https://github.com/kubestellar/kubestellar/issues/1945#issuecomment-2034897896.
Fixes #1945
=> 🐛 Allow a 'singleton' bindingpolicy to select no clusters

test/util/util.go
When ginkgo tests fail in a utility function, they print the stack consisting of the failing utility function and then the calling functions.  But since ginkgo receive functions as inputs we don't actually get the precise location in each calling function.  To ensure we do see where the failure originated in, rather than print the location within the utility function, we should print the location within the caller of the utility function.  
Fixes #
=> ✨ use ginkgoHelper() to pinpoint stack failure.

docs/content/direct/examples.md, docs/content/direct/release.md, scripts/deploy-transport-controller.sh, test/e2e/common/setup-kubestellar.sh
This PR updates docs and recipes wrt two issues regarding the transport controller. One is to allow multiple WDSes, each with its own transport controller. This required putting the Helm chart instances ("releases") in distinct namespaces. The other issue is overdue updates to track releases of ks/OTP.
Fixes #2047
=> 📖 Support multiple transport controllers, doc more staggering

pkg/binding/controller.go
The resource group `scheduling.k8s.io` is currently include 1 resource called `PriorityClass` that allow users to set scheduling priority for deployments/pods. We should allow down syncing for `PriorityClass`.
Fixes #
=> :bug: Do not exclude scheduling.k8s.io group

pkg/transport/generic_transport_controller.go
This PR updates the way that the generic transport controller code logs the outcome of syncing one object reference. Now there is distinct logging for an unrecoverable error vs. one that causes a retry.
Fixes #2053
=> 🐛 Clearer logging of sync outcome

test/e2e/multi-cluster-deployment/README.md
This PR makes a couple of small fixes to the wording in `test/e2e/multi-cluster-deployment/README.md`.
I am not entirely sure I got this right. Does this test really use three OCP clusters, or one somehow do double duty?
Fixes #
=> 📖 Fix some wording in e2e/multi-cluster-deployment README for OCP

docs/content/direct/user-guide.md
This PR fixes a doc bug introduced in #2080 , and clarifies the parenthetic remark introduced there.
Fixes #
=> 📖 Remove recent breakage in template expansion example

config/postcreate-hooks/kubestellar.yaml, docs/content/direct/README.md, docs/content/direct/examples.md, docs/content/direct/release-notes.md, scripts/deploy-transport-controller.sh, test/e2e/common/setup-kubestellar.sh
This PR (a) tracks the 0.1.5 release of ks/OTP and (b) updates the ks/ks self-references in preparation for its 0.22.0-rc2.
Fixes #
=> ✨ Track OTP release 0.1.5 and prep for KS release 0.22.0-rc2

docs/content/direct/example-wecs.md, test/e2e/README.md
This PR adds remarks in the examples and E2E test docs pointing to https://kind.sigs.k8s.io/docs/user/known-issues/#pod-errors-due-to-too-many-open-files , because we have lost all pointers to that and it is still critically needed.
Fixes #2095
=> 📖 Document the need to raise OS limits for three kind clusters

docs/overrides/main.html
This PR fixes the functionality of the "version warning" banner (see https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/?h=#setting-a-default-version), so that the links correctly lead to the "stable" and "latest" aliases.
This addresses the first problem in Issue #2019 --- but only for release-0.22.0 .
=> 📖 Fix version warning for release-0.22.0

docs/overrides/main.html
This PR fixes the version navigation in the version warning banner, in branch release-0.22.0-rc3.
This addresses the first problem in Issue #2019  --- for the "release-0.22.0-rc3" version of the source of the website.
=> 📖 Fix version warning banner in release-0.22.0-rc3

.github/workflows/docs-gen-and-push.yml, Makefile, docs/README.md, docs/content/direct/release.md, docs/scripts/deploy-docs.sh
This PR changes `.github/workflows/docs-gen-and-push.yml` from fixed aliasing to parameterized aliasing. Before this change, there was a fixed policy:
- version "main" gets aliased to "latest" and "unstable";
- version "release-0.21.1" (as defined by a line in `docs/scripts/deploy-docs.sh`) gets aliased to "stable".
With this change: there is still a fixed policy of aliasing "main" to "unstable", but the aliases "latest" and "stable" are not automatically applied. Instead the workflow takes inputs that tell it whether to apply the "latest" alias and whether to apply the "stable" alias. When project maintainers decide to advance the "latest" and/or "stable" aliases, they explicitly run the workflow with appropriate parameter values. Here is an example of what that looked like when I was …
=> ✨ Parameterize deploy docs

.github/workflows/docs-gen-and-push.yml, Makefile, docs/README.md, docs/content/direct/release.md, docs/mkdocs.yml, docs/overrides/main.html, docs/scripts/deploy-docs.sh
This PR updates the policy docs and website behavior to eliminate the concept of a "stable" release and equate "latest" with the highest semver regular release.
If accepted, this PR will need to be followed up with corresponding PRs to the existing release branches so that their version warning banner will behave as intended.
This partly resolves #2019
=> 📖 Streamline release categorization

docs/mkdocs.yml, docs/overrides/main.html
This PR changes the version warning banner behavior in branch `release-0.22.0` to match the changes made to branch `main` in #2111 .
This PR only changes enough to get the needed behavior fix; the older automation in the new state gives the right result (e.g., the `latest` alias has already been set to point to `release-0.22.0`, no need to change it).
This is part of addressing #2019 .
=> 📖 Update version warning banner in release-0.22.0

docs/mkdocs.yml, docs/overrides/main.html
This PR fixes the version warning banner in the branch named `release-0.21.2`, following the pattern set in #2111 .
This is part of addressing part of #2019 .
=> 📖 Track fixes to version warning banner

docs/mkdocs.yml, docs/overrides/main.html
This PR fixes the version warning banner in the branch named `release-0.21.1`, following the pattern set in #2111 . This is what #2119 was supposed to do, but I botched that one.
Fixes #
=> 📖 Fix version warning banner in release-0.21.1

config/default/manager_auth_proxy_patch.yaml
KS chart suggests that one could set ITSName: "" to something like its1 and expect the chart to use it and pass it to the controller. However, the value does not seem used in the Helm template.
This PR updates the chart to use it: `--its-name={{.Values.ITSName}}`
Fixes #
=> 🐛 Implement usage of ITSName argument by the chart

docs/content/direct/user-guide.md
This PR makes the description of the subset of JSONPath accepted in a CustomTransform object more precise.
Fixes #2113
=> 📖 Describe the accepted JSONPath subset more carefully

config/postcreate-hooks/kubestellar.yaml, config/postcreate-hooks/ocm.yaml, docs/content/direct/examples.md, test/e2e/common/setup-kubestellar.sh
Update PCHs to include ocm status-addon and transport-plugin:
1. update ocm.yaml PCH to include a second container installing the OCM status-addon along OCM
2. update kubestellar.yaml PCH to include a second container installing the OCM transport-plugin along with the KubeStellar plugin
3. update the example.md to remove the corresponding 2 steps
Fixes #
=> ✨ Update PCHs to include ocm status-addon and transport-plugin

config/postcreate-hooks/ocm.yaml, docs/content/direct/packaging.md
Use a new version of the `clusteradm` image for ocm PostCreateHook in KubeStellar. The `clusteradm` CLI release `v0.8.2` is bundled with the OCM release `v0.13.2` which includes the fix(https://github.com/open-cluster-management-io/ocm/issues/384) for the issue https://github.com/kubestellar/kubestellar/issues/1637
Fixes https://github.com/kubestellar/kubestellar/issues/1637
=> :sparkles: Update OCM clusteradm version to 0.8.2

Makefile, test/e2e/common/setup-kubestellar.sh
This PR changes the scripting/makery to stop rendering the Helm chart into a directory named `local-chart/`; instead, it is just kept in `chart/`. This is good because it makes everything simpler.
=> 🌱 Stop rendering Helm chart into local-chart directory

docs/content/direct/user-guide.md
This PR fixes a copy-and-paste error in the user guide: the `apiVersion` was omitted from the exhibited `CustomTransform` object.
Fixes #2112
=> 📖 Include apiVersion in exhibited CustomTransform

test/e2e/ginkgo/ginkgo_suite_test.go
This PR parametrize the cluster context's name for the ginkgo e2e tests and allows for more flexibility to generate the kubeconfig file needed to run the e2e tests in other environments (e.g., ocp, etc)
Fixes #
=> ✨  Parametrize clusters context name for ginkgo

docs/README.md
After searching for quite some time while working to design better site structure, I finally figured out where the site navigation menu is hiding (in the mkdocs.yml). 
I added a note in the readme pointing out that the site navigation is also defined in the mkdocs.yml
=> :book: 📖 docs Update docs\README.md with note about navigation definition

docs/content/direct/release.md, test/e2e/multi-cluster-deployment/README.md
This PR makes two updates to documentation, which should have been done in #2137.
- Update `test/e2e/multi-cluster-deployment/README.md` on how to invoke the test.
- Update `docs/content/direct/release.md`, removing updates to the self-references removed here.
Fixes #
=> 📖 Finish doc updates wrt E2E test on OCP

test/e2e/common/cleanup.sh, test/e2e/multi-cluster-deployment/README.md, test/e2e/multi-cluster-deployment/run-test.sh
This PR improves the current e2e tests with a single script that activates both bash and ginkgo tests for kind and ocp clusters
https://github.com/kubestellar/kubestellar/issues/2104
Fixes #
=> ✨  Single script that activates e2e tests for bash and ginkgo tests

cmd/controller-manager/main.go, pkg/util/kubeconfig.go
This PR removes the spurious parameter for the name of the label that holds a ControlPlane's "type" for KubeStellar purposes (WDS vs ITS).
This PR also fixes the wait loop in pkg/util.getRestConfig to wait for the right condition, not too much and not too little.
Fixes #2131
Fixes #2133
=> 🐛 Fixes to getRestConfig and callers

cmd/controller-manager/main.go, options/client-options.go, pkg/binding/controller.go, pkg/transport/cmd/options.go
This PR adds QPS and Burst command line flags to the kubestellar controller-manager and the generic transport controller code.
This is part of addressing #2159
=> ✨ Add QPS and Burst flags to core controllers

pkg/abstract/primitive-maps.go, pkg/binding/bindingpolicy-resolution-broker.go, pkg/binding/bindingpolicy-resolution.go, pkg/status/controller.go
This PR is the first in the set that implement #2141. Once the set is completed, Combined-Status would be functional.
In this PR a new binding resolution broker is introduced, which will be used by the to-be-created `CombinedStatusResolver`.
Peek of the overall design and intentions:
- Following this broker, a `WorkStatus` broker will be PR'd. The `WorkStatus` broker will allow callback registering for a finer-granularity notification, where observers will register for changes of a single workload-object (all of its associated work-statuses)
- Using the `binging.ResolutionBroker` and the `status.WorkStatusBroker`, a `CombinedStatusResolver` will maintain:
- Per (binding) resolution,  and per `StatusCollector`, the information used of every relevant `WorkStatus`
- When a `WorkStatus` is …
=> :sparkles: CombinedStatus Calculation (part 1)

core-chart/Chart.yaml
Update core chart to use KubeFlex v0.62
Fixes #
=> ✨ Update core chart to use KubeFlex v0.62

.github/workflows/docs-gen-and-push.yml, docs/README.md, docs/scripts/deploy-docs.sh
This PR modifies the website update workflow to also render in the case of a contributor working on a branch whose name starts with "doc-". The rendering is only done if the actor involved in the github action is the repository owner. The rendering goes to the contributor's own github pages site. For example, this PR caused publication to https://mikespreitzer.github.io/kcp-edge-mc/doc-preview-enable/ .
Fixes #
=> ✨ Enable website previews

.github/workflows/pr-test-e2e.yml, go.mod, pkg/metrics/client.go, pkg/metrics/client_test.go, pkg/metrics/sampler.go, pkg/metrics/wrap_client.go, pkg/metrics/wrap_dynamic.go, pkg/transport/cmd/generic-main.go, pkg/transport/custom_transform_collection.go, pkg/transport/generic_transport_controller.go, pkg/transport/generic_transport_controller_test.go
This PR adds metrics to the generic transport controller. These added metrics are as follows.
- kubestellar_apiserver_call_latency_seconds: histogram of round trip times for calls on apiservers, broken down by: space, resource, method, and shortened error.
- kubestellar_transport_controller_binding_whats: histogram of the number of workload objects referenced in a Binding, observed whenever a Binding is sync'd.
- kubestellar_transport_controller_binding_wheres: histogram of the number of WECs referenced by a Binding, observed whenever a Binding is sync'd.
- kubestellar_transport_controller_binding_areas: histogram of the product of number of workload objects referenced and number of WECs referenced by a Binding, observed whenever a Binding is sync'd.
- …
=> ✨ Add metrics to transport controller

docs/mkdocs.yml, docs/scripts/docs-ecutable.sh
This PR removes the definitions of doc variables that are not used in any existing doc.
This partially addresses #2204
=> 🌱 Remove definitions of unused doc variables

test/e2e/ginkgo/ginkgo_suite_test.go, test/e2e/ginkgo/multiple_cluster_deployment_test.go, test/util/util.go
This PR attempts to connect ginkgo timeout to interrupting the `exec.Cmd` that runs `setup-kubestellar.sh`, so that a timeout during that script will cause the logging in SetupKubestellar to take effect. This should give a way to understand what went wrong during `setup-kubestellar.sh` when that suffers a timeout.
This is intended to partially address #2200 .
=> 🐛 Make ginkgo setup interruptable

docs/mkdocs.yml
This PR updates the docs in the `release-0.23.0` branch to remove (from the navigation tree) the dead-ends that people keep getting stuck in: setup on kind and setup on OCP. This also moves the examples ahead of the other setup instructions, because the examples have the setup instructions using three new kind clusters.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-untwist-setup-for-0230/readme/
This fixes #2213 in the branch named `release-0.23.0`. That is the one that drives what people see on the website.
=> 📖 release-0.23.0: Remove misleading empty setup content

docs/content/readme.md
This PR replaces a broken absolute link to a document with a working relative link.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-unmain/readme/#contributing
This should fix #2232 in the branch named `release-0.23.0`, which is the one that is currently the source of the default version of the website.
=> 📖 [release-0.23.0] Fix broken cross-ref to CONTRIBUTING doc

docs/content/readme.md
This PR fixes a broken link in the doc, in the `main` branch, replacing an erroneous absolute URL with a working relative URL.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-fixrel-main/readme/#contributing
This should fix #2232 in `main`. PR #2234 fixed it in `release-0.23.0`.
=> 📖 Replace broken absolute URL with working relative one

docs/content/direct/common-setup-core-chart.md
This PR fixes another wrong absolute link in the website.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-fixrel2/direct/common-setup-core-chart/#install-kubestellar-core-chart
This fixes #2235 in `main`
=> 📖 Replace another wrong absolute link with correct relative one

docs/content/direct/common-setup-core-chart.md
This fixes another wrong link.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-fixrel2-r0230/direct/common-setup-core-chart/#install-kubestellar-core-chart
This fixes #2235 in `release-0.23.0`, which is the branch that drives the current default version of the website.
=> 📖 [release-0.23.0] Replace another wrong absolute link with correct relative one

docs/README.md, docs/content/direct/common-setup-core-chart.md, docs/content/direct/common-setup-step-by-step.md, docs/content/direct/core-chart.md, docs/content/direct/microshift.md, docs/content/direct/release.md, docs/mkdocs.yml
This PR introduces some new documentation variables that align with our current release concepts of "latest regular release" and "latest release". This replaces several self-references with just one (the definition of `ks_latest_release`).
=> ✨ Introduce doc vars for releases

docs/content/direct/get-started.md
This PR tweaks the quickstart in a few ways:
- reduce the volume of prereq material;
- focus on just one usage scenarios;
- include the instruction to configure `kind` for more than two clusters.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-tweak-quickstart/direct/get-started/
None
=> 📖 Simplify quickstart wrt prereqs, scenarios

docs/content/direct/pre-reqs.md
This PR adds a section to the pre-reqs doc to cover what else the quickstart needs in its setup phase (i.e., kind) and moves the mention of docker to where it belongs.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-quickstart-prereq/direct/pre-reqs/
=> 📖 Add prereq section for quickstart install

.github/workflows/broken-links-crawler.yml
This PR updates the broken links crawler workflow to account for the fact that the branch named `main` appears as the website "version" named `unreleased-development`.
Fixes #
=> 🐛 Hack broken links crawler for main->unreleased-development

.github/workflows/broken-links-crawler.yml
This PR generalizes the broken links crawler workflow so that it works on forks; previously it only worked on the shared repo.
Tested by pushing to the `main` branch on my fork; see https://github.com/MikeSpreitzer/kcp-edge-mc/actions/runs/9721013863
I briefly goofed up on testing, creating commit 09feb2cdd07d31764176329f8a3f8a22874d5ffa in the shared repo; commit be284b14f76b8c147ec4b853ee359d9b742f2404 undoes that.
In combination with #2275 (now merged),
Fixes #2203
=> 🌱 Make broken links crawler work on forks

.github/workflows/full-broken-links-crawler.yml
This PR adds a workflow that reports all broken links to HTTPS URLs. This workflow is not triggered by pushes or PRs because it always finds a lot of stuff. Instead, it is triggered once a week (09:00 on Friday) and manually.
Fixes #
=> ✨ Add crawl for all broken links

pkg/status/controller.go, test/e2e/ginkgo/multiple_cluster_deployment_test.go
This PR adds logic to the status controller so that it handles the deletion of WorkStatus objects.
This PR also completes a pending e2e test, tracked by [this comment](https://github.com/kubestellar/kubestellar/issues/2020#issuecomment-2037539110). The test was blocked by #2020, and it's now unblocked by this PR.
Closes #2020
=> ✨ Make the status controller handle the deletion of workstatuses

pkg/transport/cmd/generic-main.go, pkg/transport/cmd/options.go, pkg/transport/generic_transport_controller.go, pkg/transport/generic_transport_controller_test.go, test/e2e/ginkgo/multiple_cluster_deployment_test.go
Shard the object containing the wrapped objects to be transported (i.e. the manifestwork) if the object is larger than a max limit which is set by default to 512K.
Marking as a WIP after talking with Nir who suggests we move the max size param into the transport controller rather than have it in the bindingpolicy. 
Fixes #2016
=> ✨ sharded manifestwork

.prow.yaml, go.mod, go.sum
Because 1.20 is no longer supported
This PR increases the required version of go from 1.20 to 1.21, because 1.20 is no longer supported.
Fixes #
=> 🌱 Bump minimum go version to 1.21

test/e2e/ginkgo/multiple_cluster_deployment_test.go
We have an existing test case for sharding wrapped objects (i.e. manifestwork objects) but it's end to end test case and does not test the manifestworks themselves.  On second thought it should.  
Fixes #
=> ✨ update shard test to check number of manifestworks

CONTRIBUTING.md, docs/README.md, docs/content/direct/acquire-hosting-cluster.md, docs/content/direct/core-chart.md, docs/content/direct/example-scenarios.md, docs/content/direct/get-started.md, docs/content/direct/init-hosting-cluster.md, docs/content/direct/packaging.md, docs/content/direct/pre-reqs.md, docs/content/direct/release.md, docs/content/direct/setup-overview.md, docs/content/direct/user-guide-intro.md, docs/mkdocs.yml
This PR makes some improvements to the website for navigation and clarity. These include the following.
- Rename "quickstart" to "Getting Started".
- Made "Getting Started" disjoint from "User Guide", because they are both listed across the top section of the website (if your browser is open wide enough) and I was told that some readers assume this means that they are disjoint.
- Rename the navigation DAG node "Setup" to "General Setup", which contrasts with "the Setup section in Getting Started".
- Made the references from the end of Getting Started to example scenario 1 use actual hyperlinks.
- Added a reference (with hyperlink) from the definitions of the relevant shell variables at the start of the example scenarios document to the concrete example in Getting Started.
- Increased the …
=> 📖 Rename quickstart to Getting Started, other doc brush up

docs/README.md, docs/content/Contribution guidelines/operations/all-macros.md, docs/mkdocs.yml
This PR removes the file `docs/content/Contribution guidelines/operations/all-macros.md` because it was only useful to hacky document authors and deemed too confusing when it turns up in search results.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-trim-710/
Fixes #
=> 📖 Remove all-macros.md

docs/mkdocs.yml, docs/overrides/home.html, docs/overrides/stylesheets/kubestellar.css
The rendering of the left menu tree in our existing rendered website only uses a color change to indicate the currently active page in the tree. This makes it less obvious to the user how they are traveling through the website.
This PR is a simple change to the css styling to make it much more obvious where a visitor is in the tree.
It also by way of example restores the previous behavior of having the getting started link in the masthead jump you to that as a page in the user guide tree
[The site may be previewed at https://kproche.github.io/kubestellar/doc-nav-emphasis/](https://kproche.github.io/kubestellar/doc-nav-emphasis/)
=> :book: Add additional emphasis to website left navigation to reduce confusion

docs/mkdocs.yml, docs/overrides/main.html
Previewable at https://kproche.github.io/kubestellar/doc-announce/
This PR is intended to clarify and remind website visitors to compare the website version they are reading with the release version of KubeStellar they are using.
It adds a notice to that effect to the upper "announce" bar on the masthead of the site.
It also makes that bar dismissible for visitors who wish to regain the real estate on their browser screen.
Finally, an explanation about the un-released development "release" is added to the yellow "outdated" warning banner.
New banner:
Old banner:
Note: before merging, the assorted commits and tweaks should be squashed. I anticipate some wording tweaks, so that has not been done yet.
=> 📖 Add multi-version warning to the header 

docs/mkdocs.yml
This PR fixes a typo in the nav tree in `docs/mkdocs.yml`.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-fixlink-720/direct/user-guide-intro/
=> 📖 Fix typo in nav tree that made broken link to troubleshooting

test/e2e/ginkgo/multiple_cluster_deployment_test.go
This PR fixes up the language in the `It` and `By` calls in the ginkgo-based E2E functional test suite to follow the grammatical norms for those calls.
This PR also fixes incorrect offsets in that test suite.
Fixes #
=> 🌱 Brush up language and offsets in ginkgo E2E test

cmd/controller-manager/main.go, pkg/binding/binding.go, pkg/binding/bindingpolicy.go, pkg/binding/controller.go, pkg/status/combinedstatus.go, pkg/status/controller.go, pkg/status/statuscollector.go, pkg/util/resources.go
This PR introduces a `controllers` flag into the controller manager, so we can specify which controller to be started by the controller manager. This feature improves the testability because it allows us to simulate the scenario where some of the controller(s) crush and restart.
=> ✨ Improve testability by allowing controllers to run independently

docs/content/direct/combined-status.md, test/e2e/ginkgo/multiple_cluster_deployment_test.go
1. Additional combined status e2e test for the `obj` identifier in CEL expression.
2. Small fix to the combined status doc.
Fixes #
=> :sparkles: More combined status testing

test/e2e/ginkgo/multiple_cluster_deployment_test.go
This PR fixes some recently introduced bugs in offsets in `ginkgo.Expect` calls.
Fixes #
=> 🐛 Fix some new offset errors

docs/content/direct/pre-reqs.md
This PR updates the prereqs doc a little regarding building container images.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-update-726a/direct/pre-reqs/
Fixes #
=> 📖 Update pre-reqs.md about container _images_

.github/workflows/goreleaser.yml, config/postcreate-hooks/kubestellar.yaml, core-chart/values.yaml, docs/content/direct/release-notes.md, docs/mkdocs.yml
This PR does two things. First is fix an oversight in the release workflow, it needed to be updated to say to use version 1.21 of go. The other thing is update the self-references in preparation for release 0.24.0-alpha.2.
Doc preview at https://mikespreitzer.github.io/kcp-edge-mc/release-prep-0240a2/readme/
Fixes #
=> 🌱 Fix goreleaser.yml and prep for release 0.24.0-alpha.2

test/e2e/ginkgo/multiple_cluster_deployment_test.go, test/util/util.go
This PR introduce test on whether status controller achieves eventual consistency w.r.t. the singleton statuses of workload objects in WDS.
The test simulates a scenario where the status controller is absent (e.g. because of a crush) for some time during which there are changes in bindingpolicies. Upon the reappearance of the status controller, it should drive the singleton statuses into their desired state.
#2285 depends on this PR.
This PR uses #2347
=> ✨ Test for status controller eventual consistency

test/e2e/ginkgo/multiple_cluster_deployment_test.go, test/util/util.go
This PR makes some improvements in the ginkgo E2E tests, primarily around waiting for a Deployment to have the desired number of "available replicas".
This PR also improves the `ginkgo.DeferCleanup` func for two test cases, one testing sharding of ManifestWork objects and one testing eventual consistency vs singleton status.
This PR also improves the test of ManifestWork sharding by making it read the existing args of the transport-controller container.
Fixes #
=> 🌱 Wait properly for intended Deployment availability

pkg/transport/cmd/generic-main.go, pkg/transport/cmd/options.go, pkg/transport/generic_transport_controller.go, pkg/transport/generic_transport_controller_test.go, test/e2e/ginkgo/multiple_cluster_deployment_test.go
This PR adds the max-num-wrapped parameter to the transport controller.  This parameter enables sharding of the wrapped object (i.e. the manifestwork) based on the number of manifests it contains.  
This PR also changes the name of the max-size-wrapped-object parameter into max-size-wrapped.
Fixes #2016
=> ✨ Shard based on number of wrapped objects in a single manifestwork

docs/content/direct/example-scenarios.md
This PR fixes an oversight in `docs/content/direct/example-scenarios.md`: a dollar sign was missing.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-update-802/direct/example-scenarios/#scenario-6-multi-cluster-workload-deployment-of-app-with-serviceaccount-with-argocd
Fixes #
=> 📖 Added overlooked dollar sign in example-scenarios.md

pkg/binding/controller.go
A bug fix to #2377 and a learning-by-doing on `DeletedFinalStateUnknown`.
Fixes #2377
=> 🐛 Handle DeletedFinalStateUnknown for binding controller's managedclusters informer

pkg/binding/bindingpolicy.go, pkg/binding/controller.go, pkg/binding/selectors.go, pkg/status/combinedstatus-resolver.go, pkg/status/controller.go, pkg/status/workstatus.go, test/e2e/ginkgo/README.md, test/e2e/ginkgo/ginkgo_suite_test.go, test/e2e/ginkgo/multiple_cluster_deployment_test.go, test/util/util.go
This PR makes various improvements to the binding controller and the ginkgo E2E test suite.
There is a bug fix regarding excessive enqueuing.
This PR adds missing calls to `ginkgo.GinkgoHelper`. This PR also replaces use of offset with use of `ginkgo.GinkgoHelper`.
This PR adds the ability to pass all allowed `setup-kubestellar.sh` flags/args through the `ginkgo` command.
The are improvements to debug logging.
Fixes #
=> 🌱 Improvements to ginkgo E2E test suite

monitoring/install-ks-monitoring.sh
This PR add specific release version for installation of monitoring tools. 
This PR address the issue reported by @MikeSpreitzer  during the installation of the pyroscope tool. Root cause: the pyroscope-agent pod was renamed in the latest release:
```+ kubectl --context kind-kubeflex get statefulset pyroscope-agent -n ks-monitoring
+ echo 'statefulset pyroscope-agent does not exist in the namespace ks-monitoring and context kind-kubeflex'
statefulset pyroscope-agent does not exist in the namespace ks-monitoring and context kind-kubeflex
+ echo 'Sleeping for 3 seconds...'
Sleeping for 3 seconds...
+ sleep 3
+ :
+ kubectl --context kind-kubeflex get statefulset pyroscope-agent -n ks-monitoring
+ echo 'statefulset pyroscope-agent does not exist in the namespace ks-monitoring and context …
```
=> 🐛  Add specific release version for installation of monitoring tools

config/default/manager_auth_proxy_patch.yaml, config/manager/manager.yaml, monitoring/configure-metrics-tools.sh
1. rename the named container port 8443 of the proxy from `https` to `metrics`
2. add `debug-pprof` port 8082 to manager container
3. add flag to set the binding address
Fixes #2360
=> ✨ Create named container port for `/debug/pprof`

docs/content/direct/core-chart.md
Fix 3 instances of `kubeflex-controller` in `core-chart.md`
Fixes #2387
=> 🐛 fix kubeflex-controller in the docs

docs/content/direct/get-started.md
This PR adds a note to the getting-started.md doc emphasizing that the reader should not ignore the Helm chart's notes about establishing the "its1" and "wds1" contexts.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-update-801b/direct/get-started/
Fixes #2372
=> 📖 Refer getting-started reader to Helm chart notes about contexts

pkg/binding/bindingpolicy-resolution.go, pkg/binding/bindingpolicy-resolver.go
This PR extends the BindingPolicyResolver interface with a method to inquire about what all the resolutions together say about singleton reported state return. This is good because it will make it easier to implement that feature.
Fixes #
=> 🌱  Add GetSingletonReportedStateRequestForObject method

api/control/v1alpha1/types.go, config/crd/bases/control.kubestellar.io_bindings.yaml, pkg/crd/files/crds.yaml
This PR updates the definition of Binding objects to explicitly say (in a way that is checked by the apiserver) that duplicates are not allowed in the lists of destinations and workload objects. This is good because it is something that we intend and the consuming code has been silently assuming.
Fixes #
=> 🌱  Update IDL to forbid duplications in BindingSpec

cmd/controller-manager/main.go, pkg/binding/bindingpolicy-resolver.go, pkg/binding/controller.go, pkg/status/binding.go, pkg/status/controller.go, pkg/status/singletonstatus.go, pkg/status/workstatus.go
This PR uses some existing data structures and logic in (also adds some to) the binding controller, to help the status controller handle singleton statuses.
Now status controller
- doesn’t have functionally duplicated code;
- doesn't have to read the `managed-by.kubestellar.io/singletonstatus` label when reconciling singleton statuses.
Fixes #
=> ✨ Improve status controller using existing assets

.github/workflows/ocp-self-runner.yml, .github/workflows/pr-test-e2e.yml, .github/workflows/pr-test-integration.yml, .github/workflows/test-latest-release.yml, .prow.yaml
This PR fixes the remaining places where CI was saying to use go release 1.22.
Fixes #
=> 🌱  Fix remaining wrong go versions in CI

cmd/controller-manager/main.go, go.mod, go.sum, options/client-options.go, options/process-options.go, pkg/binding/binding.go, pkg/binding/bindingpolicy.go, pkg/binding/controller.go, pkg/controller/run.go, pkg/crd/crds.go, pkg/metrics/wrap_client.go, pkg/ocm/ocm.go, pkg/status/combinedstatus.go, pkg/status/controller.go, pkg/status/statuscollector.go, pkg/transport/generic/cmd/generic-main.go, pkg/transport/generic/cmd/options.go, test/integration/controller-manager/crd-handling_test.go, test/integration/controller-manager/matching_test.go
This PR switches the KubeStellar controller-manager from using controller-runtime to using plain Kubernetes.
There remains some relatively isolated use of just part of controller-runtime, the non-typed client, due to https://github.com/kubestellar/kubeflex/issues/277 .
Fixes #
=> ✨ Make controller-manager use plain Kubernetes

monitoring/configuration/prometheus-pod-exempt.yaml, monitoring/configure-monitoring-wds.sh, monitoring/grafana/APIServerPriorityFairness.json
This PR configures Kubernetes API Priority and Fairness (APF) for KS monitoring tools, more precisely this PR achieves the following:
-  Create a flowschema for prometheus traffic to the WDS API server with a priority level of type `exempt` - hence, prometheus traffic will not be subject to any of the limitations imposed by APF.
-  Adds a grafana dashboard to monitor APF for WDS/ITS spaces and host cluster API server
-  Updates KS script for configuring monitoring tools to create APF flowschema for prometheus in the KS spaces. 
README file will be updated in a NEW PR. 
p.s:  the Grafana dashboard in this PR is a revised version of the grafana dashboard found in the  AWS blog in the open source community. Source: https://github.com/RiskyAdventure/Troubleshooting-Dashboards/blob/main/api-tro …
=> ✨ Adding APF for KS monitoring tools

docs/requirements.txt
Effect of this PR may be previewed at https://kproche.github.io/kubestellar/doc-autodark
Problem: The previous PR #2411, while it fixed the rendering issue for browsers in dark mode, did not respond properly to system settings for dark/light mode.
Investigation revealed that the auto-switching function was only supported in the **Material for MKDocs** theme after release 9.5.50, and our requirements.txt file was only specifying 9.1.0
This PR updates the Material theme specification to the latest release (9.5.34), and also specifies the mkdocs and other library component versions needed to support it properly.
=> :book: update requirements.txt for Materials for MKDocs theme to properly support light/dark autoswitching

.github/workflows/goreleaser.yml, .goreleaser.yaml, config/postcreate-hooks/kubestellar.yaml, core-chart/templates/postcreatehooks/wds.yaml, core-chart/values.yaml, docs/content/direct/packaging.md, docs/content/direct/release-notes.md, docs/content/direct/release.md, docs/mkdocs.yml, ocm-transport-controller-chart/.helmignore, ocm-transport-controller-chart/Chart.yaml, ocm-transport-controller-chart/templates/controller.yaml, ocm-transport-controller-chart/values.yaml
This PR finishes the functional part of the campaign to merge kubestellar/ocm-transport-plugin into kubestellar/kubestellar. More documentation work should be done (notably including the architecture document), but this PR should be functional.
This PR includes self-reference updates preparing for a test release named `0.24.0-experiment.5`.
Doc preview is at https://mikespreitzer.github.io/kcp-edge-mc/doc-tport-move-4/direct/packaging/ .
This PR is built on #2433 and I will rebase if that merges first.
=> 🌱 Use OTC Helm chart from ks/ks instead of ks/OTP

.goreleaser.yaml, docs/content/direct/packaging.md
This PR continues the campaign to merge ks/OTP into ks/ks my extending the goreleaser config of ks/ks to also build the transport controller container image.
Doc preview is at https://mikespreitzer.github.io/kcp-edge-mc/doc-tport-move-2/direct/packaging/ .
FYI, documentation on how to use `ko` from `goreleaser` can be found at https://goreleaser.com/blog/goreleaser-ko/?h=ko and https://goreleaser.com/customization/ko/ . Documentation about configuring a goreleaser "build" is at https://goreleaser.com/customization/builds/ .
This PR is built on top of #2432 and I will rebase if that one merges first.
=> 🌱 Make ks/ks build transport controller container image

.github/workflows/goreleaser.yml, .goreleaser.yaml, docs/content/direct/packaging.md, ocm-transport-controller-chart/.helmignore, ocm-transport-controller-chart/Chart.yaml, ocm-transport-controller-chart/templates/controller.yaml, ocm-transport-controller-chart/values.yaml
This PR continues the campaign of merging the ks/ocm-transport-plugin repo into ks/ks. The step here is moving where the Helm chart source is and where the packaged chart is published to.
Doc preview is at https://mikespreitzer.github.io/kcp-edge-mc/doc-tport-move-3/direct/packaging/ .
This PR is based on PR #2429 and I will rebase if 2429 merges first.
=> 🌱 Make ks/ks repo publish ocm-transport-controller Helm chart

.github/workflows/goreleaser.yml
This PR updates the goreleaser workflow to track a recent change to the Makefile regarding the variable that defines the kubestellar-controller-manager image reference.
Fixes #2440
=> 🐛 Update goreleaser to track Makefile change

config/postcreate-hooks/kubestellar.yaml, core-chart/values.yaml, docs/mkdocs.yml
This PR updates the self-references in preparation for test release 0.24.0-rc1.
This is not to say that we might not merge https://github.com/kubestellar/kubestellar/pull/2442 and/or #2444 (which tracks the [latest ks/OSA release](https://github.com/kubestellar/ocm-status-addon/releases/tag/v0.2.0-rc11)) and/or others before actually making this test release.
Fixes #
=> ✨ Update self-references for 0.24.0-rc.1 release

chart/values.yaml, config/postcreate-hooks/kubestellar.yaml, test/e2e/common/setup-kubestellar.sh
This PR generalizes the `kubestellar` PostCreateHook to take two controller verbosity parameters and the `test/e2e/common/setup-kubestellar.sh` script to pass them. This removes the need for a restriction on the those verbosity settings when using that PostCreateHook.
Fixes #2439
=> ✨ Expose verbosity controls from kubestellar PCH

.github/workflows/ocp-self-runner.yml, .github/workflows/pr-test-e2e.yml, .github/workflows/pr-test-integration.yml, .github/workflows/test-latest-release.yml
This PR updates the GitHub Actions workflows to use release 0.6.1 of kubeflex rather than 0.4.2, because 0.6.1 is now the minimum required version.
Fixes #
=> 🐛 Update the kubeflex version in the GitHub workflows

docs/mkdocs.yml
This updates the **format:** parameter for mermaid in the markdown_extensions section of mkdocs.yml to match that in the current documentation for Material for MKDocs, the theme we are using.
Doing so enables mermaid diagrams to shift their color scheme to display properly in whatever theme (light/dark) the browser is rendering the site in.
Preview at https://kproche.github.io/kubestellar/doc-fixmermaid/direct/packaging/
Fixes #2435
=> :book: Fix call to mermaid to allow it to change colors when website theme toggles dark/light

Makefile, pkg/status/workstatus.go
This PR adds a (phony) target to Makefile to make it handy to load controller manager image into a host cluster of type k3d.
Also adds FieldManager when the status controller `updateObjectStatus`.
=> 🌱 Facilitate image loading on k3d

test/performance/README.md, test/performance/workloads/performance-test-config.yaml
This PR adds the Poisson tuningset in the workload configuration for clusterloader2 - we will use the tuning set to generate the KS benchmark workloads in our experiments. 
N.B: this PR also improves the README to allow users to easily copy & past the list commands. 
Fixes #
=>  ✨ Adding Poisson tunning set for workload generation

Makefile, core-chart/templates/postcreatehooks/wds.yaml, test/e2e/common/setup-kubestellar.sh
Remove the use of Kustomizer to dynamically generate the YAML for the KubeStellar controller deployment.
Key changes:
- update the WDS PCH to have static YAML for deploying KubeStellar controller
- remove several unused targets from Makefile, including `core-chart`
- remove `config/` folder
Fixes #
=> ✨Remove Kustomizer usage to build the core-chart

.github/workflows/goreleaser.yml
Fix setting Helm chart versions in goreleaser
https://github.com/kubestellar/kubestellar/pull/2465#discussion_r1786884762
Fixes #
=> 🐛 Fix setting Helm chart versions in goreleaser

docs/content/direct/release-notes.md
This PR corrects the release notes to note that the create-only feature is not implemented yet. This PR also updates the release notes to add the problem with Job objects to every release's list of incompleteness.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/release-0.24.0/direct/release-notes/
Fixes #
=> 📖 Note incompleteness of create-only implementation

pkg/transport/generic/generic_transport_controller.go
This PR changes the generic transport controller code so that it does not thrash the finalizers of the wrapped object.
Fixes #
=> 🐛 Stop transport-controller thrashing finalizers

hack/check_pre_req.sh
This PR is a follow-on to #2272, making the check_pre_req.sh script show that `make` is also available from the XCode Command Line Tools.
Preview (although this PR makes no change to the website) at https://mikespreitzer.github.io/kcp-edge-mc/doc-more-xclt/direct/pre-reqs/ .
Fixes #
=> 📖 Note that make is in XCode CLT

docs/content/direct/release-notes.md
This PR updates the release notes to say that release 0.24.0 has an incomplete introduction of create-only and that every release (thus far) does not support Job objects properly.
Proper release notes would probably have prevented @cwiklik from wasting his time testing release 0.24.0.
=> 📖 Note incompleteness of create-only

README.md, docs/content/direct/testing.md, docs/content/readme.md, docs/mkdocs.yml
This PR makes some organizational changes to the documentation: adding a few links, removing the "Contribution Notes" vertex in the hierarchy (promoting its children), recognizing that the "For Contributors" doc is really just about testing.
Preview of website part at https://mikespreitzer.github.io/kcp-edge-mc/doc-fixlinx-1010/readme/
Fixes #
=> 📖 Improve doc linkage

core-chart/values.yaml, docs/content/direct/release-notes.md, docs/mkdocs.yml, scripts/create-kubestellar-demo-env.sh
This PR updates the self-references in preparation for release 0.25.0-rc.1.
This PR also reworks `scripts/create-kubestellar-demo-env.sh` (which is still not documented) a bit so that it needs to hold only one copy of the release version.
Website preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep-for-0250rc1/readme/
Fixes #
=> ✨ Update self-references for 0.25.0-rc.1

pkg/transport/generic/cmd/options.go
The PR changes the default value for the `--max-num-wrapped` command line flag of the generic transport controller. The old value was 9223372036854775807, a huge value that stuns the eyes does not correspond to anything reasonable. The new value is the same as the default for `--max-size-wrapped`, which is a much more sensible value. Each wrapped object will certainly require multiple bytes.
Fixes #
=> 🌱 Improve default max-num-wrapped of transport controller

api/control/v1alpha1/types.go, config/crd/patches/more_validations_in_bindingpolicies.yaml, docs/content/direct/binding.md, docs/content/direct/testing.md, pkg/crd/crds.go, pkg/crd/files/crds.yaml, test/integration/controller-manager/cr-validation_test.go, test/integration/controller-manager/crd-handling_test.go, test/integration/controller-manager/matching_test.go
This PR adds validation checking to BindingPolicy regarding the prohibition on an empty DownsyncObjectTest, and updates the statement in the API about how validation errors are reported.
This PR adds this validation in two ways, because the first way does not work and I do not understand why. Hopefully it is some small thing that can be rectified, which is why I have not abandoned it. The first technique adds some validation to the JSON schema for BindingPolicy, but the kube-apiserver accepts this extra validation without complaint but also trashes it so that it has no effect (it empties out the schemas in the array value of the `anyOf`, so they all trivially validate; the integration test displays the returned CRD, where you can see the trashed schemas). This PR has a second commit which …
=> 🐛  Check for empty DownsyncObjectTest

cmd/controller-manager/main.go, pkg/abstract/map-lock.go, pkg/abstract/map-map.go, pkg/abstract/map-to-comparable.go, pkg/abstract/map-to-comparable_test.go, pkg/abstract/map.go, pkg/abstract/primitive-map-as-map.go, pkg/binding/binding-controller.go, pkg/binding/binding.go, pkg/binding/bindingpolicy-resolution-broker.go, pkg/binding/bindingpolicy-resolution.go, pkg/binding/bindingpolicy-resolver.go, pkg/binding/bindingpolicy.go, pkg/binding/crd.go, pkg/binding/selectors.go, pkg/status/binding.go, pkg/status/singletonstatus.go, pkg/status/status-controller.go, pkg/status/workstatus.go, pkg/util/labels.go, pkg/util/unstructured.go, test/integration/controller-manager/crd-handling_test.go, test/integration/controller-manager/matching_test.go
This PR updates the KubeStellar controller-manager to do nothing with labels named `managed-by.kubestellar.io/singletonstatus`. This is good because it is not necessary to run controller internal state through API object labels.
This PR also enhances some debug logging and adds a missing FieldManager attribution.
Fixes #2420 
Fixes #2421 
Fixes #2505
=> 🌱 Stop using singletonstatus label

docs/README.md, docs/content/contribution-guidelines/operations/testing-doc-prs.md
This is a very simple PR to fix a pair of bad relative links in /docs/README.md and the "Testing website PRs" page.
Preview of the critical page at https://kproche.github.io/kubestellar/doc-fix-badlink/contribution-guidelines/operations/testing-doc-prs/
The link in question is in the very first paragraph of that page, and now that it works, it has been added back into the README.md file.
NOTE: the links only work in the rendered html pages, not when viewing the markdown on github.
=> :book: Fix bad links in the website management documentation

docs/content/direct/get-started.md, docs/content/direct/start-from-ocm.md
This PR updates the two setup recipes to use a variable that is local to the shell rather than exported to processes invoked in the recipes, to hold the KubeStellar release string. This is good because it does not leave the reader wondering whether those processes are sensitive to such an environment variable.
Fixes #
=> 📖  Use shell variable rather than environment variable

docs/content/direct/release.md, docs/content/direct/start-from-ocm.md
This PR is a bit of cleanup after #2515 . This PR does two things.
1. Use an explicit version in the reference to the OCM Quick Start.
2. Note that the upcoming release should replace the reference to KubeStellar `main` with that release.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-release-for-ocm/direct/release/
Fixes #
=> 📖  Use explicit releases instead of main

core-chart/values.yaml, docs/content/direct/release-notes.md
This PR is a replacement of #2529 because #2529 got stuck when GitHub is 'Processing updates'.
In #2529 we see
stands there for more than 1 hour.
Fixes #
=> 🌱 Default max-num-wrapped to 1 in core Helm chart

docs/content/direct/pre-reqs.md, docs/content/direct/release.md, hack/check_pre_req.sh
This PR enhances `hack/check_pre_req.sh` to know what the minimum required version of each dependency is, and check that. This PR also enhances the pre-reqs doc to list all the minimum required versions.
I had to guess at some of the version requirements.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-check-versions/direct/pre-reqs/
Fixes #2492 
This also completes the work on Issue 2491, which is already marked as complete (although I do not understand why).
=> ✨ Add version checking to the check_pre_req script

go.mod, test/e2e/ginkgo/multiple_cluster_deployment_test.go, test/util/util.go
This PR fixes the ginkgo end-to-end test cases that examine a CombinedStatus object, making them wait for the object to both exist and have the expected content.
This fixes the original complaint in #2532. I added a comment in that Issue noting another instance of the bad pattern (but not involving CombinedStatus).
=> 🐛 Examine CombinedStatus objects in wait loop

scripts/create-kubestellar-demo-env.sh
I have discovered that every so often that 1 of the cluster1 and cluster2 aliases in kubeconfig do not create propertly - I assume there is a blocking happening since both clusters are create simultaneously - to avoid this I added a retry for both clusters - not pretty, but necessary to avoid missed config
Fixes #
=> ✨ fix: sometimes cluster1 or cluster2 kubeconfig context alias does not create on the first try

.github/workflows/pr-test-e2e.yml, test/e2e/README.md, test/e2e/run-test.sh
This PR does two things. One is to change the GitHub Actions workflow that runs the ginkgo E2E test, to use `--fail-fast`. This is good because it means that the state dumping after the test shows the problem state.
The other thing is to generalize the `test/e2e/run-test.sh` script so that it can be given `--fail-fast`. This is good because rushing past a failure destroys state that a contributor would want to examine.
Fixes #
=> 🌱  Give some love to ginkgo --fail-fast

core-chart/templates/postcreatehooks/its.yaml, docs/content/direct/get-started.md, scripts/create-kubestellar-demo-env.sh, test/e2e/common/setup-kubestellar.sh
This PR updates the setup recipes to wait for the completion of the initialization of the ITS as an OCM hub cluster. This is good because there was a timing splinter that caused grief and confusion (e.g., #2549).
This PR updates all copies of the setup recipe to wait in the same way. This way has the advantage of breaking as few abstraction layers as is required. A Helm chart does not give the author a way to program a general wait, so our recipe has to understand what is in the core Helm chart. A KF PCH also does not give the author a way to program a general wait, so our recipe has to understand what is in the "its" PCH. This PR adds `--wait` to the `clusteradm init` command, so that Job "completion" will imply completion of the OCM hub setup.
For a preview of a new section, see …
=> 🐛  Add/fix wait for ITS to finish OCM setup

docs/content/direct/get-started.md, docs/content/direct/start-from-ocm.md
This PR fixes the reference from the start-from-ocm document to the modified OCM quickstart script.
This PR also adds a warning to that doc about cleanup.
This PR also restores the recommendation to `set -e`.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-fix-ocm-ref/direct/start-from-ocm/
Fixes #
=> 🐛  Fix reference to modified OCM quickstart script

hack/check_pre_req.sh
This PR changes the check-pre_req.sh script so that it does not use `jq`. This is good because it removes a circularity, needing a prerequisite in order to run the script that checks prerequisties.
Fixes #2554
=> 🐛  Change check_pre_req.sh script to not use jq

docs/content/direct/start-from-ocm.md, scripts/ocm-local-up-for-ingress.sh
This PR removes the unnecessary and non-functional `dirname` from the `ocm-local-up-for-ingress.sh` script, so that it can be used in curl-to-bash style.
This PR also adds a reference to the OCM Quick Start page, for easy reference by the reader.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-fix-2555/direct/start-from-ocm/
Fixes #2555
=> 🐛  Remove problematic `dirname` from ocm-local-up-for-ingress.sh

docs/content/direct/release.md, scripts/create-kubestellar-demo-env.sh
This PR fixes the KubeStellar version number in `scripts/create-kubestellar-demo-env.sh` and updates the release process document to include that in the list of self-references to update.
Fixes #
=> 🐛  Fix KS version in create-kubestellar-demo-env.sh

docs/content/direct/release.md, scripts/create-kind-cluster-with-SSL-passthrough.sh, scripts/create-kubestellar-demo-env.sh, test/e2e/common/setup-kubestellar.sh
This PR improves the demo environment creation script in the following ways.
- The script retains, and displays if there is a failure, the logging from `kind`.
- The whole script fails if any WEC creation fails.
- This PR adds a wait for the update-cluster-info Job to complete before running the `clusteradm join` commands, because the latter depends on the former.
- Change `scripts/create-kind-cluster-with-SSL-passthrough.sh` to explicitly specify the kubeconfig context in each command, so that this script can be used in parallel with other activity that sets/requires the current context to be something else.
- Change `create-kubestellar-demo-env.sh` to create the hub cluster concurrently with creating the WECs, for improved total execution time.
- Use the `check_pre_req.sh` script from …
=> 🐛  Various fixes and improvements to create-kubestellar-demo-env.sh

scripts/create-kubestellar-demo-env.sh
This PR does some clean-up of #2546 , which --- as a hack to enable testing --- referenced its own copy of `scripts/create-kind-cluster-with-SSL-passthrough.sh`. This PR changes that to reference the copy in the `main` branch. When making the next release, the reference will be changed again, to reference the released version.
Fixes #
=> 🌱  Changed create-kubestellar-demo-env.sh ref from me to main

docs/content/direct/known-issues.md, docs/content/direct/knownissue-collector-miss.md, docs/mkdocs.yml
This PR adds an entry in the "known issues" compendium for a botched reference from a Binding[Policy] to a StatusCollector.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-collector-miss/direct/knownissue-collector-miss/
This PR does _not_ resolve Issue #2574 . Resolving that issue _might_ make it unnecessary to list this particular "known issue", but that would be new work that should not merge before the next release.
=> 📖  Add known issue for botched StatusCollector reference

scripts/create-kind-cluster-with-SSL-passthrough.sh
This PR increases the timeout that `scripts/create-kind-cluster-with-SSL-passthrough.sh` uses when waiting for the nginx Ingress controller to become ready. This is good because I observed the pull to take about 140 seconds, which is longer than the current timeout of 90 seconds.
Fixes #2573
=> 🐛  Increase timeout wainting for nginx Ingress controller

docs/content/direct/combined-status.md
This PR revises the wording in the examples section of the doc on "combined status", to make it clearer that what is exhibited is the contents of the `spec` section. This was prompted by someone having to ask me about this.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-spec/direct/combined-status/#examples-of-using-the-general-technique
Fixes #
=> 📖  Be more explicit about "spec" of `CombinedStatus`

docs/content/direct/get-started.md
This PR reorganizes the Getting Started page a bit, to follow @KPRoche's outline shown in https://github.com/kubestellar/kubestellar/pull/2584#issuecomment-2476820172 . This is good because it puts the fast path first without reducing what can be learned from the whole page.
This version also draws on the version in release 0.25.0 (https://docs.kubestellar.io/release-0.25.0/direct/get-started/).
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-demo-script/direct/get-started/
Fixes #
=> 📖  Reorganize Getting Started Page

docs/content/direct/combined-status.md
This PR fixes the indentation in the source for https://docs.kubestellar.io/release-0.25.0/direct/combined-status/#queryable-objects so that the intended nesting shows up.
Fixes #
=> 📖  Fix nesting in listing of queryable objects in combined status

test/e2e/common/setup-kubestellar.sh
This PR fixes the setup-kubestellar.sh script to unconditionally overwrite any pre-existing setting in kflex's kubeconfig extension that holds the name of the hosting cluster context.
Fixes #2587
=> 🐛  Make setup-kubestellar overwrite kflex hidden state

docs/content/direct/release-notes.md
This PR updates the bug lists in the release notes to mention the two transport controller bugs that I have been thinking about (one was fixed in #2589, the other has not been fixed).
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-xc-bug/direct/release-notes/#remaining-limitations-in-0250-and-its-candidates
Fixes #
=> 📖  Document transport controller bugs in release notes

scripts/create-kind-cluster-with-SSL-passthrough.sh, scripts/create-kubestellar-demo-env.sh
This PR increases the timeouts in `scripts/create-kind-cluster-with-SSL-passthrough.sh` and `scripts/create-kubestellar-demo-env.sh` to a day, because we are getting reports of very long times to pull the images. Note that `kubectl wait` insists on having _some_ timeout.
Fixes #
=> 🐛  Increase scripting timeouts to 1 day

docs/content/direct/get-started.md
This was supposed to be switched to a versioned reference at the point of first release of the new script.
This PR fixes an oversight that happened when first documenting the `create-kubestellar-demo-env.sh` script. The versioned document should have used a versioned reference to the script.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-overlooked-version/direct/get-started/#run-the-script
Fixes #
=> 📖  Versioned reference to create-kubestellar-demo-env.sh

scripts/kubestellar-snapshot.sh
Provide a new script to take a snapshot of KubeStellar deployment: `kubestellar-snapshot.sh`
```shell
Usage: ./kubestellar-snapshot.sh [--kubeconfig|-K <filename>] [--context|-C <name>] [--verbose|-V] [-X]
--kubeconfig|-K <filename> use the specified kubeconfig
--context|-C <name>        use the specified context
--logs|-L                  save the logs of the pods
--yaml|-Y                  save the YAML of the resources
--verbose|-V               output extra information
--version|-v               print out the script version
-X                         enable verbose execution of the script for debugging
```
Example of usage after running `test/e2c/run_test.sh`:
```shell
$ ./kubestellar-snapshot.sh -V -Y -L
KubeStellar Snapshot v0.10
Script run on 2024-11-07_23:21:53
Checking script …
```
=> ✨Provide a script to take a snapshot of KubeStellar deployment

.github/workflows/spellcheck_action.yml
This PR changes the condition under which an attempt is made to save the spell checking output to a workflow artifact. This PR removes the restriction to the "kubestellar" organization, so that contributors can also get these artifacts for their own branches. This PR allows the saving to be attempted even if the spell checking finds errors.
Fixes #2628
=> 🌱  Always save spellcheck output to workflow artifact

scripts/create-kind-cluster-with-SSL-passthrough.sh
Introduce a `--prefetch` argument to prefetach nginx ingress images to the kind cluster.
NOTE:  the sha256 portion of the image tags needs to be removed from the nginx YAML before applying it because the images loaded into the kind cluster will have a different sha256. The YAML would keep pulling new images even though we loaded them.
Fixes #
=> ✨ Enable prefetch in create kind cluster script

core-chart/templates/NOTES.txt
This PR removes spurious escaping of the brackets in the NOTES.txt template in the core Helm chart.
Fixes #
=> 🐛  Remove spurious escaping of brackets in NOTES.txt template

pkg/transport/generic/generic_transport_controller.go
This PR fixes an oversight in the generic transport controller. When it logs an info message about a transient error, actually showing the error was overlooked.
Fixes #
=> 🌱  Include error in warning about sync fail

docs/content/direct/known-issues.md, docs/content/direct/release-notes.md, pkg/transport/generic/generic_transport_controller.go, test/e2e/ginkgo/multiple_cluster_deployment_test.go, test/util/util.go
This PR stops the thrashing of workload objects in a WEC (see #2634) IF the transport-controller's max-num-wrapped is 1. The trick is to make the name of the `ManifestWork` a function of its one and only workload object.
This PR is built on #2641, and I will rebase this one if that one merges first.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-no-thrash/direct/release-notes/#0260-alpha1
Hopefully this will fix #2634 but I want to wait for confirmation from @cwiklik before closing that Issue.
=> 🐛  Stop thrashing workload objects in the WEC, when max-num-wrapped is 1

docs/content/direct/release.md, monitoring/README.md
This PR fixes a couple of oversights. The first is the mention of the version of ks/ocm-status-addon to use in `monitoring/README.md`. The other oversight is the fact that this was not mentioned in the release process document.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-monitoring-dependency/direct/release/#reacting-to-a-new-ocm-status-addon-release
Fixes #
=> 📖  Update ocm-status-addon version in monitoring/README

hack/Dockerfile.kubectl, hack/build-clusteradm-image.sh
Improve scripts for building some of the service images
- remove `jq` and `yq` from the `kubectl` container image
- fix dir change in `build-clusteradm-image.sh`
Fixes #
=> ✨ Improve scripts for building some of the service images

hack/build-clusteradm-image.sh
This PR changes the script for building the clusteradm image so that it is informative rather than confusing about where the checkout is going. This undoes a bad suggestion that I made to the earlier PR on this script.
Fixes #
=> 🌱  Make clusteradm build folder evident to user

docs/content/direct/known-issues.md, docs/content/direct/release-notes.md
This PR updates the documentation for release 0.25.1 to document the pathology that I realized while thinking about Issue #2634 .
This PR also adds a note to the "known issues" index page to explicitly state its relation with bugs.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-mw-thrash-0251/direct/release-notes/
Fixes #
=> 📖  [release-0.25.1] Document workload object thrashing

scripts/kubestellar-snapshot.sh
This PR fixes a spelling error in the directory name where BindingPolicy objects are dumped by the `kubestellar-snapshot.sh` script.
Fixes #
=> 🐛  Fix speling error in kubestellar-snapshot.sh

core-chart/values.yaml, docs/content/direct/release-notes.md, docs/mkdocs.yml, scripts/create-kubestellar-demo-env.sh
This PR updates the self-references in preparation for the next alpha release. This is urgent because merging #2645 broke `main`.
Preview in https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0260a3/readme/
Fixes #
=> ✨  Update self-references for 0.26.0-alpha.3 release

pkg/binding/bindingpolicy-resolution.go, pkg/binding/selectors.go, pkg/status/combinedstatus-resolution.go, pkg/status/combinedstatus-resolver.go, test/e2e/ginkgo/multiple_cluster_deployment_test.go
This PR starts with a commit that changes the ordering of setup steps in some ginkgo test cases, to better exercise more paths through the controllers.
That revealed some bugs, which the later commits expose and fix.
This might shed some light on #2687
=> 🌱  Fix StatusCollector event order bugs in status controller

scripts/create-k3s-cluster-with-SSL-passthrough.sh
This pull request addresses issue [#2685](https://github.com/kubestellar/kubestellar/issues/2685) by modifying the `create-k3s-cluster-with-SSL-passthrough.sh` script to use a dependency approach for installing `k3s`. The script now checks if `k3s` is already installed before attempting to install it. Additionally, the script ensures the necessary directory exists before writing the kubeconfig file.
The original script performs an unconditional and un-parameterized install of `k3s`, which is excessive and can cause issues if `k3s` is already installed on the system.
- Added a check to see if `k3s` is already installed.
- Ensured the `.kube` directory exists before writing the kubeconfig file.
- Parameterized the script to allow users to skip the installation if `k3s` is already installed. …
=> ✨:Correct installation script

docs/content/direct/example-scenarios.md
This PR updates Example Scenario 4 to track the recent API change wrt where `wantSingletonReportedState` appears.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-0260a3-fix-ex4/direct/example-scenarios/#scenario-4-singleton-status
This addresses #2694 in one of the relevant branches.
=> :book: [release-0.26.0-alpha.3] Track change in where `wantSingletonReportedState` appears

docs/content/direct/example-scenarios.md
This PR updates example scenario 4 in the `main` branch to track the recent change in where the `wantSingletonReportedState` bit goes in a `BindingPolicy` object.
This is like #2695 but for the `main` branch instead of a release.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-fix-ex4/direct/example-scenarios/#scenario-4-singleton-status
Fixes #2694
=> 📖  Track change in where `wantSingletonReportedState` appears

ONBOARDING.md, README.md, docs/content/direct/example-wecs.md
When I am going through the docs and CONTRIBUTING.MD or Readme.md I figure out most of the links are broken
Fixes #2727
=> :book: resolve broken links in documentation

ONBOARDING.md, README.md, docs/content/direct/example-wecs.md
This PR fixes some broken links in the "release-0.25.1" "version" of the website. This is a copy of the fixes in #2728 .
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-0251-fixlinx/direct/get-started/#create-and-register-two-workload-execution-clusters
Fixes #2743
=> 📖  resolve broken links in documentation

CONTRIBUTING.md, docs/content/direct/pr-signoff.md, docs/mkdocs.yml
This PR updates the website page about sign-off and signing. This is good because the page mixed up the two in a confusing way.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-signoff/direct/pr-signoff/
Fixes #
=> 📖 Clarify documentation about signoff and signing

core-chart/values.yaml, docs/content/direct/get-started.md, docs/content/direct/release-notes.md, docs/content/direct/release.md, docs/content/direct/start-from-ocm.md, docs/mkdocs.yml, scripts/create-kubestellar-demo-env.sh
This PR updates the self-references and release notes in preparation for the first RC of the next regular release.
This PR also removes some temporary hackery that is no longer needed.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0260rc1/readme/
Fixes #
=> ✨  Update self-references in prep for release 0.26.0-rc.1

docs/content/direct/get-started.md, docs/mkdocs.yml, docs/requirements.txt
Fixes #2771
This PR resolves issue https://github.com/kubestellar/kubestellar/issues/2771 by updating the docs/requirements.txt file to ensure compatibility with Python releases 3.12 or higher. The changes include:
Upgraded dependencies in docs/requirements.txt to their latest versions that support Python 3.12+.
Verified compatibility across Python 3.12 and higher to ensure a smooth installation process for documentation-related dependencies.
Fixed :- mkdocs.yml, getstarted.md files for newer compatible versions
=> ⚠️ breaking change: docs/requirements.txt satisfiable for recent Python releases

docs/content/direct/pre-reqs.md, hack/check_pre_req.sh, scripts/check_pre_req.sh
This PR updates the `{scripts,hack}/check_pre_req.sh` script to check that the container runtime's OS has been adjusted according to https://kind.sigs.k8s.io/docs/user/known-issues#pod-errors-due-to-too-many-open-files . This is good because we have been having trouble with that requirement not being met and people being confused by the resulting behavior.
This PR also updates the prereqs doc to state this requirement more prominently.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-check-kind-config/direct/pre-reqs/#additional-software-for-the-getting-started-setup and #additional-software-for-building-kubestellar-from-source-and-testing and #examples .
Fixes #
=> ✨  Check sysctl fs stuff in preflight

docs/content/direct/example-scenarios.md
This PR excises the now-incorrect and never-needed listing of ManifestWork objects from example scenario 1.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-not-manifestworks/direct/example-scenarios/#scenario-1-multi-cluster-workload-deployment-with-kubectl
Fixes #
=> 📖  Remove outdated and unneeded example listing of manifestworks

docs/content/direct/transforming.md, pkg/transport/generic/filtering/service.go, pkg/util/unstructured.go
An annotation is used to signal the preserving of certain fields in workload objects. But the key of the annotation is not consistent across code and doc. This PR is a fix to the inconsistency.
=> 🐛 Make an annotation key consistent

scripts/kubestellar-snapshot.sh
Fix a problem with `echov` being invoked by the `on_exit` function before being defined
Here is an example of the problem being solved:
```shell
$ kubestellar-snapshot.sh --foo
kubestellar-snapshot.sh: unknown flag
kubestellar-snapshot.sh: line 182: echov: command not found
```
Fixes #
=> 🐛 Fix a problem with `echov` in `kubestellar-snapshot` script

pkg/status/combinedstatus-resolution.go, pkg/status/combinedstatus-resolver.go
This PR updates the status controller to make each CombinedStatus object have an OwnerReference to its workload object.
Fixes #2808
=> ✨  Add OwnerReference from CombinedStatus to workload obj

.goreleaser.yaml
After multiple reviews, I found out, if we are to build the sbom using the go-releaser functionality, we have remove the `skip_upload: true ` option , this would obviously lead to creation of some unrequired binaries as seen before, but still serves our purpose. Another way to do it is to create a hook in go-releaser and use an external script to create an sbom.
I have tested it in a test repo [here](https://github.com/jaydee029/test)
It consists of a basic go-releaser config, and multiple releases (with variations)
As soon as this is merged I'll create a PR for the signed binary issue
Fixes #2613
=> ✨: Added sbom generation

.github/workflows/pr-test-integration.yml
The PR changes the way that the pr-test-integration workflow refers to actions/checkout, to improve supply chain security by pinning to a specific SHA256 instead of a tag.
These address part of #2844
=> 🐛  Pin actions/checkout to SHA in pr-test-integration

scripts/check_pre_req.sh
Update sysctl error URL and refactor URL handling in check_pre_req.sh: This commit updates the sysctl error URL to point to the new installation errors documentation page (https://docs.kubestellar.io/release-0.27.0/direct/installation-errors#pod-errors-due-to-too-many-open-files). Additionally, the URL handling in the check_pre_req.sh script has been refactored by introducing BASE_URL and VERSION variables, making it easier to update the documentation URL in the future.
```
"Update sysctl error URL and refactor URL handling in check_pre_req.sh: This commit updates the sysctl error URL to point to 
the new installation errors documentation page (https://docs.kubestellar.io/release-0.27.0/direct/installation-errors#pod-errors-due-to-too-many-open-files). Additionally, 
the URL handling in …
```
=> 🌱 Update sysctl error URL and refactor URL handling in check_pre_req script

.github/workflows/ocp-self-runner.yml, .github/workflows/pr-test-e2e.yml, .github/workflows/pr-test-integration.yml, .github/workflows/test-latest-release.yml
This PR pins the version of clusteradm used in CI to 0.10.1, because 0.11.0 changes a ServiceAccount name and breaks our scripting.
Fixes #
=> 🐛  Pin clusteradm to release 0.10.1

scripts/create-kind-cluster-with-SSL-passthrough.sh
Upgrade NGINX ingress to v1.12.1 to patch vulnerabilities CVE-2025-24513, CVE-2025-24514, CVE-2025-1097, CVE-2025-1098, and CVE-2025-1974.
See https://thehackernews.com/2025/03/critical-ingress-nginx-controller.html
Fixes #
=> 🐛 Patch NGINX vulnerabilities

docs/content/direct/get-started.md, docs/content/direct/pre-reqs.md, scripts/check_pre_req.sh
This PR updates the instructions to install the latest **usable** version of clusteradm and to emphasize that check_pre_req.sh has to succeed, and restores the RED X that appears when version checking on clusteradm fails.
Website preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-install-right-clusteradm/direct/pre-reqs/#software-prerequisites-for-using-kubestellar
Fixes #
=> 📖  Doc install right clusteradm

docs/content/direct/get-started.md, docs/content/direct/pre-reqs.md
This PR updates the pre-reqs page and the check_pre_req.sh script, so that the instructions for installing clusteradm install the latest usable version rather than the troublesome 0.11.0.
This PR updates the `release-0.27.1` branch.
Website preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-rel0271-install-right-clusteradm/direct/pre-reqs/
Fixes #
=> 📖  [release-0.27.1] Update install instructions for clusteradm

docs/content/direct/get-started.md, docs/content/direct/pre-reqs.md, docs/content/direct/troubleshooting.md
This PR updates the `release-0.27.1` version of the website, fixing botches about clusteradm and helm and enhancing troubleshooting. I had made earlier PRs intended to update this version of the website but botched them, they actually got opened against `main`.
Website preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-rel0271-triplefix/direct/pre-reqs/
Fixes #
=> 📖  [release-0.27.1] Fix docs about clusteradm and helm and troubleshooting

docs/content/direct/ui-intro.md
There was an extraneous reference to a kubeflex demo video at the end of the ui-intro.md file, the result of a cut-and-paste error. 
It has been removed.
Preview at https://kproche.github.io/kubestellar/doc-fix_ui-intro/direct/ui-intro/
Fixes #
=> 📖  Elide reference to KubeFlex from ui-intro.md

core-chart/values.yaml, docs/content/direct/release-notes.md, docs/mkdocs.yml, scripts/check_pre_req.sh, scripts/create-kubestellar-demo-env.sh
This PR updates the self-references in preparation for the patch release 0.27.2.
This PR also undoes the inadvertent release reversion to `docs/mkdocs.ysml` in #2861 .
Website preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-prep4-0272/readme/
Fixes #
=> ✨  Prep for patch release 0.27.2

CONTRIBUTING.md, docs/content/contribution-guidelines/contributing-inc.md
-->
This PR is intended as a better way to fix the problem noted in PR #2873 :
When viewing the file CONTRIBUTING.md in the Github repository, relative links intended for rendering on the website return 404 errors.
This is a side effect of the contents of CONTRIBUTING.md being pulled into the webpage built by contributing-inc.md via the include-markdown plugin of mkdocs.
For this PR, the relative links in the two files have been isolated: website relative links are now in _contributing-inc.md_ between the include directives, and GitHub repo relative links are in sections of _CONTRIBUTING.md_ which are *not* pulled into the rendered website.
To compare the link behaviours, 
The webpage rendering may be previewed at 
https://kproche.github.io/kubestellar/doc-contribfix/contribution-guideline …
=> 📖 Fix Contribution Docs: Move Relative web Links into -inc file

core-chart/templates/argocd/rbac.yaml
Fix mismatch in SA name in Helm template for setting up ArgoCD
Fixes #
=> 🐛 Fix mismatch in SA name for ArgoCD setup in Helm

.gha-reversemap.yml, .github/workflows/add-to-project.yml, .github/workflows/broken-links-crawler.yml, .github/workflows/create-our-meeting-bi-weekly.yml, .github/workflows/docs-gen-and-push.yml, .github/workflows/elapsed-time-collector.yml, .github/workflows/full-broken-links-crawler.yml, .github/workflows/goreleaser.yml, .github/workflows/greetings.yml, .github/workflows/ocp-self-runner.yml, .github/workflows/pr-test-e2e.yml, .github/workflows/pr-test-integration.yml, .github/workflows/pull_request.yml, .github/workflows/spellcheck_action.yml, .github/workflows/test-latest-release.yml, .github/workflows/verify.yml, hack/gha-reversemap.sh
As per of [the following discussion](https://github.com/kubestellar/kubestellar/pull/2883#issuecomment-2848030049), a rework has been done to enhance the functionnality of the reverse map and its script.
**Goal**: move away of tag/branch as actions' version. Usage of commit sha instead to avoid supply chain attack.
Update includes:
- Usage of the script as a CLI with `update/reversemap`, `update-action-version` and `apply-reversemap` operations.
- Reverse map contains `sha`, `tag`, `url-sha` and `url-tag` as a KV for each actions
Make use of this hack script as part of CI to:
- test to ensure that no actions has been used with a tag or branch as version. 
- update on approval an action version in its reverse map and workflows right from GitHub.
If part of the CI, perhaps creating …
=> 🐛 implementation of the script as CLI to solve Supply Chain security on CI

hack/build-helm-image.sh
This PR updates the `hack/build-helm-image.sh` script so that when invoked on version 3.16.anything of Helm it will pick up more recent dependencies. This is good because it will remove all the vulnerabilities that https://artifacthub.io/packages/helm/kubestellar/core-chart note for the `quay.io/kubestellar/helm:3.16.1` container image.
This is a copy of #2891, which got wedged during the Prow migration.
Fixes #
=> 🌱  Make building helm 3.16 get good dependencies

.github/spellcheck/.spellcheck.yml
This PR updates the `spellcheck.yml` configuration to fix issues related to HTML tags being incorrectly checked by the spellchecker. 
- Adjusted `pyspelling.filters.html` to properly ignore HTML elements like `code`, `pre`, `style`, and `script`.
- Updated the configuration to handle hidden and invisible HTML content more accurately.
Fixes #2507
=> 🐛  Fix: Ignore invisible HTML content in spellchecker (Fixes #2507)

.github/workflows/pr-verifier.yaml
The current `pr-verifier.yaml` workflow is vulnerable to command injection when processing PR titles. Unescaped characters or injected commands can be executed in the shell during the GitHub Actions run.
- Secure the PR title handling by escaping characters properly using `printf %q`.
- Prevent command injection by avoiding direct evaluation of untrusted input in the shell.
- Add `set -euo pipefail` for shell safety.
- Use `grep -qE` for secure matching of allowed emojis in the PR title.
- Updated `pr-verifier.yaml` to:
- Add safe shell practices.
- Properly handle and escape PR title.
- Ensure the PR title is validated securely without running injected commands.
This change prevents arbitrary command execution via PR titles, improving the security of the GitHub Actions workflow.
Please …
=> 🌱 Test : Fix  command injection vulnerability in PR title validation

.gha-reversemap.yml, .github/workflows/goreleaser.yml, .github/workflows/ocp-self-runner.yml, .github/workflows/pr-test-e2e.yml, .github/workflows/pr-test-integration.yml, .github/workflows/test-latest-release.yml, hack/gha-reversemap.sh
This PR makes two changes. One is to liberalize the check that the `hack/gha-reversemap.sh` script makes on the version of yq, so that any v4.45.X is accepted. This is good because 4.45.2 was recently released.
The other change is to pick up the latest release of the setup-go action.
This will supersede #2902 
Fixes #
=> ✨ Liberalize yq version check, bump setup-go to 5.5.0

.github/workflows/verify.yml
This pull request updates the GitHub Actions workflow in `.github/workflows/verify.yml` to use a specific commit hash for the `actions/checkout` action instead of a version tag. This change ensures a more stable and secure workflow by pinning the action to a known commit.
* [`.github/workflows/verify.yml`](diffhunk://#diff-b32b798d8ec577b859922a84b90dfe871b19fad404cc6fa7a6fe163f079fbcbfL13-R13): Updated the `uses` field for the `actions/checkout` step to reference the specific commit `11bd71901bbe5b1630ceea73d27597364c9af683` instead of the `v4` version tag
Fixes #2910
=> 🌱 chore: update checkout action version in PR title verifier workflow

hack/build-clusteradm-image.sh
This PR updates the script for building the clusteradm container image so that it gets later versions of some dependencies, picking up security fixes.
I have rebuilt quay.io/kubestellar/clusteradm:0.10.1 and quay.io/kubestellar/clusteradm:0.11.0 with the revised script.
Fixes #
=> 🐛  Make clusteradm build get some later dependencies

core-chart/templates/postcreatehooks/wds.yaml, scripts/create-kubestellar-demo-env.sh, test/e2e/common/setup-kubestellar.sh
This PR bumps the version of the quay.io/brancz/kube-rbac-proxy image used in the kubestellar-controller-manager Deployment from v0.18.0 to v0.19.1. The benefit is fewer security vulnerabilities. The downside is that v0.19.1 is built on Kubernetes 1.31, while the rest of KubeStellar uses Kubernetes 1.30. I suspect that this inconsistency will not be problematic because of the narrow job of this particular image.
Fixes #
=> ✨  Bump kube-rbac-proxy from 0.18.0 to 0.19.1

docs/content/readme.md
Previously, when clicking on "Contributing guide" in the documentation, the link incorrectly opened:
https://docs.kubestellar.io/release-0.27.2/readme/Contribution%20guidelines/CONTRIBUTING.md
which resulted in a broken or not found page.
The expected behavior was to open the proper contribution guide at:
/direct/contribute/
This PR fixes the link so that clicking "Contributing guide" now correctly navigates to the /direct/contribute/ page, improving user experience and eliminating the broken link issue.
i fixed it and tested , now the link open correctly on clicking Contributing
=>  📖  Fix: Contribution Guide Link Not Opening from Documentation

docs/content/direct/core-chart.md, docs/content/direct/get-started.md
:book: 📖 docs: Fix Helm command syntax in documentation
This PR updates the Helm command syntax in the KubeStellar documentation to use the correct format for `--set-json` flags. The changes make the commands more reliable across different shell environments, particularly on Ubuntu 24.04.
1. Updated `--set-json='KEY=VALUE'` to `--set-json KEY='VALUE'` for better shell compatibility
2. Added proper quoting around shell variables (e.g., `"$KUBESTELLAR_VERSION"`)
3. Changed `--set-json='verbosity.default=5'` to `--set verbosity.default=5` for consistency
- Fixes potential command failures on Ubuntu 24.04 and other Linux distributions
- Follows Helm's recommended usage patterns
- Makes the documentation more reliable for new users
Fixes # (add issue number if applicable)
I have not raised an …
=> fix: update Helm command syntax in documentation

.goreleaser.yaml
There was an error in this workflow as described in this issue -- getting this error in workflow - only version: 2 configuration files are supported, yours is version: 0, please update your configuration.
- Updated the goreleaser.yml file and bumped up the version to fix the error properly.
Fixes #2930
=> 🐛 bug: fixed goreleaser version update error 

test/util/util.go
Improve E2E test logging to show detailed output during setup failures.
The Ginkgo E2E tests were failing with timeouts but provided no indication of where in the `setup-kubestellar.sh` script the timeout occurred, making debugging very difficult.
Modified `test/util/util.go` to stream output from the setup script in real-time, providing complete visibility into the setup process and exact failure points.
- Updated `SetupKubestellar()` function to show live output from `setup-kubestellar.sh`
- Now displays detailed kind cluster creation, kubeadm init process, and API server startup logs
- Enables precise identification of where setup failures occur
Fixes #2200
=> 🐛bug: improve e2e ginkgo test logging for setup debugging

Makefile
```
KO_DOCKER_REPO=ko.local ko build -B ./cmd/controller-manager -t c0f945577 --platform linux/amd64
2025/06/13 12:15:21 Using base cgr.dev/chainguard/static:latest@sha256:797e62f43d04d792e9f930913e7d9f5a63e92bd19ca5e7e5139a692decee2dbc for github.com/kubestellar/kubestellar/cmd/controller-manager
2025/06/13 12:15:22 Building github.com/kubestellar/kubestellar/cmd/controller-manager for linux/amd64
2025/06/13 12:15:45 Loading ko.local/controller-manager:35529aa9721bd8be3f09f3daaa2d6185ef93d83b71190e9432d5de1ef31d4ef3
2025/06/13 12:15:46 Loaded ko.local/controller-manager:35529aa9721bd8be3f09f3daaa2d6185ef93d83b71190e9432d5de1ef31d4ef3
2025/06/13 12:15:46 Adding tag c0f945577
2025/06/13 12:15:46 Added tag c0f945577
ko.local/controller-manager:35529aa9721bd8be3f09f3daaa2d6185ef93d83b71190e94 …
```
=> 🌱 other/misc: add log for better understanding of docker context error!

docs/README.md
This PR updates the documentation regarding rendering of the website by GitHub, in two ways.
1. Note the restriction on branch name.
2. Explain how to enable GitHub Pages on a pre-existing fork.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-rendering-more/contribution-guidelines/operations/document-management/#serving-up-documents-globally-from-a-fork-of-the-repository-via-github and https://mikespreitzer.github.io/kcp-edge-mc/doc-rendering-more/contribution-guidelines/operations/document-management/#enabling-github-pages-for-a-fork-that-already-exists
Unfortunately, this PR overlaps with #3033. Ordinarily I would try to avoid such a conflict, but I think this PR may be urgent because it adds critical information for preparing successful PRs.
Fixes #
=> 📖  Note branch name restriction and fork repair

docs/content/direct/galaxy-intro.md
Found a broken link in this [documentation page](https://docs.kubestellar.io/release-0.28.0/direct/galaxy-intro/#learn-more) while exploring Kubestellar.
This PR fixes a broken link in [docs/content/direct/galaxy-intro.md](https://github.com/kubestellar/kubestellar/blob/main/docs/content/direct/galaxy-intro.md?plain=1#L31). 
There was a typo in underlying reference that was causing 404 error. The issue was discovered while exploring the docs.
Preview at https://greninja517.github.io/kubestellar/direct/galaxy-intro/#learn-more
=> 📖 Fix the broken link for Galaxy repository in galaxy.md file

scripts/check_pre_req.sh
This PR fixes the Warning Message display by `kubeflex` new version ( `0.9.0` ) while running _/scripts/check_pre_req.sh_  script to show the actual version of `kubeflex`.
Fixes #3078
=> 🐛 Fix the Warning message from kubeflex to display actual kubeflex version

ONBOARDING.md, README.md, docs/content/Community/_index.md, docs/content/Community/partners/fluxcd.md, docs/content/Community/partners/kyverno.md, docs/content/Community/partners/mvi.md, docs/content/contribution-guidelines/contributing-inc.md, docs/content/direct/contribute.md, docs/content/direct/user-guide-intro.md, docs/content/readme.md, docs/mkdocs.yml
This PR updates all the references of  `kubestellar-dev` slack channel that was previously under Kubernetes workspace to point to new slack channel under CNCF workspace as described in the issue #3122 in the entire repo and docs. Community Inviter URL for the new CNCF workspace has also been updated in the relevant files. 
Shortcut URL `https://kubestellar.io/slack` is still pointing to old Kubernetes Slack channel which needs to be updated by the maintainers who are managing the domain names.
Preview at: https://greninja517.github.io/kubestellar/doc-cncf-slack-update/
Fixes #3122
=> 📖 CNCF Slack Update: Update all Slack URLs to point to new CNCF Slack Channel across the repo and docs

docs/content/direct/observability.md, docs/mkdocs.yml
📖 Summary
This PR refines the Observability documentation based on feedback from [PR #2992](https://github.com/kubestellar/kubestellar/pull/2992).
It clarifies and expands the details around controller metrics and profiling endpoints.
Key improvements:
•	Added kubestellar-controller-manager entry for port 8080 (HTTP access without auth)
•	Clarified when HTTPS and authentication are required — even for direct Pod access
•	Corrected status-agent-controller debug endpoint port from 8082 → 8083
•	Updated notes to reflect Helm configurability status (per [issue #2158](https://github.com/kubestellar/kubestellar/issues/2158))
•	Improved section titles for accuracy (e.g., “Accessing KubeStellar Controller Metrics”)
•	Fixed outdated mkdocs.yml link to point to #testing-website-prs directly
These …
=> 📖 finalize observability page with protocol and port clarifications

docs/content/contribution-guidelines/operations/docs-styleguide.md, docs/content/contribution-guidelines/operations/document-management.md, docs/content/direct/contribute.md, docs/mkdocs.yml
As the number of contributors to the KubeStellar documentation (and docs PRs) has grown, the need for a Style Guide to aid in consistent documentation has become apparent. This is intended as a stepping-off point for that Guide, intended to be used in conjunction with the Design Guide being currently developed 
The Style Guide may be previewed at 
https://kproche.github.io/kubestellar/doc-add-styleguide/contribution-guidelines/operations/docs-styleguide/
=> 📖  Add elementary style guide to website contribution section

.github/workflows/check-docs-pr-preview.yml
This PR fixes a couple of bugs in the GitHub Actions workflow that checks whether a PR that modifies the website includes a link to a preview.
- Fixes the script so that it does not crash when there is no preview link.
- Removes metacharacter injection vulnerability by removing use of `echo -e`
Fixes #
=> 🐛  Make doc preview check not crash

docs/content/direct/get-started.md
Fixed broken link in get-started documentation as reported in issue #3137.
The get-started documentation had a broken link in the "Note for Windows users" section that was referencing a non-existent file `docs/content/direct/knownissue-wsl-ghcr-helm.md`.
- Fixed the broken link reference
- Updated the link to point to the correct file `docs/content/direct/knownissue-helm-ghcr.md`
- Ensured the documentation flows correctly for Windows users
Fixes #3137
- Updated broken link in `docs/content/direct/get-started.md`
- Verified the target file exists and contains relevant information
=> 📖 Update get-started documentation

docs/content/contribution-guidelines/operations/docs-styleguide.md
This is a tiny PR fixing two typos and one bad contraction in the original version of the Style Guide
Preview available at https://kproche.github.io/kubestellar/doc-stylefixtypos/contribution-guidelines/operations/docs-styleguide/
Fixes #3149
=> 📖 Style Guide: fixing initial typos

core-chart/templates/postcreatehooks/install-status-addon.yaml, core-chart/templates/postcreatehooks/its-hub-init.yaml, docs/content/direct/get-started.md, scripts/create-kubestellar-demo-env.sh, test/e2e/common/setup-kubestellar.sh
This PR fixes the bugs introduced in #3121:
- usage of the released Helm chart is followed by commands that apply to the latest version in `main` rather than the last release;
- a quoting problem caused premature completion of waiting for the kubeconfig file to appear.
This PR also removes an unnecessary copy of a block of waiting commands.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-pullback-its-split/direct/get-started/#wait-for-its-to-be-fully-initialized
Fixes #
=> 🐛 Undo bugs introduced in split of ITS PCH into two

docs/content/direct/release.md
This PR documents the proper time to finish the work that was prematurely included in PR #3121 and temporarily undone in #3163 .
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-next-release-change/direct/release/#making-a-new-kubestellar-release
Fixes #
=> 📖  Put one-shot tracking work in release process

SECURITY-INSIGHTS.yml, SECURITY.md
The dependency policy check was not passing in CLOMonitor earlier which could have caused some security vulnerabilities.
After making the required changes by reading the documentation, I ran the CLOMonitor tests against my local branch and it passed the dependency policy check, which earlier was not passing.
preview link : https://antedotee.github.io/kubestellar/doc-dependency-policy-fix
Relates to #2595
=> ✨ dependency policy fix of CLOMonitor

docs/content/direct/get-started.md, scripts/create-kubestellar-demo-env.sh, test/e2e/common/setup-kubestellar.sh
Restores the documentation and script changes that were prematurely included in PR #3121 and rolled back in PR #3163. Updates wait commands to use the correct PostCreateHook names.
Changes:
- docs/content/direct/get-started.md: Replace its-with-clusteradm waits with install-status-addon and its-hub-init waits
- scripts/create-kubestellar-demo-env.sh: Same replacement for demo environment script  
- test/e2e/common/setup-kubestellar.sh: Replace conditional logic with unconditional quad wait
This aligns documentation with the current PostCreateHook structure and ensures consistent behavior across all environments.
Preview at https://rishi-jat.github.io/kubestellar/doc-restore-pch-waits-3121/
Follow-up to #3121
=> 🐛fix(docs): restore PostCreateHook wait commands for install-status-addon and its-hub-init

hack/build-clusteradm-image.sh
This PR bumps some dependencies in hack/build-clusteradm-image.sh to pick up some security fixes.
Fixes #
=> 🌱 Bump dependencies in hack/build-clusteradm-image.sh

docs/content/contribution-guidelines/contributing-inc.md
- Explicitly documents the issue archive URL in the “Issues” section
- Guides users to search existing and closed issues before opening new ones
- Improves transparency and aligns with OpenSSF Best Practices Badge requirements
fixing #3230 
Preview: https://shivansh-source.github.io/kubestellar/archive_issue
=> 📖docs: document issue archive in CONTRIBUTING.md

.gitattributes
This pull request adds a .gitattributes file to the repository to:
Enforce consistent LF line endings across all platforms by setting * text=auto eol=lf.
Mark generated files (e.g., zz_generated.*.go and files inside /pkg/client/) with linguist-generated=true and -diff to minimize diff noise both locally and in GitHub pull requests. 
fixes #3211
=> ✨ Add .gitattributes to normalize line endings and ignore generated files in diffs

docs/content/contribution-guidelines/operations/docs-styleguide.md
Preview: https://eeshaansa.github.io/kubestellar-core/doc-a11y/contribution-guidelines/operations/docs-styleguide/
This PR addresses the addition of a new “Accessibility Guidelines” section to the existing KubeStellar Documentation Style Guide.
Replacement for #3178 . Same commit; name branch to support docs workflow
#3130 
Fixes #3160
=> 📖  Expand a11y section in docs style guide

.github/workflows/golangci-lint.yml
The `--fast` flag was deprecated and removed in golangci-lint v2.4.0, but the workflow was still using it.
- Removed the deprecated `--fast` flag from golangci-lint command
-  Updated workflow step name from "Run golangci-lint (Fast Mode)" to "Run golangci-lint" 
- Fixed workflow summary to accurately reflect actual triggers (weekly + manual dispatch only)
- Fixed resource impact description 
-  Tested locally - golangci-lint runs without errors
-  Tested on fork's GitHub Actions - workflow passes successfully
-   Verified YAML syntax and workflow structure
Fixes #3264
=> 🐛 bug: golangci-lint workflow: remove deprecated --fast flag

docs/content/contribution-guidelines/contributing-inc.md, hack/gha-reversemap.sh
This PR improves the error handling in `hack/gha-reversemap.sh` so that it prints an understandable and actionable error message in all cases where the GitHub API rate limit is hit.
This PR also removes the insistence that the envar GITHUB_TOKEN is set, because it that setting is rarely needed and there is now a serviceable error message when the problem occurs.
This PR also improves the website documentation of that script a little.
Preview at https://mikespreitzer.github.io/kcp-edge-mc/doc-actions/contribution-guidelines/contributing-inc/#github-action-reference-discipline
Fixes #
=> 🌱 Improved error handling in hack/gha-reversemap.sh

go.mod, test/performance/latency-controller/README.md, test/performance/latency-controller/internal/controller/controller.go, test/performance/latency-controller/kubestellar-dashboard.json, test/performance/latency-controller/main.go
This PR introduces a new `GenericLatencyCollectorReconciler` controller responsible for observing and collecting end-to-end latency metrics across the Kubernetes multi-cluster landscape using KubeStellar.
The controller tracks:
- Downsync durations: from WDS Deployment to WEC Deployment
- Upsync durations: from WEC Deployment status back to WDS status
- Individual lifecycle stages such as:
- Packaging
- Delivery
- Activation
- WorkStatus reporting
The metrics are exposed as Prometheus histogram metrics and a workload count gauge, registered under `kubestellar_*` prefixed metric names.
A Grafana dashboard can consume these Prometheus metrics to visualize latency trends.
> 📊 **See the screenshots below for a sample Grafana dashboard visualization.**
- Go to the `README.md` file for detailed …
=> ✨  Add LatencyCollector controller to collect end-to-end metrics across clusters

monitoring/install-ks-monitoring.sh
This PR enables Grafana dashboards to be embedded within the monitoring tool UI. It updates the Grafana configuration to allow iframe embedding by relaxing default security headers.
=> ✨ Allow embedding for grafana

docs/content/direct/roadmap.md
This PR removes stop applying PCHes too early point from roadmap as it is closed.
Preview at : https://gaurab-khanal.github.io/kubestellar
Fixes #3362
=> 📖  Remove stop applying PCHes too early from roadmap
